- teuthology/run_tasks.py
There are other log messages in run_tasks that you could use to figure out if you went into interactive mode during task execution or clean up, but this makes it clearer without having to do that.
> Make log messages in run_tasks.py specify when the exception occurred.

- teuthology/run.py
- teuthology/run_tasks.py
- teuthology/suite.py
- teuthology/task/internal.py
- teuthology/test/test_suite.py
This changes existing functionality in teuthology-suite that used to block runs from being scheduled if they contained jobs with missing packages.  This check is now done with a new task that is always ran first and will fail the job with the 'dead' status if there are packages missing.
A count of jobs with missing packages can be seen if you use the ``--dry-run`` flag with teuthology-suite.
> Schedule jobs with missing packages, but fail them quickly

- teuthology/run.py
- teuthology/test/test_run.py
I often find myself wanting the original teuthology command when debugging a failed job.  This will give me that.
> Log the teuthology command being ran at the debug level

- teuthology/task/install.py
> Don't suppress stdout for most apt-get ops

- teuthology/task/install.py
I also put in a couple TODO comments for things to look at later.
I was looking over the install task yesterday and the 'extras' functionality really confused me.  It took me a while to unravel it's purpose so I thought I'd leave a comment so the next dev looking at this code doesn't have the same confusion.
> Added some comments clarifying functionality in the install task.

- teuthology/misc.py
- teuthology/test/test_get_distro.py
- teuthology/test/test_get_distro_version.py
This fixes the regression in issue #10621
> Make teuthology-lock respect --os-type

- teuthology/config.py
- teuthology/exceptions.py
- teuthology/packaging.py
- teuthology/task/kernel.py
- teuthology/test/test_packaging.py
If you have 'brew: <build_id>' in the 'kernel' stanza of your teuthology yaml config this will install the kernel from that build_id on the specified node.  This only works on rhel systems.
I've also tried to abstract the functions that talk with brew into their own functions in teuthology.packaging so we can reuse them in the future to download other things from brew.
For: http://tracker.ceph.com/issues/10561
(I might still want to write tests for this, looking mainly for feedback right now)
> Enable kernel installs from brew

- scripts/lock.py
- teuthology/misc.py
- teuthology/provision.py
- teuthology/test/test_get_distro.py
- teuthology/test/test_get_distro_version.py
We don't think this is being used anymore so we're gonna deprecate this feature and remove the unused code.
See, http://tracker.ceph.com/issues/10625
> deprecate support for a custom downburst config

- teuthology/exceptions.py
- teuthology/orchestra/run.py
- teuthology/task/tests.py
With this feature we can label any remote calls we perform.  If the command fails during execution it'll print out the label so it's more apparent when looking at log output what the initial purpose of the command being ran was.  This can help us to determine if a job failure is environmental, a teuthology failure or a legit ceph test failure.  Of course, it depends on the writer of the test to properly use the new label kwarg.  See, http://tracker.ceph.com/issues/10699
Also, I've started a simple testing task I used to make sure this feature was working correctly.  I've got another branch that uses pytest to autodiscover tests in this new task but I thought that'd be best in another PR.
Here's sample output from a test run of this branch.
```
2015-02-03 10:04:25,981.981 …
```
> Add a label to run.run

- teuthology/lockstatus.py
- teuthology/orchestra/remote.py
- teuthology/task/tests/test_locking.py
There is also some minor test clean up and I made the existing machine_type test use the new property.
> Adds a machine_type property to orchestra.remote.Remote

- README.rst
* replace sample usage of deprecated schedule_suite.sh with that of
teuthology-suite
* add a pointer to `teuthology-suite --help`
Fixes: #8678
> README: update with teuthology-suite

- teuthology/task/tests/__init__.py
This makes the logs easier to read.
With ``-s``:
```
2015-02-11T17:17:24.966 INFO:teuthology.run_tasks:Running task tests...
2015-02-11T17:17:25.106 INFO:teuthology.task.tests:test_locking:TestLocking.test_correct_os_type Skipped: os_type was not defined
2015-02-11T17:17:25.109 INFO:teuthology.task.tests:test_locking:TestLocking.test_correct_os_version Skipped: os_version was not defined
2015-02-11T17:17:25.173 INFO:teuthology.task.tests:test_locking:TestLocking.test_correct_machine_type Passed
2015-02-11T17:17:25.176 INFO:teuthology.orchestra.run.magna064:Running (working as expected, nothing to see here): "python -c 'assert False'"
2015-02-11T17:17:25.205 INFO:teuthology.orchestra.run.magna064.stderr:Traceback (most recent call last):
2015-02-11T17:17:25.205 …
```
> Make pytest capture stdout when running the tests task

- teuthology/task/hadoop.py
Signed-off-by: Greg Farnum <gfarnum@redhat.com>
Sorry Zack! :(
> hadoop: remove parallel from import; fixes linter warning

- teuthology/lock.py
- teuthology/provision.py
- teuthology/task/internal.py
Previously we'd see things like this:
```
07:44:30 vpm011 locked by job 749579
07:44:32 downburst created vpm011 for job 749579
07:46:01 downburst destroyed vpm011 for job 749584
07:46:02 vpm011 unlocked by job 749584
07:46:03 vpm011 locked by job 749554
07:46:05 downburst created vpm011 for job 749554
07:46:16 job 749579 lost connection to vpm011
07:46:16 downburst destroyed vpm011 for job 749579
07:46:17 vpm011 unlocked by job 749579
```
It was because:
1. Before destroying a VM, teuthology didn't check to see if it had the same ``description`` on the lock server, or even if it had the same ``locked_by`` value
2. teuthology didn't pass the ``description`` the the lock server when unlocking
3. Paddles didn't even care about ``description``s when unlocking single nodes
3 is fixed by …
> Safer vps unlocking

- teuthology/task/tests/__init__.py
When you schedule a job it's in a background process with no terminal. When we invoked pytest it would die trying to report the status to the nonexistent terminal.  So, just unregister the TerminalReporter so it doesn't complain.
Also made it so if pytest dies the job reports as 'dead'.
> Fixes the issue of pytest failing with scheduled jobs

- teuthology/orchestra/remote.py
If dest_dir != '/tmp', attempt to use the original filename.
> Allow Remote.get_file() to use original filename

- teuthology/nuke.py
Sometimes packages or dpkg gets in a weird state where a nuke will
fail to run and simply running an apt-get -f install on the
machine will fix things up so it can be nuked again. Currently
we only ran that being dependent on dpkg --configure completing
where as I changed it so it will still try apt-get -f install
to potentially require less manual intervention when cleaning up
machines. I kept the original behavior but adding some arguments
to insure it will not prompt you for a yes/no (like apt-get -f
install usually would do).
Signed-off-by: Sandon Van Ness <sandon@redhat.com>
> Bug #10803: Try apt-get -f install to workaround nuke failure.

- teuthology/task/internal.py
Per issue #5629
Since we need the binaries (regular stripped + non-stripped with
debug symbols) to do debugging this will make it more convinient
for developers so they don't have to track down the files from
the specific build in question and instead they will just be
sitting in the archive folder with the coredump files.
Signed-off-by: Sandon Van Ness <sandon@redhat.com>
> Download ELFs (regular + debug) from remotes when coredump occurs.

- teuthology/lock.py
There was never any reason not to.
Fixes: #11167
> lock.py: allow machines list for --brief

- bootstrap
In #sepia today, Zack explained the reasoning for the python-libvirt package on the Debian family of distros.
> bootstrap: explain the system python-libvirt pkg

- teuthology/packaging.py
- teuthology/task/install.py
- teuthology/test/task/test_install.py
- teuthology/test/test_packaging.py
This adds a function to teuthology.packaging that can be reused to
fetch the installed version of a package for the given remote.
> Verify that the correct ceph version is installed on updates and install

- teuthology/task/valgrind.supp
This appears to have come from dca722ec7b2a7fc9214844ec92310074b5cb2faa,
which merged in support for use of lttng ust functions on fork. Valgrind
started warning on a Leak_StillReachable with lttng_ust_init in
the function call trace.
Hopefully this is specific enough that we don't mask out any other
lttng errors.
Signed-off-by: Greg Farnum <gfarnum@redhat.com>
> valgrind: ignore lttng warning on un-cleaned-up state

- teuthology/lock.py
- teuthology/provision.py
- teuthology/test/test_provision.py
This allows for better logging, easier debugging, and a proper way to give up attempting to start up instances that are somehow broken. I also intend for it to serve as a model to follow when adding support for e.g. Cobbler reimaging and OpenStack provisioning.
> Refactor downburst provisioning

- teuthology/orchestra/connection.py
- teuthology/orchestra/remote.py
- teuthology/run.py
- teuthology/task/internal.py
This PR also splits ``task.internal.connect()`` into two subtasks.
Both of these changes are needed to support the provisioning work I'm doing in other branches.
> Add timeouts to Remote connection functions

- teuthology/suite.py
We're hitting the github API rate limit; if master doesn't exist we lose
anyway
> Don't call get_branch_info() for master branches

- setup.py
Some non-python scripts are missing when install.
Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>
> Adding missing files in setup.py

- tox.ini
What this does is the ability to catch SyntaxErrors with flake8 when tox runs:
flake8 --select=F,E9 kernel.py
kernel.py:645:64: E901 SyntaxError: EOL while scanning string literal
Reference issue: http://tracker.ceph.com/issues/11491
> include E9 errors for flake8 runs in tox.ini

- teuthology/nuke.py
- teuthology/task/internal.py
internal.check_lock seems to only be used by nuke and it's sometimes helpful
to be able to nuke a node that is marked down.
> Don't assert status==up when using internal.check_lock.

- teuthology/config.py
- teuthology/packaging.py
- teuthology/task/kernel.py
- teuthology/test/test_packaging.py
This allows us to install kernels from koji that have been scratch built, meaning we must install from a taskID not a buildID.
For reference: http://tracker.ceph.com/issues/11552
> Install scratch built kernels from koji

- .travis.yml
- tox.ini
Travis CI's docs say that HOME is supposed to be set to `/home/travis` by default, however, it also says "do not depend on this value": http://docs.travis-ci.com/user/ci-environment/
Teuthology depends on the $HOME environment variable being set, and the test suites that depended on this recently failed to build in Travis CI.
Set the var explicitly so it's always available for the tests.
> tests: set HOME env var

- scripts/lock.py
- teuthology/lock.py
- teuthology/misc.py
- teuthology/test/test_misc.py
--json-query <file> or --json-query <string> allows filtering search
results conveniently; the JSON must be a dictionary that is a subset
of the lock record to be matched.  The reason this was invented:
Find all VPSes on a particular vmhost:
teuthology-lock --list --all --json-query \
'{"vm_host":{"name":"mira003.front.sepia.ceph.com"}}'
> lock.py: Add '--json-query' to allow complex search for --list/--brief

- teuthology/lock.py
Without this, lock.py keeps trying to get at the key in
case it might need it later...but there's nothing that even
uses that information left, so it just causes a delay.
> lock.py: remove dead code trying to deal with locks

- teuthology/task/kernel.py
Since commit 7da76fa78f63 ("Use kernel_flavor when polling
gitbuilders"), teuthology-suite appends 'flavor: basic' to kernel task
config.  This broke all scheduled kernel suites, because
normalize_config() treats unknown keys as role types and when it
doesn't find a valid one it bails and returns {}, which means "do
nothing".
Fix this temporarily by adding flavor to a list of recognized keys.
This is wrong a bunch of levels, but it fixes a regression while
sticking to the way normalize_config() currently works.
> kernel: recognize flavor key

- requirements.txt
- teuthology/__init__.py
- teuthology/task/ansible.py
- teuthology/test/task/test_ansible.py
This doesn't move us over yet, but adds all of the (teuthology-side) tweaks we need to make the real transition.
> Enablement for chef -> ansible transition

- teuthology/suite.py
Use it instead of get_branch_info() to avoid GitHub's API rate limiting.
> Add github_branch_exists()

- docs/siteconfig.rst
- teuthology/config.py
- teuthology/task/install.py
- teuthology/test/task/test_install.py
Instead of hardcoding the template used by _get_baseurl to build the URL
of the repository where packages are to be found, make it a
baseurl_template
configuration parameter in the teuthology.yaml file.
http://tracker.ceph.com/issues/11830 Fixes: #11830
> expose the install._get_baseurl template in .teuthology.yaml

- teuthology/suite.py
There are three cases: a) don't install a kernel, b) install a distro
kernel or c) install a specified version.  Appending 'flavor: basic' to
kernel task config in the former two cases is wrong.  In case a)
appending flavor is not only bogus but also leads to bug: a { 'kernel':
{ 'flavor': 'basic' } } config confuses kernel task and it installs
a default version of the kernel (branch master) on all remotes when the
user's intent was to not install any kernel.  As for case b), distro
kernels are built by distros and don't have flavors.
Fix this by appending 'flavor: basic' to kernel task config only in
case c).
> suite: append flavor key only if kernel version is specified

- teuthology/task/kernel.py
This function is only used in distro kernel codepaths. Remove a similar
block of code from need_to_install_distro() and use this function.
> get_latest_image_version_rpm(): ignore non-distro

- teuthology/suite.py
The whole kernel_flavor check in schedule_suite() is completely wrong.
ceph packages and kernel packages are built on different gitbuilders
and so a set of ceph flavors is distinct from a set a kernel flavors
(they happen to intersect because both have a 'basic' flavor but that's
it).  Querying ceph gitbuilders with kernel flavor (which is what it
currently does - has_packages_for_distro() talks to ceph gitbuilders)
is useless and only worked because the only kernel we currently care
about and use in qa is 'basic' kernel.  Remove the for i in set(...)
construct and only check install task (i.e. ceph) flavor.
Also, crucially, do not make an empty dict a kernel task config in
!kernel_hash (i.e. "do not install any kernel") case.  This makes
kernel task install a default version of the …
> suite: don't try to check ceph packages against kernel flavor

- teuthology/task/ansible.py
- teuthology/test/task/test_ansible.py
If given the config value of ``cleanup`` the ansible task will rerun the
same playbook during the teardown stage with a ``teardown`` var added
with a value of True.  This will allow the playbook to cleanup after
itself during teardown, if the playbook supports this feature.
The tests pass, but I haven't actually ran a job with this yet.
> Enable the Ansible task to optionally cleanup after itself.

- scripts/lock.py
Instead of using sys.argv implicitly, which is inconvenient for testing.
> lock.py: make main() argv as an argument

- teuthology/task/install.py
I think this used to be a wget call, so the url we were requesting to
fetch the package version would be logged by that wget call.  Since
we've changed that call to use requests and lost that logging, this adds
some of that logging back.
I'm hoping to use this to debug: http://tracker.ceph.com/issues/12115
> Better logging when looking for a package version in the install task

- teuthology/exceptions.py
- teuthology/run.py
- teuthology/task/selinux.py
- teuthology/test/task/test_selinux.py
This creates a new SELinux task that, on RPM-based systems, will do two things:
1. Set the SELinux mode before testing begins (default mode is permissive)
2. Before testing, scrape the audit log for denials
3. After testing, scrape the audit log for *new* denials - and fail the job if there are any
4. Restore the SELinux mode to the one used before testing began.
If run on a kernel which does not support SELinux, the job will fail. This is the reason for blocking.
> Let's test with SELinux

- scripts/schedule.py
Instead of using sys.argv implicitly, which is inconvenient for testing.
> schedule.py: make main() argv as an argument

- scripts/suite.py
Instead of using sys.argv implicitly, which is inconvenient for testing.
> suite.py: make main() argv as an argument

- teuthology/task/install.py
It does not matter if the {proj}.list file can't be removed because it
does not exist.
> task/install: rm {proj}.list is idempotent

- teuthology/lock.py
Depending on the backend being used (sqlite or another), paddles won't
interpret locked=false as being the same as locked=0 (see
http://tracker.ceph.com/issues/12183 for more context).
Convert True to 1 and False to 0 to always get the same behavior from
paddles, regardless of the backend.
> list_locks must use 1 / 0 for True / False

- teuthology/lock.py
Gracefully handle the case where a virtual machine has no dedicated
host. It's the case for OpenStack.
> lock.py: not all virtual machines have a dedicated host

- teuthology/test/test_worker.py
- teuthology/worker.py
When a worker runs with --verbose, it also runs the jobs with --verbose.
> a worker --verbose calls run --verbose

- teuthology/misc.py
It is the same as subprocess.check_output, only it log.debug the command
being run as well as its output.
> misc.py: sh helper to log command and output

- teuthology/task/kernel.py
When we were still using Chef, we accidentally ran it twice on downburst
VMs during scheduled jobs. Now that we're not, VMs are showing up with
stale apt caches. This will make all deb-based systems update their
cache before attempting to install a kernel.
> get_latest_image_version_deb(): run apt-get update

- README.rst
- teuthology/run.py
- teuthology/test/test_run.py
http://tracker.ceph.com/issues/12226
> Ensures that task list is a python list

- teuthology/orchestra/connection.py
Changing from `dsa` to `dss` in error message.
> Fixing small typo

- teuthology/lock.py
Testing the name of a machine to figure out if it is a virtual machine
is unreliable. Use the is_vm field of get_status instead.
> lock.py: is_vpm should test is_vm

- teuthology/lock.py
- teuthology/misc.py
- teuthology/task/internal.py
Because it may be used by provision.py
> move ssh_keyscan from lock.py to misc.py

- setup.py
setuptools doesn't install dependencies found in `tests_require`, so there's no need to have this option in `setup.py`. Since this options doesn't have an effect on the outcome of tests, we run the risk of getting out of sync to what we actually use, which is specified in `tox.ini`.
alternatively, we can set `tests_require` to what `tox.ini` has.
The former seemed more straightforward.
> Removes test_require from setup.py

- teuthology/task/ansible.py
To take advantage of the updated ssh_config shipped by the testnodes
role
> Ansible: reconnect to remotes after playbook runs

- teuthology/task/ansible.py
Otherwise it may fail if LC_ALL=C
> ansible: decode('utf-8') before logging

- teuthology/nuke.py
If nuke is called with no targets, just do nothing instead of failing
because the target element is not found in the map. This can happen if
the machine fails to be provisioned early in the process.
> nuke: gracefully handle zero targets

- teuthology/task/ansible.py
b834dd6660a77379b2c693a36487352941a8e52d added decode('utf-8') which
breaks when a substring inadevertendly cuts in the middle of a valid
utf-8 sequence. Add the 'ignore' so the offending sequence is discarded
instead of raising an error.
> ansible: decode('utf-8', 'ignore') before logging

- teuthology/misc.py
ssh_keyscan is designed to return almost immediately if there is no
connection (the timeout is 1 second). ssh_keyscan_wait will wait up to
10 minutes and report progress every 6 seconds.
> ssh_keyscan_wait: blocking version of ssh_keysscan

- teuthology/task/internal.py
http://tracker.ceph.com/issues/12462
If lock_many() fails to create any VMs, it returns an empty dict, which
was causing an exception to be raised. The existing error reporting in
lock_many() should be adequate here.
> Remove buggy error checking in lock_machines()

- teuthology/task/install.py
Removed this tool from upstream.  Don't install (or remove) it any more!
> task/install: rest-bench has been removed

- teuthology/misc.py
- teuthology/packaging.py
- teuthology/task/install.py
- teuthology/task/internal.py
- teuthology/test/task/test_install.py
- teuthology/test/test_packaging.py
teuthology.suite, teuthology.task.install and teuthology.task.internal.check_packages all use different methods to check for packages in gitbuilder.  This provides a standard interface that all places in teuthology should be able to use to interact with packages on gitbuilder.
I'm looking for feedback on the class and the approach.  I've implemented it's usage in teuthology.task.internal.check_packages and that tests out with manual teuthology runs.  I've scheduled a suite, but it hasn't completed yet.
I'm hoping we can agree on  the approach and usage in check_packages in this PR and then submit others to use this in suite and install.
I've also done a bit of refactoring and testing to install here as well.
> Introduces teuthology.packaging.GitbuilderProject

- teuthology/packaging.py
- teuthology/test/test_packaging.py
We don't care about minor version numbers anymore for gitbuilder.
> packaging: ignore minor version numbers in gitbuilder urls

- teuthology/task/install.py
- teuthology/test/task/test_install.py
We don't care about minor version in gitbuilder anymore.
> install: ignore minor version when building a gitbuilder url

- teuthology/exceptions.py
- teuthology/task/ansible.py
This works with a custom ansible callback plugin that intercepts task
failures and writes them to a log file (in yaml format) provided by the
ansible task as an environment variable. If the playbook fails, teuthology
reads that failure log and raises an AnsibleFailedError with the actual
output from the failed ansible task.
> ansible: read the ansible failure log and raise a more meaningful error

- teuthology/orchestra/daemon.py
Default to False (not silent) to preserve existing behavior.
> orchestra/daemon: add 'silent' option to signal()

- teuthology/task/ansible.py
When moving the error log between file systems of two different types os.rename will throw an error while shutil.move correctly handles that case.  See: http://tracker.ceph.com/issues/12656
I've also added some exception handling incase we fail to parse the error log.  All it does is fail silently and log the exception so that we can inspect the log after the fact. See: http://tracker.ceph.com/issues/12675
> fix ansible error reporting

- teuthology/task/ansible.py
Fixing a bug introduced with https://github.com/ceph/teuthology/pull/595.  When I opened the failure_log I gave it the name ``log`` which conflicts with ``ansible.log`` which is what I was really wanting to use with ``log.exception``.
> ansible: rename log to fail_log to not conflict with ansible.log

- teuthology/packaging.py
- teuthology/task/install.py
- teuthology/test/task/test_install.py
- teuthology/test/test_packaging.py
I've tested this on Ubuntu, Debian and Centos.  It might be smart to run an upgrade suite with this branch before merging just to be safe though.
This should fix: http://tracker.ceph.com/issues/12668
> refactor the install task to use packaging.GitbuilderProject

- teuthology/task/ansible.py
Without the permissions set correctly apache will not serve this file
> task.ansible: set the ansible_failure.yaml file mode to 0664

- teuthology/task/ansible.py
This fixes a bug where if we fail to parse the ansible log it is never
archived.
> task.ansible: archive the ansible log even if parsing fails

- teuthology/task/ansible.py
If _handle_failures fails to parse the yaml in the ansible error log, it
can still give the contents of the failure log to an AnsibleFailedError
in it's unparsed form.
I also changed the log.exception to log.error when an ParserError occurs
as I think it was confusing some having that extra traceback in the log.
> ansible: raise an AnsibleFailedError even when parsing fails

- teuthology/test/task/test_ansible.py
Speeds up that unit test greatly.
> test_execute_playbook(): patch Remote.reconnect()

- teuthology/packaging.py
This parsing is not needed on other projects and it was breaking
the kernel task by trying to verify an incorrect version was installed.
Fixes the failure here: http://pulpito.front.sepia.ceph.com/teuthology-2015-08-23_23:18:02-multimds-next-testing-basic-multi/1028553/
> packaging: only mangle the version string for the ceph project

- teuthology/task/internal.py
This is not a concern for error and should be ignored.
> internal: ceph-deploy may have ceph-create-keys INFO in syslog

- scripts/suite.py
- teuthology/suite.py
If called with --dry-run --verbose --verbose (or --dry-run -vv), call
teuthology-schedule --dry-run for each job that would be scheduled. This
causes teuthology-schedule to print out each would-be job config.
> teuthology-suite: very-verbose mode

- teuthology/packaging.py
- teuthology/test/test_packaging.py
If the sha1 is not provided in the job config, it needs to be fetched
from gitbuilder.
See: http://tracker.ceph.com/issues/12934
> GitbuilderProject: fetch sha1 from gitbuilder if not in the config

- setup.py
We need >= 1.15 to connect to newer OpenSSH, such as the version used by
debian jessie.
> use modern paramiko

- scripts/openstack.py
- scripts/suite.py
- teuthology/openstack/test/test_openstack.py
- teuthology/suite.py
- teuthology/test/suites/noop/noop.yaml
- teuthology/test/test_suite.py
http://tracker.ceph.com/issues/12977
> openstack: throttle job scheduling by default

- teuthology/openstack/openstack-teuthology.init
So that there is no leftover from the ceph-qa-suite clones.
> openstack: cleanup the src directory when stopping the cluster

- teuthology/openstack/setup-openstack.sh
So that it is easier to replace because there is no need to verify if
it's already present or not.
> openstack: explicitly set gitbuilder_host default

- setup.py
No need to pin 1.6.3 since 1.7.3 has been released and fixes the
regression.
https://bugs.launchpad.net/python-openstackclient/+bug/1496689
> os-client-config is fixed

- teuthology/suite.py
Sample output:
```
(virtualenv)13:40:20 zack@zwork.local teuthology master ? teuthology-suite -vv --owner zack@zqork --suite teuthology --limit 1 --priority 1 --filter vps --filter-out rgw --dry-run
2015-09-21 13:40:39,040.040 DEBUG:teuthology.suite:Defaults for machine_type magna distro None: arch=x86_64, release=centos7, pkg_type=rpm
2015-09-21 13:40:39,040.040 DEBUG:teuthology.suite:Gitbuilder URL: http://gitbuilder.ceph.redhat.com/ceph-rpm-centos7-x86_64-basic/ref/master/sha1
2015-09-21 13:40:39,457.457 INFO:teuthology.suite:ceph sha1: 0bfefdf5b6becba0a395c6316b126fd7f3addc8b
2015-09-21 13:40:39,457.457 DEBUG:teuthology.suite:Defaults for machine_type magna distro None: arch=x86_64, release=centos7, pkg_type=rpm
2015-09-21 13:40:39,457.457 DEBUG:teuthology.suite:Looking for packages …
```
> Fix results-email-job scheduling

- teuthology/run.py
- teuthology/task/internal.py
- teuthology/test/task/test_internal.py
- teuthology/test/test_run.py
If a buildpackages task is found, ensure it is always before the install
task because it is intended to produce the packages that will be used by
the install task.
http://tracker.ceph.com/issues/13031 Refs: #13031
> internal: move buildpackages before install task

- teuthology/openstack/__init__.py
The instance throttling (not launching more than X instances per minute)
helps the instance running the teuthology cluster when running multiple
workers. The workload does not spike when launching a suite and that
allows to run more workers on a machine with the same hardware configuration.
> openstack: throttling helps the instance running the cluster

- teuthology/misc.py
This fixes errors we get from ceph-mon when it spawns crushtool to test new
maps.
Fixes: #13251
> misc: do not trace children with valgrind

- teuthology/task/install.py
fix for version match, 1.3.1 now maps to 0.94.3 instead of the prevoius 0.94.2
> fix for version match, 1.3.1 now maps to 0.94.3

- teuthology/task/kernel.py
...instead of relying on already-created repos to have
the correct URI.
> task/kernel: set the URI properly

- teuthology/misc.py
- teuthology/test/test_misc.py
It is not enough to count the number of entries in the osds
array, wait_until_osds_up must count which one are actually up by
checking if the string "up" is in the "state" array.
http://tracker.ceph.com/issues/13363 Fixes: #13363
> misc: wait_until_osds_up must verify 'up' in state

- README.rst
- teuthology/openstack/__init__.py
Skip security groups if running against RackSpace and document the
restriction.
http://tracker.ceph.com/issues/13027 Fixes: #13027
> openstack: rackspace does not support security groups

- teuthology/openstack/test/openstack.yaml
Make it so the default when using the OpenStack backend is to build the
packages transparently using the OpenStack cluster instead of relying on
http://ceph.com/gitbuilder.cgi.
> openstack: do not rely on gitbuilder.ceph.com by default

- teuthology/run_tasks.py
I don't know when or why it changed, but the existing URL format, which
uses '/search?q=<id>', fails; what works, by observing the web UI's URL
submission and by testing, is to omit the 'search' part of the path:
'/?q=<id>'
> run_tasks.py: fix Sentry URL

- docs/siteconfig.rst
- teuthology/config.py
- teuthology/repo_utils.py
The ~/.teuthology.yaml ceph_git_base_url configuration does not allow to
modify the URL of the Ceph repository without also modifying the URL of
the teuthology repository. Although it is frequently needed to point to
an alternate ceph or ceph-qa-suite repository, it is rarely necessary to
point to an alternate teuthology repository.
This is not a blocker: it is enough to mirror the teuthology,
ceph-cm-ansible, ceph-deploy and maybe a few other repositories to
satisfy this requirement. This is however inconvenient because the
exact list of repositories that need to be mirrored is not easily
accessible. In addition, unless the user is careful about updating the
mirrors prior to running teuthology, there is a good chance that an
obsolete version of the repository will be used and this may …
> config: add ceph_git_url and ceph_qa_suite_git_url

- teuthology/task/install.py
- teuthology/test/task/test_install.py
The upgrade_common function implements a non trivial logic that defines
how overrides are applied to the install.upgrade task, as well as the
way upgrades are applied to the desired targets.
The function is split in two:
upgrade_common which remains the entry point
upgrade_remote_to_config which encapsulates the logic
This allows other parts of teuthology to obey the same logic by calling
the function instead of replicating it.
> install: split the upgrade_common function

- teuthology/openstack/openstack-teuthology.init
When running /etc/init.d/teuthology stop, all OpenStack resources are
destroyed, including the instance hosting the repository where the
buildpackages task artefacts are archived. Remove /tmp/stampsdir so that
everything gets rebuilt.
> openstack: clear the buildpackages directory on stop

- teuthology/openstack/openstack-teuthology.init
Make it so even after a reboot and run from root, the HOME is set to the
user directory where the scripts are expected to be.
> openstack: ensure HOME environment variable

- teuthology/lock.py
We're seeing intermittent network failures when running inside OVH. This should help work around the issue.
> Use safe_while to work around an OVH problem

- README.rst
- teuthology/openstack/__init__.py
- teuthology/openstack/test/test_openstack.py
- teuthology/provision.py
Exactly one OpenStack resources hint can be included in a given job, as
part of an existing facet. It is error prone because it is sometimes not
trivial to figure out how a given job is composed and if two resources
hint are included only one of them will be taken into account which can
lead to problems difficult to diagnose. Another undesirable side effect
is to artificially increase resources usage. It is easier and more
reliable (from the test maintainer point of view) to increase the
resources of all jobs when a few need more RAM or disk rather than
trying to figure where to write the hints so that they are used by these
jobs and these jobs only.
Instead of being a fixed hint for a given job, the max of all hints
found in each facet is used. For instance, rados/thrash can have a facet …
> openstack: resources hint is the max of all hints

- docs/siteconfig.rst
- teuthology/config.py
Volumes are rarely needed, having no volumes by default is sane.
> openstack: revert to zero volumes default

- teuthology/openstack/openstack-teuthology.init
- teuthology/provision.py
And delete the volumes owned by a teuthology instance on restart.
> openstack: add ownedby property to volumes

- teuthology/openstack/setup-openstack.sh
It takes more than 4 hours for some upgrade jobs to complete.
> openstack: increase timeout from 4 hours to 6 hours

- teuthology/openstack/openstack-teuthology.init
The package-repository instance is destroyed and requests to it will
timeout which takes time. Reverting to the default gitbuilder.ceph.com
is quicker and easier.
> openstack: reset the gitbuilder_host on stop

- teuthology/openstack/__init__.py
- teuthology/openstack/test/test_openstack.py
Setting the provider name depending on the OS_AUTH_URL content is
generally useful and moved to the OpenStack base class. There is a need
to cope with public OpenStack providers special cases, even if
temporarily (i.e. no volumes on OVH, no security group on RackSpace
etc.).
> openstack: implement OpenStack.set_provider

- teuthology/openstack/test/test_openstack.py
- tox.ini
The output is now logged, use caplog instead of capsys and add it as a
test dependency.
> openstack: tests: look in caplog

- teuthology/openstack/__init__.py
When the connectivity is not great, this is required.
> openstack: increase ssh timeout to 240

- teuthology/misc.py
- teuthology/test/test_misc.py
- tox.ini
Only shows the first 128 characters of the output when the command
succeeds and show all of it only when it fails.
> misc: reduce misc.sh verbosity

- setup.py
If cliff-tablib is not present, the output of openstack server show is a
dictionary, otherwise it is a list of Field/Value pairs. Since
cliff-tablib is not a required dependency of python-openstack client,
the output format of openstack server show may vary. Add cliff-tablib as
a dependency so that the output format is always the same.
https://bugs.launchpad.net/python-openstackclient/+bug/1510546
> openstack: server show must always return array

- teuthology/suite.py
Otherwise the check is always done on the default
http://github.com/ceph/xxx
> suite: use get_ceph_*_url when checking branches

- teuthology/provision.py
An attempt to reduce the instance error rate on OVH. When all workers
are on the same machine, it makes them wait for an instance creation is
complete before running another one. If not, it is possible for 200
workers to run 200 server creation simultaneously. While this should be
throttled by OVH, these bursts may be the cause for occasional instance
creation errors: few tenants are likely to have such a pattern.
> openstack: global server creation lock

- teuthology/provision.py
When removing a server and the volumes attached to it, the following can
happen:
* the server goes in ERROR status instead of being deleted
* if removed before the server is deleted, the volume may fail detach
and consequently the deletion can fail with "still attached, detach
volume first"
* some volumes go in ERROR status instead of being deleted
This will cause problem when and if an instance is assigned the same IP
as an instance in ERROR state. They will both have the same name and
confuse teuthology.
Instead of assuming deletion is a reliable operation, assume it is a
best effort:
* rename the server and volumes to REMOVE-ME
* delete the server and then the volumes: ignore failures
The names instances and volumes in error state no longer conflict with
the name of running instances …
> openstack: more robust server deletion

- teuthology/test/test_misc.py
It needs to be specifically told to use /bin/echo. Also add some
newlines to make the linter happy.
> Fix misc.sh() tests on MacOS

- teuthology/openstack/setup-openstack.sh
By default teuthology-openstack builds packages dynamically and does not
rely on gitbuilder.ceph.com
> openstack: disable teuthology-suite sha1 verification

- teuthology/openstack/test/resources_hint.yaml
- teuthology/openstack/test/resources_hint_no_cinder.yaml
The memory cannot be lowered by the hint: test that it increases to 10GB
instead of testing that it was lowered under a given limit.
> openstack: tests: use new resources hint style

- teuthology/openstack/__init__.py
The user-data files are in the sources, in the teuthology/openstack
directory. By default the template path being used is
teuthology/openstack/openstack-{os_type}-{os_version}-user-data.txt and
assumes teuthology-suite / teuthology-openstack is run from the root of
the source directory.
If the user-data path is relative, make it absolute based on the
directory in which the openstack module is found.
http://tracker.ceph.com/issues/13416 Fixes: #13416
> openstack: get user-data path relative to the sources

- teuthology/suite.py
- teuthology/test/test_suite.py
To be able to re-run a job we need:
* the ceph repository and hash
* the ceph-qa-suite repository and hash
* the job description
When reading the job log from the archive directory, we currently only
have the ceph-qa-suite branch name. If and when the branch name moves
on, the job description may cease to be valid and re-running the job
may no longer be possible.
> suite: add the ceph-qa-suite hash to the job config

- teuthology/run.py
The unwinding order is in reverse: internal.archive must be after
archive_upload so that it actually happens *before*.
> run: upload must happen after archive

- scripts/results.py
- teuthology/results.py
- teuthology/test/test_results.py
We used to claim that every job that didn't pass or fail had 'hung'. That was a holdover from the pre-paddles era.
Now we can report 'dead', 'running', 'waiting', and 'queued'.
``teuthology-results`` will now require a running paddles instance, but then again, so does scheduling jobs in the first place.
> teuthology-results: Be aware of all job statuses

- setup.py
This is to fix 'openstack image list --json' acting as if --debug were
passed. This was breaking things.
https://bugs.launchpad.net/os-client-config/+bug/1513919
> Pin os-client-config to 1.9.0

- teuthology/worker.py
They will fail immediately, but at least we'll know about them.
> Run jobs even if 'roles' is empty

- setup.py
The bug found in 1.10.1 was fixed and version 1.10.2 is now current.
https://bugs.launchpad.net/os-client-config/+bug/1513919
> Unpin os-client-config

- teuthology/openstack/__init__.py
No cloud provider boots an instance within 30 seconds, no need to poll
aggressively. Also wait more than a total of 1200 seconds (3000 seconds)
because some providers may take more than 20 minutes to complete the
boot sequence.
> openstack: poll every 30 seconds instead of 2

- teuthology/repo_utils.py
http://tracker.ceph.com/issues/13728
> Be more tolerant of GitErrors in repo_utils

- scripts/test/script.py
- teuthology/run.py
- teuthology/suite.py
- teuthology/test/test_run.py
The worker runs the job, even if there are no roles: it is legitimate to
run a job that does not need machines.
Run only locks machines if there are roles and init_tasks is only
populated with tasks that make sense depending on the presence of roles
or not.
Move the internal task added in suite.py to run.py : there is no reason
to not have them with teuthology-run or teuthology-schedule (ansible +
clock).
> run: do not lock machines if there are no roles

- bootstrap
- teuthology/openstack/__init__.py
For providers such as dreamcompute that only support the glance image
format raw, convert the qcow2 image to raw prior to uploading.
> openstack: support glance disk-format raw

- teuthology/openstack/__init__.py
When the connectivity is not great, this is required.
> openstack: increase ssh timeout to 240 (part 2)

- scripts/openstack.py
Most jobs in rados/thrash allocate six volumes. The default tenant on
OVH has ten volumes, that's just not enough for two jobs to run in parallel.
> openstack: run one job at a time by default

- teuthology/task/install.py
Remove epel packages during downstream testing if present on the node and install these packages using the downstream repo
Dependent on https://github.com/ceph/ceph-cm-ansible/pull/167
> Remove epel packages during downstream testing if present on the node

- bootstrap
When a package is found not to exist, we need to also check if there
is another package installed that provides a capability of the same
name.
Also, the python-devel package must be installed, or the pip phase
fails.
http://tracker.ceph.com/issues/14002 Fixes: #14002
> bootstrap: fixes for openSUSE

- teuthology/openstack/setup-openstack.sh
We will point to apt-mirror.sepia.ceph.com, which is
publicly-accessible.
> Stop hardcoding apt-mirror's IP

- teuthology/orchestra/remote.py
- teuthology/orchestra/test/test_remote.py
The opsys.OS class passes the operating system's version according to
the actual host; in some cases e.g. CentOS is reporting things like
'7.1.1503'. In these cases, let's make
Remote.inventory_info['os_version'] only use the '7.1' - since we don't
care about the rest. This will allow us to continue scheduling against
CentOS smoothly.
> Remote: only submit X.Y for os_version

- teuthology/misc.py
Truncating by default to 128 frequently trims useful debug
information. Set the default to 1024: the intent is to avoid huge logs
when a json output is repeatedly returning large (>10k) payloads.
> misc: truncating shell output to 1024 per line

- teuthology/openstack/__init__.py
All OpenStack hints have been converted to arrays (hammer, infernalis,
master), raise an error if a hint is added old style to avoid mixing
style.
http://tracker.ceph.com/issues/13581 Fixes: #13581
> openstack: enforce hints as an array

- teuthology/openstack/openstack-teuthology.cron
- teuthology/openstack/setup-openstack.sh
Resources are billed by the hour, it makes a difference to cleanup
leftovers once every hour. Provide a crontab that runs
teuthology-nuke --stale-openstack
every 30 minutes.
> openstack: cleanup leftovers every 30 minutes

- teuthology/openstack/__init__.py
Using the server list to verify if the connection to the OpenStack
cluster works may generate too much output if there are many
instances. Use the last two lines of flavor list instead.
> openstack: use flavor list to verify connectivity

- teuthology/orchestra/connection.py
Instead of log.info because it is noisy.
> orchestra: display connect_args on debug

- teuthology/task/ansible.py
When parsing of the ansible failure log fails this will actually print
the contents of the malformed log in the raised AnsibleFailedError.
> ansible: include the contents of the failure log in the exception

- setup.py
Because of https://bugs.launchpad.net/nova/+bug/1526413
> Block requests==2.9.0

- teuthology/openstack/test/openstack-integration.py
It will wipe out all targets in the tenant which can be devastating and
unexpected when multiple teuthology clusters use the same tenant. Filter
the deletion using the ownedby property to limit the destruction to the
targets owned by the cluster in which the integration tests are run.
> tests: openstack-integration is too agressive

- teuthology/openstack/__init__.py
Instead of duplicating a bugous static IP regexp, use the get_ip()
method.
> openstack: remove bugous static IP regexp

- teuthology/openstack/__init__.py
Ensure a newly created image is private to this tenant by default,
regardless of whatever the openstack defaults are.
Signed-off-by: Robin H. Johnson <robin.johnson@dreamhost.com>
> openstack: keep image private

- teuthology/suite.py
When running dry-run, an attempt is made to figure out if the hash of
the job is already present in the gitbuilder. This must not be done
if suite_verify_ceph_hash is false.
> suite: honor suite_verify_ceph_hash on --dry-run

- setup.py
- teuthology/openstack/__init__.py
- teuthology/openstack/openstack-centos-7.1-user-data.txt
It uses the same cloud image as centos-7.0 because it already was 7.1
anyway, only misnamed 7.0 because changing it is inconvenient.
> openstack: support CentOS 7.1

- teuthology/nuke.py
- teuthology/test/test_nuke.py
Otherwise it will fail if there are multiple instances by the same name.
http://tracker.ceph.com/issues/14238 Fixes: #14238
> openstack: nuke must use ID and not name

- teuthology/packaging.py
- teuthology/task/install.py
- teuthology/test/test_packaging.py
This fixes: http://tracker.ceph.com/issues/14125
When trying to fetch a package version, GitbuilderProject will now wait and retry for 2 1/2 minutes if the status_code returned is not a 200 and the config option ``wait_for_package: true`` is set for either the install task or install.upgrade.
The 2 1/2 minute wait time is fairly arbitrary, I'm open to better suggestions there. We could also make it a teuthology config option (in teuthology.yaml) if we wanted to get fancy.
> packaging.GitbuilderProject: support the wait_for_package feature

- teuthology/provision.py
The global lock used to run openstack server create must timeout
otherwise it may hang forever. The timeout is set to 8h. Assuming one
server create --wait takes ~1mn to return, that should be more than
enough to absorbe a burst of 200 jobs provisioning instances at the same
time.
The goal here is to ensure the queue does not stay blocked forever, not
to timeout jobs because they cannot get a server in a given delay.
http://tracker.ceph.com/issues/14243 Fixes: #14243
> openstack: flock timeout on openstack server create

- README.rst
The install task contains its own list of sub-point bullets.  Prior to this change, rST did not treat this list as a sub-list of the "install task" bullet point. Instead, it rendered them at the same level as the install task and all the other tasks.
Indent the sub-bullets under the install task's description. This will cause rST to treat them as true sub-bullets under the install task.
> README: fix rst syntax for sub-bullets

- teuthology/provision.py
Bug report: http://tracker.ceph.com/issues/14336
Regression caused in: https://github.com/ceph/teuthology/pull/764
> Fix regression in flock usage

- teuthology/task/tests/test_locking.py
... instead of remote.os.version.
> Use remote.inventory_info['os_version']

- teuthology/task/valgrind.supp
Fixes: #14163
Signed-off-by: Jason Dillaman <dillaman@redhat.com>
> valgrind.supp: suppress helgrind warnings for external libraries

- hammer.sh
This script was added by 303e863d32c077c17cd8a027172af8204434a66b - this
commit takes the description from that commit and places it in a comment at
the top of the script.
Without this descriptive comment, the only thing we have to go on is the
filename, hammer.sh, which is easily confused with Hammer as in version
0.94 of Ceph.
> doc: add descriptive comment at top of hammer.sh script

- setup.py
- teuthology/openstack/__init__.py
- teuthology/openstack/test/test_openstack.py
The python-openstackclient output may either be a list of Value/Field or
a dictionary. Use the dictionary instead of the Value/Field form
because it is easier to deal with. The former was chosen because of a
bug that made it impossible to control the output. The bug still exists
but is believed to be rare enough to ignore. Should it happen, a message
recommending a corrective action and a comment on:
https://bugs.launchpad.net/python-openstackclient/+bug/1510546
is displayed.
> openstack: switch the default json output to dictionary

- teuthology/nuke.py
- teuthology/test/test_nuke.py
> nuke: Expect json output from openstack commands

- teuthology/openstack/__init__.py
It will be cleaned up by nuke --stale-openstack
> openstack: a failure to rename a volume is not fatal

- scripts/suite.py
- teuthology/suite.py
- teuthology/test/test_suite.py
After all jobs in the suite are scheduled, wait for it to complete by
checking the result server every five minutes. The polling delay is
large but almost all suites take significantly longer than five minutes.
The list of remaining jobs is displayed every five minutes in verbose
mode.
The suite is considered stale if the list of unfinished jobs does not
change within config.max_job_time seconds (plus 30 minutes to avoid
border cases). It can happen when a worker dies, the machine running the
worker reboots etc.
http://tracker.ceph.com/issues/13884 Fixes: 13884
> suite: --wait to block until the suite finishes

- teuthology/misc.py
If a block device is read-only, or is a cloud-init datasource, we should
not change the content on it!
This change detects most documented datasources as of 2015/12/10 from
http://cloudinit.readthedocs.org/en/latest/topics/datasources.html
It cannot detect datasources that are only detectable based on files on
volume (eg config-drive v1)
Signed-off-by: Robin H. Johnson <robin.johnson@dreamhost.com>
> misc: ignore some unusable block devices

- teuthology/ceph.conf.template
Teuthology puts everything under one host, and many tests run on one host.
> ceph.conf: mon osd reporter subtree level = osd

- docs/LAB_SETUP.rst
In fact, results server and lock server are function of the paddles, written pulpito is misleading, although pulpito and paddles always installed on one machine.
> amendment misunderstood lock server and results server address

- scripts/openstack.py
- teuthology/openstack/__init__.py
- teuthology/openstack/setup-openstack.sh
The teuthology-openstack cli has two arguments to override the
git_ceph_url and git_ceph_qa_suite_url configuration values in the
~/.teuthology.yaml file of the teuthology cluster.
> openstack: update ~/.teuthology with --git-ceph{,qa-suite}-url

- teuthology/exceptions.py
- teuthology/provision.py
- teuthology/task/internal.py
Also, add a specific exception for quota-exceeded errors. This will help us identify general OpenStack breakage sooner and more easily.
This is http://tracker.ceph.com/issues/14515
> Map locking failures to 'dead' status

- teuthology/run_tasks.py
We were trying to tell the timer to write to a nonexistent file
> Fix bug when running archiveless jobs

- teuthology/suite.py
When determining the ceph hash, we usually ask gitbuilder. When that
fails, the error is misleading but it would take a bit of refactoring to
truly fix it. Let's at least put a useful warning before the confusing error
message.
> Add a warning when gitbuilder 404s

- scripts/openstack.py
- scripts/suite.py
- teuthology/openstack/__init__.py
Make it so the exit code of the command reflects the success or failure
of the suite. This is useful when running with --wait.
> suite/openstack: implement the exit code

- docs/siteconfig.rst
- scripts/openstack.py
- scripts/suite.py
- teuthology/config.py
- teuthology/openstack/__init__.py
- teuthology/openstack/test/test_openstack.py
- teuthology/suite.py
When uploading job results with --upload, it may be non-trivial to
figure out the public facing URL where the job will be visible. When
used via teuthology-openstack, it defaults to
http://teuthology-logs.public.ceph.com
so that using --wait --upload --teardown displays the URLs of the
uploaded job results that are accessible even after the cluster is
gone.
> suite/openstack: add --archive-upload-url

- teuthology/openstack/setup-openstack.sh
Because a few job take more than 6h. Ideally this could be overriden on
a case by case basis.
> openstack: default to 9h job timeout

- teuthology/openstack/__init__.py
- teuthology/openstack/openstack-teuthology.init
Obsolete resources will be taken care of by the teuthology-nuke
--stale-openstack cron job. We just want to avoid running into obsolete
targets.
The ceph-* targets which are created by the buildpackages task must also
be disposed of.
The timestamps dir is wiped out, except for packages-repository, if
it exists.
> openstack: only destroy target/ceph- VMs on restart

- setup.py
Explicitly require python-neutronclient.
> openstack: openstacklient >= 2.1.0 does not depend on neutronclient

- tox.ini
> openstack: do not use sitepackages for openstack-integration tests

- teuthology/openstack/setup-openstack.sh
It is now required by teuthology.
http://tracker.ceph.com/issues/14914 Fixes: #14914
> openstack: create default ~/.vault_pass.txt

- setup.py
> pin gevent 1.0.2

- teuthology/test/fake_fs.py
When the documentation of make_fake_fstools() was written, the function evidently only returned two values. Now it returns four values. Additional return values might be added later.
> doc: update documentation of make_fake_fstools()

- setup.py
- teuthology/__init__.py
Recently, gevent updated to 1.1.0, breaking a few things like misc.sh().
PR #810 pinned gevent to 1.0.2, but I wanted to properly investigate the
issue to not be stuck on an old version. Some git bisects later, I
discovered that gevent began patching the subprocess module by default
in:
https://github.com/gevent/gevent/commit/fc73e9afa34d811ede5d62531025d2e3876b8c01
Unpinning gevent and also telling it not to patch subprocess fixes the
issue.
> Unpin gevent and avoid patching subprocess

- teuthology/task/selinux.py
http://tracker.ceph.com/issues/14244
Fixes 14244 and adds whitelist option to ignore known future denials using overrides
> Add whitelist option and fix for cephtest denials

- teuthology/lock.py
This fixes this bug:
```
(virtualenv)zack@teuthology:~/teuthology$ teuthology-lock --lock vpm169 --os-type ubuntu --os-version 14.04
File "/home/zack/teuthology/virtualenv/bin/teuthology-lock", line 9, in <module>
load_entry_point('teuthology', 'console_scripts', 'teuthology-lock')()
File "/home/zack/teuthology/scripts/lock.py", line 17, in main
sys.exit(teuthology.lock.main(parse_args(sys.argv[1:])))
File "/home/zack/teuthology/teuthology/lock.py", line 316, in main
provision.create_if_vm(ctx, machine)
File "/home/zack/teuthology/teuthology/provision.py", line 391, in create_if_vm
return dbrst.create()
File "/home/zack/teuthology/teuthology/provision.py", line 76, in create
self.build_config()
File "/home/zack/teuthology/teuthology/provision.py", line …
```
> lock: Pass canonicalized hostname to create_if_vm

- teuthology/task/valgrind.supp
Signed-off-by: Greg Farnum <gfarnum@redhat.com>
> valgrind: ignore boost thread-local warning

- teuthology/task/valgrind.supp
http://tracker.ceph.com/issues/14799 Fixes: #14799
> valgrind: add suppression for tcmalloc in libboost_thread-mt.so.1.53.0

- docs/siteconfig.rst
A couple lines below this it says "count: 0", so replace "three" with
"zero".
> docs/siteconfig.rst: adapt comments to reality

- scripts/openstack.py
- teuthology/openstack/__init__.py
- teuthology/openstack/test/test_openstack.py
When running from a wip teuthology branch, it is inconvenient to tweak
~/.teuthology.yaml. Add --teuthology-git-url and --teuthology-branch to
take precendence and override the defaults.
> openstack: allow override of openstack:clone:

- scripts/kill.py
There isn't currently a remote kill-a-process feature.
> Mention that -kill must be run on the master node

- teuthology/openstack/openstack-debian-7.0-user-data.txt
The file this symlink was pointing to no longer exists.
> openstack-debian-7.0-user-data.txt: fix symlink

- teuthology/parallel.py
Per the class docstring, one gevent (or the with body) throwing an
exception should not stop the other events.  Instead, wait for them to
finish and then reraise the first exception we find.
A concrete problem caused by this is that with multiple parallel
installs, one failure can cause packaging operations on the other nodes
to be unceremoniously killed and left in an inconsistent state.
Signed-off-by: Samuel Just <sjust@redhat.com>
> parallel: parallel.__exit__ should always wait for greenlets to finish

- scripts/lock.py
- teuthology/lock.py
So that it is possible to lock a target of a given arch. The lock_many
function already has the argument, it only needs to be added to the list
of available options.
> lock: add the --arch option

- teuthology/orchestra/monkey.py
Disable re-keying entirely: it does not work at all and alway times
out. Here is the reproducer:
ceph-workbench ceph-qa-suite --verbose --suite upgrade/infernalis-x --suite-branch jewel --ceph jewel --ceph-git-url https://github.com/ceph/ceph --filter 'upgrade:infernalis-x/stress-split/{0-cluster/start.yaml 1-infernalis-install/infernalis.yaml 2-partial-upgrade/firsthalf.yaml 3-thrash/default.yaml 4-mon/mona.yaml 5-workload/{rbd-cls.yaml rbd-import-export.yaml readwrite.yaml snaps-few-objects.yaml} 6-next-mon/monb.yaml 7-workload/{radosbench.yaml rbd_api.yaml} 8-next-mon/monc.yaml 9-workload/{rbd-python.yaml rgw-swift.yaml snaps-many-objects.yaml} distros/centos_7.2.yaml}'
Which always fails after ~4h with the following:
2016-03-17T23:44:32.607 INFO:tasks.thrashosds.thrasher:Traceback …
> orchestra: disable re-keying to fix Key-exchange timed out

- teuthology/task/ansible.py
To avoid ansible bailing with an OSError. Normally we don't even need
the vault password for cephlab.yml.
> ansible.CephLab: touch ~/.vault_pass.txt

- teuthology/task/selinux.py
> task.selinux: add PCP's pmlogger to the whitelist

- teuthology/task/selinux.py
SELinux denials found on ubuntu@smithi027.front.sepia.ceph.com: ['type=AVC msg=audit(1462234212.274:85266): avc: denied { read } for pid=1984 comm="pmcd" name="pmlogger_daily.pid" dev="tmpfs" ino=1474542 scontext=system_u:system_r:pcp_pmcd_t:s0 tcontext=system_u:object_r:cron_var_run_t:s0 tclass=file']
> task/selinux: another pcp whitelist

- teuthology/ceph.conf.template
- teuthology/misc.py
- teuthology/orchestra/daemon.py
- teuthology/task/common_fs_utils.py
- teuthology/test/test_misc.py
Tested against master, hammer and infernalis ceph-qa-suites, running a couple kinds of upgrade tests, plus subsets of the fs, rados, rbd, and rgw suites. The impetus for this is being able to test rbd mirroring, which uses multiple ceph clusters. There's a companion PR for ceph-qa-suite: https://github.com/ceph/ceph-qa-suite/pull/937
The general idea is that roles can have a prefix of the ceph cluster name. Since roles are only interpreted by some tasks (mainly the ceph task), this localizes the required changes somewhat, and makes it simple to stay compatible with existing single-cluster suites.
> support multiple ceph clusters

- teuthology/task/hadoop.py
This is the only non-ceph task that uses custom roles, and it happens
to put a '.' as a delimiter between hadoop and the rest of the
role. Since the multi-cluster branch, is_type() is ceph-specific and
interprets this as a cluster named hadoop.
To avoid needing to change several branches in ceph-qa-suite, just use
a local is_hadoop_type() function instead of relying on the now
ceph-specific misc.is_type().
Fixes: http://tracker.ceph.com/issues/15862
> task/hadoop: fix for multi cluster is_type() change

- teuthology/packaging.py
Add an explicit "elif" block for opensuse - without this, it falls through into
the else clause and dies because it cannot determine a codename.
> packaging.py: make _get_distro() support openSUSE

- teuthology/contextutil.py
- teuthology/exceptions.py
- teuthology/test/test_worker.py
- teuthology/worker.py
The problem only shows up when all retries are exhausted.
Most of this PR is refactoring to enable unit testing.
http://tracker.ceph.com/issues/13925
> Prevent workers from becoming zombies when repo operations fail

- teuthology/task/pcp.py
If ctx.archive was set, but to None, we were failing.
> pcp: Use a smarter check for archive presence

- teuthology/nuke.py
This caused a syntax error in one of the teuthology runs:
2016-06-10T02:30:39.291 INFO:teuthology.nuke:clearing kernel mount from all nodes
2016-06-10T02:30:39.292 INFO:teuthology.orchestra.run:Running command with timeout 60
2016-06-10T02:30:39.292 INFO:teuthology.orchestra.run.mira069:Running: "grep ceph /etc/mtab | grep -o 'on /.* type' | grep -o '/.* ' | xargs -r sudo umount -f ; fi"
2016-06-10T02:30:39.363 INFO:teuthology.orchestra.run.mira069.stderr:bash: -c: line 0: syntax error near unexpected token `fi'
2016-06-10T02:30:39.364 INFO:teuthology.orchestra.run.mira069.stderr:bash: -c: line 0: `grep ceph /etc/mtab | grep -o 'on /.* type' | grep -o '/.* ' | xargs -r sudo umount -f ; fi'
Signed-off-by: Patrick Donnelly <batrick@batbytes.com>
> nuke.py: remove trailing fi token

- teuthology/suite/util.py
http://tracker.ceph.com/issues/16328
Fixes: 16328
> get_gitbuilder_hash: use default distro if needed

- teuthology/provision.py
We recently made a change to cause downburst VMs to install python on Ubuntu systems via cloud-init. This caused a race condition since teuthology started job execution while the package was still installing. This causes downburst to block until cloud-init is finished.
> Pass --wait to downburst

- teuthology/suite/placeholder.py
Default ceph-deploy override template defines devcommit which makes
'branch' overrides in the qa-suite useless since it only picksup one option
Remove the devcommit overrides from the template and use that as
default in case no other 'branch' override exist.
> Fix ceph-deploy 'branch' override

- docs/siteconfig.rst
- scripts/suite.py
- teuthology/config.py
- teuthology/packaging.py
- teuthology/suite/__init__.py
- teuthology/suite/run.py
- teuthology/suite/test/test_util.py
- teuthology/suite/util.py
This adds a simple webserver (Flask, currently manually deployed on git.ceph.com) to allow querying git history from teuthology-suite in order to implement "--newest", a facility to search for the latest-built version of a branch and schedule it if the branch tip hasn't yet been built.  There's also a --newest-limit parameter to limit the amount of backtracking allowed (10 by default).  The number of commits backtracked is logged.
This uses GitbuilderProject to check for 'builds done' on the gitbuilders in the same way suite has been doing, but adds a loop to retry if newest is set, which uses util.find_git_parent() to find the sha1 of the parent of the requested branch/sha1 and retry.  There's some refactoring of suite.run to make this happen.
There could probably be more tests.
> Add teuthology-suite --newest

- teuthology/suite/test/test_util.py
- teuthology/suite/util.py
In my defense, "committish" isn't a word, and I'm not the only one:  https://git.kaarsemaker.net/git/commit/a8a5406ab32fccabf8ed08001d50b5373e18ff1a/
> teuthology-suite: Spelling error in web API + minor test improvement

- teuthology/suite/run.py
> suite/run.py: fix order of args to schedule_fail()

- teuthology/suite/run.py
backtracking simply wasn't using the new sha1.  Refactor base_config building and rebuild when backtracking.  Duh.
Also, remove a spurious failure log message in the non-newest case.
> suite: --newest fixes: failure to rebuild base_config on sha1 backtrack, spurious log msg

- scripts/suite.py
Even if --newest isn't supplied, docopts will create it and
set it to the default.  Change the default to 0.
> suite.py: defaulting newest to 10 means it's always enabled

- teuthology/suite/run.py
Changing the default of newest to '0' meant that the combined
loop which handles both backtrack and non-backtrack conditions
was never executing, leading to undefined variables.
> suite.py: must pass at least once through the backtrack loop

- teuthology/task/install.py
This avoids having to dance around with wget and rm -f.
Fixes: 10481
http://tracker.ceph.com/issues/10481
> Install -release RPMs directly

- teuthology/suite/__init__.py
- teuthology/suite/run.py
two major fixes for --newest:
1) rewrite the /tmp yaml file that holds base_config when base_config is finally done (backtracking rewrites this info)
2) make sure that the copy of the job configuration doesn't share refs with the base_config dict so that it doesn't corrupt base_config while backtracking
The other two commits are cleanup in arg processing.
> Complete --newest feature, add some cleanups

- teuthology/task/ansible.py
This was messing up all logs with ANSI
codes.
> task/ansible: disable color output

- teuthology/orchestra/daemon.py
resolve_role_list did not handle cases where roles specified contained wild-cards or
were not specified.  ceph.role.a would end up being resolved as ceph.rolea.
Fixes: tracker issue 16053
> Fix resolve_role_list in daemon.py

- teuthology/suite/run.py
- teuthology/suite/test/test_run_.py
Change in 61350db caused email arg to be lost.  Fix, add test
> Resume paying attention to --email

- teuthology/task/packages.yaml
The way we currently build the cephfs java
bindings depends on the unversioned .so file
which is in the -dev package, not the
main one.
Fixes: http://tracker.ceph.com/issues/16640
> task/packages: install libcephfs1-dev

- teuthology/suite/run.py
Emails weren't getting sent when builds were broken
> Fix regression in schedule failure emails

- scripts/queue.py
- teuthology/beanstalk.py
Prints queue status, e.g.:
$ teuthology-queue -m smithi --status
{'paused': False, 'count': 2900, 'name': 'smithi'}
> teuthology-queue: add --status

- teuthology/task/packages.yaml
Upgrade tests on https://github.com/ceph/ceph/9744 (which drops the ceph-devel
package after a long period of deprecation) are currently failing
because teuthology tries to install ceph-devel, even though it is not needed
for any tests.
See also https://github.com/ceph/ceph-qa-suite/pull/1068
> packages.yaml: drop ceph-devel from rpm section

- teuthology/task/valgrind.supp
...so that it will match mangled names.
Fixes: http://tracker.ceph.com/issues/14794
> valgrind: wildcard boost supression

- teuthology/lock.py
When downburst is unavailable, teuthology-lock reverts to default_table and
fails because the only supported CentOS version, 7.2., is missing.
> teuthology-lock: add centos 7.2 to downburst default table

- teuthology/worker.py
I'm seeing this:
```
2016-08-09T18:24:42.415 DEBUG:teuthology.worker:Worker log: /home/teuthworker/archive/worker_logs/worker.vps.32001
2016-08-09T18:46:43.251 INFO:teuthology.worker:Success!
2016-08-09T18:46:43.252 CRITICAL:teuthology.worker:Uncaught exception
File "/home/teuthworker/src/teuthology_master/virtualenv/bin/teuthology-worker", line 9, in <module>
load_entry_point('teuthology', 'console_scripts', 'teuthology-worker')()
File "/home/teuthworker/src/teuthology_master/scripts/worker.py", line 7, in main
teuthology.worker.main(parse_args())
File "/home/teuthworker/src/teuthology_master/teuthology/worker.py", line 136, in main
job.delete()
File "/home/teuthworker/src/teuthology_master/virtualenv/local/lib/python2.7/site-packages/beanstalkc.py", …
```
> worker: Don't die on a beanstalkc SocketError

- teuthology/misc.py
- teuthology/test/test_misc.py
Reverts ceph/teuthology#925
This PR appears to be causing a deadlock in ``teuthology-nuke --stale-openstack``. I think we should probably merge #927 instead of this one.
> Revert "misc.sh(): Don't capture stderr by default"

- teuthology/nuke.py
- teuthology/openstack/__init__.py
- teuthology/openstack/test/openstack-integration.py
- teuthology/openstack/test/test_openstack.py
- teuthology/provision/openstack.py
Because they are concatenated with the STDOUT by the sh function despite
being output on STDERR and that breaks json parsing.
Fixes: http://tracker.ceph.com/issues/16972
> openstack: do not display openstack client warnings

- setup.py
... that caused `openstack ip floating list -f json` to fail and return
"Connection failure that may be retried."
>  Work around regression in openstacksdk 0.9.2

- teuthology/task/valgrind.supp
Fixes: http://tracker.ceph.com/issues/17035
> valgrind: add suppression for libunwind in libtcmalloc.so.4.2.6

- teuthology/task/packages.yaml
This reverts commit 4543fb64cedffc97c816feff7d4a69cd0456ab15.
Fixes: http://tracker.ceph.com/issues/17075
> Revert "packages.yaml: reflect python-ceph package split"

- teuthology/task/kernel.py
Commit a01f1e169074 ("kernel: use packaging.GitbuilderProject to talk
with gitbuilder.") switched the kernel task to GitbuilderProject, which
parses the config in an attempt to pick the "best" config value for
a given remote.  However, the kernel task does its own parsing and
supports more than GitbuilderProject currently handles, e.g.:
kernel:
client:
branch: testing
The above got broken by passing the entire 'kernel:' stanza to
GitbuilderProject: _get_uri_reference() chokes on "client" and defaults
to master branch.  It also effectively disables 'overrides:' support,
used by krbd:unmap suite.  Bring these back by passing in only the role
config in task().
In download_kernel(), we already have the sha1 and just need to get the
url, so construct a {'sha1': <sha>} dict on the fly. …
> kernel: don't use GitbuilderProject's _get_config_value_for_remote()

- teuthology/provision/downburst.py
http://pulpito.ceph.com/teuthology-2016-08-26_22:40:40-smoke-master-testing-basic-vps/
> Install required packages when downbursting VMs

- teuthology/orchestra/run.py
- teuthology/orchestra/test/integration/test_integration.py
http://tracker.ceph.com/issues/17102
#914 caused a regression in logging remote command output whereby each line wasn't logged immediately as it was received. This PR reverts the regression and adds an integration test so that we can avoid making the same mistake in the future.
Note that integrations tests aren't (and can't currently be) run by Jenkins-initiated testing as they need a live machine to SSH to.
> Fix logging regression

- teuthology/orchestra/run.py
Previously you could get AttributeError if
a node went away, because it tried to call
getpeername after get_transport() had
returned None.
> orchestra.run: fix generating ConnectionLostError

- teuthology/suite/run.py
- teuthology/suite/test/test_run_.py
This fixes the regression pointed out in http://tracker.ceph.com/issues/17211
> suite.Run: include suite_sha1 in job config

- teuthology/run.py
- teuthology/task/internal.py
This is to allow for teuthology to run self-tests that don't use
resources.
> Set ctx.cluster even when a job has no roles

- teuthology/run.py
- teuthology/task/internal.py
This reverts commit ffd14be3bd79baec5d9cafd8972d592085e0e099.
the add_remotes() change broke teuthology-nuke
> Revert "Set ctx.cluster even when a job has no roles"

- teuthology/openstack/__init__.py
- teuthology/openstack/test/test_openstack.py
- teuthology/provision/openstack.py
It requires setting the OS_URL depending on the command and avoids
calling the auth endpoint entirely.
Fixes: http://tracker.ceph.com/issues/16893
> openstack: use OS_AUTH_TYPE=token_endpoint when possible

- teuthology/ceph.conf.template
This lets the reweight-by-utilization command work even after mons are
restarted (ceph_manager is currently setting this via injectargs, but that
is not persistent).
> ceph.conf: set min rweight min bytes per osd = 10

- teuthology/ceph.conf.template
Merged this *after* the alignment fix is backported ot all
relevant branches: 
https://github.com/ceph/ceph/commit/80473f63853593e53d72f17c098152caf17f5e9e
> ceph.conf: journal_zero_on_create = true

- docs/intro_testers.rst
- scripts/suite.py
- teuthology/report.py
- teuthology/suite/__init__.py
- teuthology/suite/run.py
This isn't quite done yet but is ready for testing. Feedback is welcome!
Things that should be added:
Update: I think this is ready now.
> Add rerun capability to teuthology-suite

- teuthology/config.py
None of our labs are using /var/lib/teuthworker/archive anymore. The
incorrect default could trip up users.
> Update the default archive_base path

- teuthology/orchestra/connection.py
I don't know why this was ever the case, but ignoring user@host
from the targets list just seems like a bad idea, and causes
problems, because tasks/ansible/etc. assume that the user to use
is ubuntu.  If that's not what .ssh/config says, there's just
going to be trouble...but there's no reason to pay attention
to .ssh/config there; if you really want to play tricks, edit
your target list accordingly.
Fixes: http://tracker.ceph.com/issues/17125
> orchestra.connect: do not override user/host from ~/.ssh/config

- teuthology/provision/downburst.py
> downburst: Make sure python 2 is installed on Fedora

- teuthology/exit.py
- teuthology/orchestra/console.py
- teuthology/orchestra/test/test_console.py
- teuthology/task/console_log.py
- teuthology/test/task/test_console_log.py
- teuthology/test/test_exit.py
This PR first adds a framework for installing and removing signal handlers, allowing small tasks to be queued for execution when teuthology receives a given signal, or set of signals.
We then tell the ``console_log`` task to use this feature to ensure that the processes it spawns to log serial console output are killed when teuthology gets a ``SIGTERM``.
> Don't leak console-logging processes when a job is killed

- teuthology/misc.py
- teuthology/orchestra/remote.py
Avoids remote and local temp files, and subsequent read/write thrashing of local dir.  Since some of those directories are multiple tens or hundreds of gigabytes, the extra file load is important, and this should save time as well just by skipping the extra I/O thrashing (which the cephfs particularly hates)
> Change pull_directory to use a remote tar streaming to the local extract

- teuthology/nuke/actions.py
try to remove libcephfs2 as well.
> teuthology: update nuke for libcephfs2

- setup.py
This reverts commit f2576e7a719a129a3c8be603bd9993d2b1ec94f2.
We finally heeded all the deprecation warnings.
> Revert "Pin ansible to <2.2.0"

- teuthology/task/kernel.py
ceph-build kernel packages will be named -ceph-g${SHA1:0:12}.  As the
first step towards using ceph-build, change the local package regex.
With this, I'm able to download post ceph/ceph-build#540 packages and
install them as a local deb/rpm.
> kernel: update get_sha1_from_pkg_name() regex

- teuthology/misc.py
- teuthology/packaging.py
We saw several cases where repo file contents were actually small HTML
files containing "502 Bad Gateway" errors. This will cause ShamanProject
to raise an exception if that happens - and not write broken repo files.
> ShamanProject: don't write broken repos

- teuthology/suite/matrix.py
The previous approach *almost* works, but ('a') sorts after 'b'.
>>> sorted([('a',), 'b'])
['b', ('a',)]
Signed-off-by: Samuel Just <sjust@redhat.com>
> matrix.py: actually generate sorted descriptons

- teuthology/task/kernel.py
shutdown is a symlink to systemctl on xenial, and on "shutdown -r now"
network gets shut down before ssh has a chance to close gracefully.
There have been multiple complaints about this and some distantly
related fixes have made it into recent systemds [1].
This doesn't seem to happen on centos, probably because of different
systemd versions or sshd configuration, so this band-aid is for ubuntu
only.  "systemctl --no-block reboot" is nicer, but not available on
trusty.
[1] https://github.com/systemd/systemd/issues/2390
> kernel: fix reboot into the new kernel on xenial

- teuthology/suite/__init__.py
Also remove a stray print statement
> suite: Correct rerun behavior when no jobs match

- teuthology/worker.py
The new suite_repo setting was persisting between jobs, which is...
undesirable.
> worker: reload teuthology config before each job

- teuthology/task/install/valgrind.supp
Adds a valgrind suppression for a very strange memory leak only seen in radosgw under teuthology. When it reproduces, it always complains about the same 4 std::strings under md_config_t, with sizes 28, 51, 61, and 63.
I've been trying for months to track down the root cause, without success. I wasn't able to locate an offending commit via git bisect. I haven't seen it reproduce on packages built by shaman, so I suspect it's some artifact of the gitbuilders. We really want to get the rgw suite green so that kraken backports can be verified, so we're adding valgrind suppression as a last resort.
Fixes: http://tracker.ceph.com/issues/17924
> valgrind: suppression for md_config_t string leak

- teuthology/orchestra/console.py
An activated virtualenv has PATH set to find Python with /usr/bin/env.
A binary run from virtualenv/bin doesn't set PATH.  Use sys.executable
to handle both invocation methods.
Fixes: http://tracker.ceph.com/issues/17986
> spawn_sol_log: use sys.executable to find bin/python

- teuthology/suite/placeholder.py
High levels of debug messages are not required for ceph-deploy tests, also its causing remoto to hang during get of clent.admin key
> Remove high level of debug logging which is not required

- teuthology/orchestra/console.py
- teuthology/orchestra/test/test_console.py
If someone watching the console didn't think of using "console -s", we
end up power cycling the node in an attempt to get the login prompt.
This is futile -- if the watcher is still there after the node comes
back up, our connection will get dropped to spy mode again.
Use -f to temporarily force existing connections into spy mode when we
attach to save a power cycle.
> console: force existing connections into spy mode if !readonly

- teuthology/prune.py
invoking -p 7 -r 30 was only removing passed jobs 30 days or older.
> prune: use the shortest time of -p or -r to decide on processing

- teuthology/nuke/actions.py
In CentOS 7, the command "ps -ef | grep 'java.*hadoop' | grep -v grep | awk
'{print $2}' | xargs kill -9" produces undesirable output when no matching
processes exist.
Note: the "-f" option to pkill mimics the semantics of "ps -ef". For example,
"ps -ef | grep 'java.*hadoop'" will match a process called "sh java343hadoop",
while pkill will match that process only with the -f option:
$ ps -ef | grep "java.*hadoop" | grep -v grep
root     16165  4101  0 11:57 pts/1    00:00:00 sh java343hadoop
$ pkill -KILL "java.*hadoop"
$
$ ps -ef | grep "java.*hadoop" | grep -v grep
root     16165  4101  0 11:57 pts/1    00:00:00 sh java343hadoop
$ pkill -f -KILL "java.*hadoop"
[1]+  Killed                  sh java343hadoop
Fixes: http://tracker.ceph.com/issues/17981
Signed-off-by: Nathan Cutler …
> nuke: Use pkill -KILL to unconditionally wipe out hadoop processes

- teuthology/run.py
- teuthology/task/clock.py
See commit comments, but, clock will force a sync with ntpdate, which is probably the better path.
Tested with a local teuthology run and a small suite excerpt (look for "Syncing clocks"):
http://pulpito.ceph.com/dmick-2017-01-18_13:39:43-rados-kraken---basic-mira/
> Change to use task 'clock' instead of 'clock.check'

- teuthology/run.py
- teuthology/suite/placeholder.py
as "workunits" reside in ceph/qa/workunits, it's more intuitive to
respect suite-branch option when cloning workunits.
> suite: use "suite_hash" as the default sha1 for workunit

- teuthology/provision/cloud/openstack.py
We attach volumes immediately after creating them; sometimes they are
still momentarily in the 'creating' state, causing the attach call to
throw a BaseHTTPError. When that happens, simply retry the request
instead of failing node creation, starting the entire cycle all over
again.
> cloud.openstack: Also retry on BaseHTTPError

- teuthology/provision/downburst.py
Looks like an argument was dropped to a string format().
> provision.downburst: Fix a bug in PR #1041

- setup.py
python-cinderclient and/or keystoneauth1 apparently don't want
requests 2.13.0, so make it illegal for now
> setup.py: disallow requests 2.13.0

- teuthology/suite/placeholder.py
"git clone" allows us to clone a single branch, but not a sha1, so
prefer "branch" if it's available.
> suite: use "suite_branch" for workunit if avaiable

- teuthology/__init__.py
- teuthology/run.py
- teuthology/worker.py
The first commit just takes the superior excepthook from the worker module and lets the run module use it.
The second commit should make sure we can at least see uncaught exceptions in gevent greenlets in job logs.
> Improve exception logging

- teuthology/misc.py
- teuthology/parallel.py
- teuthology/test/test_misc.py
The change to `misc.wait_until_osds_up()` is the follow-up to #1056, #1045 and #1033.
The change to `parallel` fixes a very longstanding bug that prevented jobs from failing properly. If one of the parallel greenlets encountered an exception, it did not interrupt any others. In certain common situations, e.g. the `rados` task running `ceph_test_rados`, it meant the job kept running until it hit the global timeout and was killed - without any useful error message.
An example of this in action:
[This upgrade run using teuthology master](http://pulpito.ceph.com/zack-2017-03-23_14:08:11-upgrade:hammer-jewel-x-kraken---basic-ovh/) timed out.
[This run](http://pulpito.ceph.com/zack-2017-04-05_12:19:17-upgrade:hammer-jewel-x-kraken---basic-ovh/), which is otherwise identical, failed very quickly …
> If we're going to fail, fail sooner

- teuthology/misc.py
Add check argument to delete_file to provide the ability to ignore a
failed delete (say if the file to delete does not exist)
Add preserve_perms argument to move_file to make the preservation of
permissions optional. This makes move_file usable if the target
file does not yet exist.
Existing invocations are unchanged.
Signed-off-by: Jan Fajerski <jfajerski@suse.com>
(cherry picked from commit f9aef0126313a24b791bc16918eb47d113ee6139)
> misc: add flexibility to delete_ and move_file

- teuthology/run.py
ceph-ansible task is modifying some of the repo's set earlier
and affecting cdn runs, change the order to run it after ansible
task is run.
> [task/internal]: run the redhat internal task after ansible.cephlab task

- setup.py
nose is a dependency for https://github.com/ceph/ceph/pull/14688, which builds a qa suite around the existing rgw multisite tests in `src/test/rgw/test_multi.py`. those tests need to be invoked by the teuthology task itself, because they run `radosgw-admin` commands on different nodes, start/stop daemons, etc
> rgw: add nose dependency for rgw_multisite_tests task

- teuthology/task/internal/syslog.py
kern.log and misc.log weren't getting written to on ubuntu machines.
On centos chcon is saving the day.
Fixes: http://tracker.ceph.com/issues/16835
> task/internal/syslog: make kern.log and misc.log world-writable

- scripts/suite.py
Avoids using existing kernel on test nodes and always installs distro kernel if no option provided
Fixes: http://tracker.ceph.com/issues/20203
> scripts/suite.py: use distro kernel as default for all tests

- scripts/suite.py
-k defaults to distro since e1f5a3a76971 ("use distro kernel as default
for all tests").
> suite: update usage for -k

- teuthology/task/ceph_ansible.py
As requested by Andrew and Alfredo to debug failed ansible jobs
properly
> [tasks/ceph-ansible]: Add debug output for ceph-ansible runs

- teuthology/nuke/actions.py
To handle cases where /var/run/ceph is left behind
> remove any stale /var/run/ceph

- teuthology/task/ceph_ansible.py
- teuthology/test/task/test_ceph_ansible.py
It achieves 2 things
a) tests out purge-cluster and iron out any issues as we find them
b) can make ceph-ansible tests run on any nodes in lab (smithi, mira etc)
> purge cluster during teardown

- teuthology/task/internal/syslog.py
the log format of ceph-create-keys is "$level:$name:$message"
Fixes: http://tracker.ceph.com/issues/20171
> task/internal/syslog: blacklist log from ceph-create-keys

- teuthology/task/install/__init__.py
> task/install: should pass `node` as `config` to get_upgrade_version()

- teuthology/repo_utils.py
Use Popen.communicate() instead of Popen.wait()
> When bootstrapping teuthology, avoid deadlocks

- teuthology/ceph.conf.template
Since we're testing, we always want the full thing.  This
used to not really matter because almost everything was
going to the clog at info level, but as of luminous things like
the cluster map version echos are at debug level.
> teuthology: set cluster log level to debug

- teuthology/packaging.py
- teuthology/test/test_packaging.py
rbd_fio task has been switched to {install,remove}_package().  This
commit mirrors ceph.git commit d14f2da437a3 ("task/rbd_fio: allow for
unsigned packages"):
"Similar to what the teuthology install.py task does, add --force-yes to
the apt-get install so that unsigned packages are successfully
installed. It is needed when the buildpackages task is used to create
packages on the fly."
> packaging: pass --force-yes to allow for unsigned deb packages

- teuthology/provision/downburst.py
The first VPS on every VPSHOST runs off the VPSHOST root drive.  Because
of this, the root drive is filling up due to the addition of another OSD
drive: https://github.com/ceph/teuthology/pull/1099
This not only results in nagios alerts but could also result in needless
job failures.  OSD drives/partitions are already only 100G on smithi so
this should be fine.
> downburst: Decrease disk size to 100GB

- bootstrap
1. Supported for CentOS.
2. Update the rpm package of pyton2-pip for redhat family.
> Supprted for CentOS

- teuthology/orchestra/run.py
- teuthology/orchestra/test/test_run.py
`RemoteProcess`, a class built around Paramiko's `exec_command()`, currently lacks support for the `cwd` parameter. It specifies the directory in which the requested command should be executed. This stays in contrast to `LocalRemoteProcess` from the `vstart runner` as it wraps Python's `subprocess`, and thus naturally offers the feature. The patch unifies these two implementations.
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>
Related PR: https://github.com/ceph/ceph/pull/16022.
> RemoteProcess: command can be now executed in specified directory.

- teuthology/task/ceph_ansible.py
we have been using custome site.yml from within the task which is not
accurate when compared to the file provided by ceph-ansible repo, instead
use the sample file as the main playbook for tests.
> [tasks/ceph-ansible]: use site.yml from the ceph-ansible repo

- teuthology/task/internal/syslog.py
Caused OVH node jobs to fail when it shouldn't have
> task/internal/syslog: blacklist openstack datasource log

- teuthology/task/ceph_ansible.py
set ANSIBLE_LIBRARY environment variable for purge cluster playbook to work properly.
> task/ceph-ansible: copy purge-cluster to top-level directory for it to work

- teuthology/task/ceph_ansible.py
- teuthology/test/task/test_ceph_ansible.py
radosgw_interface is now required to run rgw playbook.
> [task/ceph-ansible]: Add required radosgw_interface due to ceph-ansible upstream changes

- teuthology/ceph.conf.template
The extra logging during osd shutdown is becoming optional; enable it in
qa.
> ceph.conf: osd_debug_shutdown=true

- teuthology/provision/downburst.py
http://tracker.ceph.com/issues/21727
Tested on:
- CentOS 7.4
- CentOS 7.3
- Ubuntu 16.04
- Ubuntu 14.04
> downburst: Explicitly type our user-data

- teuthology/ceph.conf.template
Signed-off-by: Greg Farnum <gfarnum@redhat.com>
> ceph.conf: enable debug asserts on shutdown

- teuthology/ceph.conf.template
it might take longer than 1 minutes to:
1. create a monmap
2. create the auth keyrings
3. prepare the osd devices and activate OSDs (fdisk,mkfs.xfs,ceph-osd --mkfs)
4. prepare the monitors (mkfs), and start them
5. start mgr
6. any mgr sends a beacon to monitor.
> ceph.conf: prolong "mon mgr mkfs grace" to 2 minutes

- teuthology/misc.py
if an node hosts 6 OSDs, it would take longer to boot. this addresses
the failure of
/a/kchai-2017-11-03_05:56:44-rados-wip-jewel-backports-reloaded-distro-basic-mira/1806380.
> misc.wait_until_osds_up: prolong the timeout from 5 min to 9 min

- teuthology/task/hadoop.py
hadoop v2.5.2 is pretty old now, and is removed from the hadoop/common
directory. but it can be found in archive.
> task/hadoop: update hadoop 2.5.2 url

- teuthology/task/__init__.py
When we initialize a ConsoleLog task during FOG reimaging, the ctx
object has no config attribute.
> Task: Tolerate a missing ctx.config

- teuthology/nuke/__init__.py
Now that FOG is in master, we don't have to reimage on nuke. Let's shut
them down - the next job will bring them up again during the reimage
process.
> nuke: Power off FOG machines instead of reimaging

- teuthology/task/install/valgrind.supp
<error>
<unique>0x7</unique>
<tid>1</tid>
<kind>Leak_StillReachable</kind>
<xwhat>
<text>40 bytes in 1 blocks are still reachable in loss record 8 of 21</text>
<leakedbytes>40</leakedbytes>
<leakedblocks>1</leakedblocks>
</xwhat>
<stack>
<frame>
<ip>0x9EAF203</ip>
<obj>/usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so</obj>
<fn>operator new(unsigned long)</fn>
<dir>/builddir/build/BUILD/valgrind-3.12.0/coregrind/m_replacemalloc</dir>
<file>vg_replace_malloc.c</file>
<line>334</line>
</frame>
<frame>
<ip>0xBDB237</ip>
<obj>/usr/bin/ceph-mon</obj>
<fn>allocate</fn>
<dir>/opt/rh/devtoolset-7/root/usr/include/c++/7/ext</dir>
<file>new_allocator.h</file>
<line>111</line>
</frame>
<frame>
<ip>0xBDB237</ip>
<obj>/usr/bin/ceph-mon</obj>
<fn>allocate</fn> …
> teuthology/task/install/valgrind.supp: new rocksdb leak

- teuthology/task/install/valgrind.supp
the analysis in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=700899
also applies to ceph-common.
Fixes: http://tracker.ceph.com/issues/22438
> teuthology/task/install/valgrind.supp: add suppression for dlopen()

- teuthology/task/install/valgrind.supp
These were set for kind 'possible' which was failing
to suppress Leak_DefinitelyLost errors.
Also add several suppressions related to module
initialization.
> install: extend python-related valgrind rules

- teuthology/ceph.conf.template
All of the errors I see seem to be between .5 and .9s.
> ceph.conf: mon_clock_drift_allowed .5 -> 1.0

- bootstrap
The name of the package is community-mysql-devel in currently
supported releases.
> bootstrap: Rename mysql-community-devel for fedora

- teuthology/task/selinux.py
These started showing up once we added RHEL to Sepia.
Fixes: https://tracker.ceph.com/issues/23343#note-5
> task.selinux: Whitelist rhsmd denials

- setup.py
Having an unversioned libvirt-python in setup.py started causing
problems with tox, since it uses an sdist archive as a basis for
installing teuthology in its virtualenvs. Removing it is consistent with
best practices. We'll still keep it in requirements.txt.
> Drop libvirt from setup.py

- teuthology/provision/fog.py
- teuthology/provision/test/test_fog.py
http://sentry.ceph.com/sepia/teuthology/issues/3357/events/135936/
<dgalloway> the problem is when there are no running smith jobs and then a big run gets scheduled.  FOG gets backed up and makes the testnodes wait
> Increase timeouts teuthology will wait for FOG provisioning

- teuthology/task/kernel.py
Fixes: http://tracker.ceph.com/issues/23381
> task.kernel: Only show latest kernel when running rpm -q kernel

- teuthology/suite/placeholder.py
Caused by: https://github.com/ceph/ceph/pull/20660 (ea97c120d2173f2fc70d979d57a7edb2a6c5da5e)
Fixes: https://tracker.ceph.com/issues/23662
> placeholder: update whitelist for osd slow op wrn

- teuthology/suite/placeholder.py
because, in ceph/qa/tasks/ceph.py, we start mon, mgr, osd, and then mds.
there is a time window where there is no mds around, but mgr is checking
mdsmap for MDS_ALL_DOWN errors. there is no way to disable this check in
this time window. so we just whitelist MDS_ALL_DOWN here.
> placeholder: whitelist MDS_ALL_DOWN by default

- teuthology/lock/query.py
there is chance that we will have 404 when accessing a job's URI.
> teuthology/lock: ignore none 200 jobs in node_job_is_active()

- teuthology/suite/placeholder.py
Should no longer be necessary after [1].
[1] https://github.com/ceph/ceph/pull/21684
> remove blanket SLOW_OPS whitelist

- teuthology/task/ansible.py
ansible-playbook will not run with an empty vault password file.  It
will run if the password file has something in it even if it doesn't get
used.
Multiple ansible vault identities won't be fixed until at least 2.5 (https://github.com/ansible/ansible/issues/38146) so this is probably our safest bet for now.
> ansible.py: Write "foo" to ~/.vault_pass.txt instead of touching

- teuthology/task/ceph_ansible.py
ceph-ansible has some new dependencies in requirements.txt which need to be installed to avoid the error:
`[ERROR]: The python-notario library is missing. Please install it to continue.`
Fixes: http://tracker.ceph.com/issues/24230
> ceph-ansible: add hard-coded notario dependency

- teuthology/orchestra/daemon/systemd.py
Also check status when daemon is restarted, any failed daemon restart will raise an error early on.
> [orchestra/systemd]: check status when daemon is restarted

- teuthology/task/internal/__init__.py
Addresses error message:
AttributeError: 'tuple' object has no attribute 'split'
> Fix fetch_binaries_for_coredumps

- teuthology/suite/build_matrix.py
- teuthology/suite/test/test_build_matrix.py
Idea is to support position independent suites so copies do not break symlinks. e.g.: 
https://github.com/batrick/ceph/commit/73f636db1b2616c0acccc2b2356549d1e03600c3
> build_matrix: ignore hidden files

- teuthology/worker.py
The patch fixes uncaught exception RuntimeError:
I could not figure out the owner of the requested job.
Please pass --owner <owner>.
Worker dies with unhandled exception in run_with_watchdog
if it can't figure out owner of a job, which it tries
to kill when job runs longer then given limit of time.
> Fix worker can't figure out owner of a job

- teuthology/openstack/openstack-teuthology.init
This patch allows to restart dead workers separately not halting the rest of the teuthology components,
and what is more importantly the beanstalkd service. That makes it possible to extend the number of workers as well. Either of pulpito and paddles can be restarted alone too.
> Restart dead workers

- teuthology/ceph.conf.template
This will be set in the cephfs qa suites: https://github.com/ceph/ceph/pull/22740
> ceph.conf.template: drop cephfs configs

- teuthology/task/ceph_ansible.py
default ansible to 2.5 as per ceph-ansible requirements for ceph master branch testing.
> default ansible to 2.5 as per ceph-ansible requirements

- teuthology/suite/run.py
A branch name containing a slash is perfectly legal in git, but
teuthology uses branch names verbatim in run names, which causes POSTs
to fail when submitting runs to paddles. Replace all '/' in run names
with ':' to allow for branches with slashes in their names.
Signed-off-by: Adam Wolfe Gordon <awg@digitalocean.com>
> Handle branch names containing slashes

- teuthology/task/install/__init__.py
We actually had a test that was "upgrading" from one version to the very same
version. This commit adds a check for that case.
> [DNM] upgrade check: upgrade to same version is a noop

- teuthology/task/install/rpm.py
In [8]: ?s.replace
Docstring:
S.replace(old, new[, count]) -> str
> task/install: str.replace() does not keyword args

- requirements.txt
- setup.py
- tox.ini
pytest requires pluggy >= 0.7, while we always use pluggy 0.6, as
specified by requirements.txt. as this version is good enough for
tox. but in tox.ini, we do use pytest, and no version is specified,
so we have good chance running into https://github.com/pytest-dev/pytest/issues/3753
> setup,py,requirements.txt: add pytest

- teuthology/orchestra/opsys.py
- teuthology/orchestra/remote.py
- teuthology/orchestra/test/test_opsys.py
Fixes: http://tracker.ceph.com/issues/18141
> platform.linux_distribution() is deprecated; stop using it

- teuthology/run.py
We want to be able to check the final values of os_type and os_version
in get_initial_tasks, so move the command-line override up to before
the get_initial_tasks() method call.
> run.py: Provide --os-{type,version} values to get_initial_tasks

- teuthology/task/internal/syslog.py
None of these should cause test failures.
> internal/syslog: whitelist ceph-crash daemon messages

- scripts/schedule.py
- teuthology/results.py
- teuthology/schedule.py
- teuthology/suite/__init__.py
- teuthology/suite/run.py
- teuthology/suite/test/test_run_.py
- teuthology/test/test_schedule.py
- teuthology/worker.py
> script,worker,suite: note down the rerun parameter in the first-job-in-suite

- teuthology/suite/__init__.py
- teuthology/worker.py
this change fixes the --rerun feature again.
>  worker: do not pass --timeout to first-in-suite job

- teuthology/task/sleep.py
Add the word "seconds" at the end of the log message, since "time.sleep()"
takes a number which is always interpreted as the number of seconds to sleep
for.
Before this commit, the log said (ambiguously):
INFO:teuthology.task.sleep:Sleeping for 10
After:
INFO:teuthology.task.sleep:Sleeping for 10 seconds
> teuthology/task/sleep: be explicit about seconds

- teuthology/task/install/valgrind.supp
Boost.Thread passes `tls_destructor` to `pthread_key_create()` in hope
to free the allocated memory stored in TLS key `current_thread_tls_key`,
but neither Boost.Thread nor us uses `pthread_exit()` for calling the
cleanup functions. and Boost.Thread is against `pthread_exit()`, see [0,1].
but Boost.Thread offers a preprocessor macro to define a global variable
whose destructor calls `tls_destructor()`, but per [2], this macro is
not defined by default. and per [3], this macro could cause assertion
failure in Boost. so it might be advisable to not define it, even we
could do so in BuildBoost.cmake.
and since this `Leak_StillReachable` leak is a one-shot thing. i am
adding it to the suppression file.
---
[0] https://www.boost.org/doc/libs/1_68_0/doc/html/thread/thread_management.html#thread. …
> teuthology/task/install/valgrind.supp: add suppression for Boost.Thread

- scripts/openstack.py
- scripts/suite.py
- teuthology/config.py
- teuthology/run_tasks.py
- teuthology/suite/placeholder.py
- teuthology/suite/run.py
With this option, all jobs in the run sleep for the given number of seconds as
the very last thing they do, regardless of success or failure.
Use case: interactive debugging
> suite: Implement --sleep-before-teardown option

- teuthology/task/dump_ctx.py
This task is supposed to pretty-print the ctx and config parameters that are
passed to each task.
The intended use is didactic: teaching myself and others how to use teuthology. I plan to add this to the existing "dummy" task:
https://github.com/ceph/ceph/tree/master/qa/suites/dummy
> teuthology/task: implement dump_ctx internal task

- teuthology/openstack/__init__.py
> openstack: use ssh identity as key_filename by default

- scripts/openstack.py
- scripts/suite.py
- teuthology/config.py
- teuthology/run_tasks.py
- teuthology/suite/placeholder.py
- teuthology/suite/run.py
This reverts commit c81ee9618faa6aeb56a4cc741e9f937b287b065e, which
broke the sequential and parallel tasks.
Fixes: https://tracker.ceph.com/issues/36230
> Revert "suite: Implement --sleep-before-teardown option"

- teuthology/run.py
Make run config visible in the logs even if -v option is not passed.
> Increase log level to 'info' of run config

- teuthology/test/task/test_install.py
Addresses failure in verify_package_version:
TypeError: argument of type 'Mock' is not iterable
> tests: use dict() instead Mock() to test config

- teuthology/task/install/valgrind.supp
> valgrind: suppress __libc_csu_init leaks

- teuthology/misc.py
- teuthology/orchestra/remote.py
- teuthology/orchestra/run.py
The Remote class does not respect ip addresses
when it comes to define shortnames. As a result,
the hostname is not shown correctly in the log.
For ipv4 it only shows first number of the octet.
For ipv6 it even does not allow to proceed,
and raises exception in orchestra.run.
> Fix ipv4 and ipv6 address logging for Remote.run

- teuthology/task/install/valgrind.supp
Yes, this is a big hammer, and we are ignoring a lot.  However, it is a
HUGE step forward to what we do now, which is not check for ceph-mgr
leaks at all.
By adding this suppress I found and fixed 3 separate ceph-mgr leaks.  This
will let us prevent others (in non-Py code) from being introduced.
> valgind: ignore all leaks relating to CPython code

- docs/_static/worker_start.sh
- teuthology/__init__.py
We print the error to teuthology log anyway. This avoids inexplicable EIO
errors printed by the greenlet exception errors.
Fixes: http://tracker.ceph.com/issues/36731
>  skip calling greenlet exception handler

- teuthology/run_tasks.py
It turns out it's possible for a file qa/tasks/foo.py to exist,
yet importing it still raises an ImportError because it references a
non-existent symbol.
In this case, teuthology was clobbering the real ImportError with its
own bogus text.
Fixes: http://tracker.ceph.com/issues/37370
> run_tasks.py: log the right ImportError message

- scripts/suite.py
- teuthology/suite/__init__.py
- teuthology/suite/run.py
Allow users to skip validation of SHA1s passed to -S when submitting
jobs via teuthology-suite. This is useful when testing against
non-GitHub repos, since teuthology can't validate refs for a plain git
repository.
Signed-off-by: Adam Wolfe Gordon <awg@digitalocean.com>
> Add no-validate-refs option to teuthology-suite

- teuthology/task/install/__init__.py
before this change, the package list to be installed are ordered by
the hash function used by set().
after this change, the order of packages are not changed. so we can
ensure the order of package installation is the identical to that
of package list in yaml.
> task/install: keep the order of pkgs to be installed

- teuthology/task/install/__init__.py
- teuthology/task/install/rpm.py
see https://github.com/ceph/ceph/pull/25463 for a use case of this change.
see http://pulpito.ceph.com/kchai-2018-12-11_05:52:36-rados-wip-kefu2-testing-2018-12-11-0943-distro-basic-smithi/ for the addressed failures.
> task/install: add "downgrade_packages" option for "install" task

- teuthology/task/install/__init__.py
- teuthology/task/install/rpm.py
- populate "downgrade_packages" to `nested_config` in `task()`.
otherwise, the "downgrade_packages" is invisible to the `install()`
function.
- also print logging message before downgrading packages.
- cleanup rpm._downgrade_packages(), no need to format `downgrade_cmd`.
it's already formated.
> task/install: populate "downgrade_packages" to nested_config

- teuthology/task/install/rpm.py
> task/install: assert on installed_version > downgrade_version

- teuthology/orchestra/run.py
When run.run is used with 'stdout' argument, the output of run command
is read to the given stream and logged with corresponding level only after
completion, which is different from the default behaviour. This 'hides'
useful information when, for example, the command is hung or stuck.
Aso it is usually handy when there are some data can be found
in the log for a prolonged command execution during runtime.
This patch addresses the issue.
> orchestra: allow runtime logging for sh

- teuthology/suite/matrix.py
Addresses issue while trying to dump matrix object:
```
AttributeError: Base instance has no attribute '__getitem__'
```
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.de>
> Fix matrix dump tostr() method

- teuthology/task/install/valgrind.supp
```
<kind>Leak_PossiblyLost</kind>
<xwhat>
<text>7 bytes in 1 blocks are possibly lost in loss record 20 of 33,344</text>
<leakedbytes>7</leakedbytes>
<leakedblocks>1</leakedblocks>
</xwhat>
<stack>
<frame>
<ip>0xA811C23</ip>
<obj>/usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so</obj>
<fn>malloc</fn>
<dir>/builddir/build/BUILD/valgrind-3.13.0/coregrind/m_replacemalloc</dir>
<file>vg_replace_malloc.c</file>
<line>299</line>
</frame>
<frame>
<ip>0xE709809</ip>
<obj>/usr/lib64/libc-2.17.so</obj>
<fn>strdup</fn>
</frame>
<frame>
<ip>0xFC49444</ip>
<obj>/usr/lib64/libnl-3.so.200.23.0</obj>
<fn>__trans_list_add</fn>
</frame>
<frame>
<ip>0xF9E07E0</ip>
<obj>/usr/lib64/libnl-route-3.so.200.23.0</obj>
</frame>
<frame>
<ip>0x9BF7B02</ip>
<obj>/usr/lib64/ld-2.17.so</obj>
<fn>_dl_init</fn> …
```
> valgrind.supp: whitelist something in glibc

- teuthology/orchestra/remote.py
Fix retry and socket timeouts misconception for reconnect.
Add default sleep time as argument to the signature.
Signed-off-by: Kyr <kyrylo.shatskyy@gmail.com>
> orchestra: fix retry and socket timeout misconception

- teuthology/task/ansible.py
yaml.safe_load() also throws yaml.scanner.ScannerError. so use
yaml.YAMLError to cover them all. see
https://pyyaml.org/wiki/PyYAMLDocumentation .
> ansible.py: catch yaml.YAMLError when yaml.safe_load()

- teuthology/task/selinux.py
Got this in RHEL 7.6 testing.
Fixes: https://tracker.ceph.com/issues/38519
> selinux: ignore nagios denial

- scripts/openstack.py
- scripts/suite.py
- teuthology/suite/__init__.py
This patch introduces TEUTH_ based environment variables
which can be used to avoid bulky commands while overriding
default values for some of the teuthology arguments.
Make --ceph argument optional for teuthology-suite,
and defaults to 'master'.
> openstack: take defaults from environment

- scripts/openstack.py
- teuthology/openstack/__init__.py
- teuthology/task/install/rpm.py
Make it possible to read repositories from a file by simply adding '@' symbol
at the beginning `--test-repo` argument value, for example from yaml:
```
---
- name: foo0
url: http://example.com/repo/foo0
- name: foo1
url: http://example.com/repo/foo1
priority: 2
- name: foo2
url: http://example.com/repo/foo2
priority: 1
- name: foo3
url: http://example.com/repo/foo3
```
Equivalent json file content below:
```
[
{
"name": "foo0",
"url": "http://example.com/repo/foo0"
},
{
"name": "foo1",
"url": "http://example.com/repo/foo1",
"priority": 2
},
{
"name": "foo2",
"url": "http://example.com/repo/foo2",
"priority": 1
},
{
"name": "foo3",
"url": "http://example.com/repo/foo3"
}
]
```
> Read test repo from file

- teuthology/task/kernel.py
also make the "Checking kernel version...want" logmsg include quotes
for spotting problems more quickly
> task/kernel: fix Depends: parsing for dependencies with "|"

- scripts/suite.py
- teuthology/suite/__init__.py
By default suite branch must be equal to ceph one.
> teuthology-suite: no default value for suite branch

- teuthology/provision/cloud/openstack.py
- teuthology/provision/cloud/test/test_openstack.py
In order to simplify selection of flavors and networks
there is added support for allow_sizes and allow_networks
records for each provider configuration.
Both supports either single regular expression or a list
of regular expressions.
Also exclude_sizes supports lists now as well.
> libcloud: add allow_sizes and allow_networks

- teuthology/task/install/rpm.py
EPEL7 has switched over to python3.6 as the main python3. and we started
packaging python bindings for python3.6 since
https://github.com/ceph/ceph-build/pull/1283
> task/install: normalize python3 packages to python36 ones

- teuthology/task/selinux.py
This is with RHEL 7.6.
The failure [1]:
2019-04-17T21:06:33.388 DEBUG:teuthology.run_tasks:Exception was not quenched, exiting: SELinuxError: SELinux denials found on ubuntu@smithi088.front.sepia.ceph.com: ['type=AVC msg=audit(1555531592.378:4451): avc:  denied  { rename } for  pid=10476 comm="updatedb" name="mlocate.db.eDrUCz" dev="sda1" ino=5477 scontext=system_u:system_r:locate_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1', 'type=AVC msg=audit(1555531589.705:4446): avc:  denied  { read write open } for  pid=10476 comm="updatedb" path="/var/lib/mlocate/mlocate.db.eDrUCz" dev="sda1" ino=5477 scontext=system_u:system_r:locate_t:s0-s0:c0.c1023 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=1', 'type=AVC …
> selinux: ignore updatedb failures

- teuthology/openstack/__init__.py
We need to always pass the parameters below in order to make it work using
environment variables:
--ceph
--ceph-repo
--suite-repo
--suite-branch
--teuthology-branch
Signed-off-by: gkyratsas <gkyratsas@suse.com>
Conflicts:
teuthology/openstack/__init__.py
> openstack: always pass branch and repo parameters

- setup.py
Signed-off-by: Yuval Lifshitz <yuvalif@yahoo.com>
This is needed for adding the tests in this PR: https://github.com/ceph/ceph/pull/27838
> rgw/pubsub: add dependencies needed for pubsub tests

- tox.ini
After upgrade mock from 2.0.0 to 3.0.3 the TestExiter started failing
with incorrect call_count.
> tox: set mock version to 2.0.0

- teuthology/orchestra/run.py
Introduced-by: ceph/ceph.git:3e0a1361f78452d79c283f70b5dc2b865d62cb61
Fixes: https://tracker.ceph.com/issues/39554
> orchestra/run: add omit_sudo arg used by vstart_runner

- teuthology/config.py
- teuthology/provision/cloud/test/test_openstack.py
This patch makes it possible to load config file directly
from the given path or data object, for testing purposes
and allows to remove silly notification about missing
teuthology.yaml file.
> config: add parameter for config load

- teuthology/orchestra/daemon/state.py
Fixes the chance of calling signal() on a  daemon which is not running. 
Found `AttributeError: 'NoneType' object has no attribute 'stdin'` in: http://qa-proxy.ceph.com/teuthology/jcollin-2019-06-27_15:38:48-fs-wip-daemonwatchdog-testing11-distro-basic-smithi/4071690/teuthology.log
Signed-off-by: Jos Collin <jcollin@redhat.com>
> orchestra/daemon: Fix proc AttributeError: 'NoneType'

- teuthology/orchestra/daemon/state.py
As there is [self.proc.stdin.close() in stop()](https://github.com/ceph/teuthology/blob/master/teuthology/orchestra/daemon/state.py#L135), there are chances
of write failing with IOError("File is closed").
Referring to the test result: http://qa-proxy.ceph.com/teuthology/jcollin-2019-07-02_09:10:36-fs-wip-daemonwatchdog-testing11-distro-basic-smithi/4087426/teuthology.log
This happened is because DaemonWatchdog sent SIGTERM signals in parallel to executing `stop_daemons_of_type()`. But however it's better to have a check here.
> teuthology/orchestra/daemon: Check if stdin is valid

- scripts/suite.py
- teuthology/suite/run.py
This is can be useful when one wants to disable kernel hash
> suite/run: add support 'none' for kernel branch parameter

- teuthology/task/selinux.py
The failures [1]:
2019-08-22T22:11:34.747 INFO:teuthology.orchestra.run.smithi195:> sudo grep 'avc: .*denied' /var/log/audit/audit.log | grep -v '\(comm="dmidecode"\|chronyd.service\|name="cephtest"\|scontext=system_u:system_r:nrpe_t:s0\|scontext=system_u:system_r:pcp_pmlogger_t\|scontext=system_u:system_r:pcp_pmcd_t:s0\|comm="rhsmd"\|scontext=system_u:system_r:syslogd_t:s0\|tcontext=system_u:system_r:nrpe_t:s0\|comm="updatedb"\)'
2019-08-22T22:11:34.810 INFO:teuthology.orchestra.run.smithi195.stdout:type=AVC msg=audit(1566509255.666:7592): avc:  denied  { read } for  pid=8598 comm="smartd" name="nvme0" dev="devtmpfs" ino=13028 scontext=system_u:system_r:fsdaemon_t:s0 tcontext=system_u:object_r:nvme_device_t:s0 tclass=chr_file permissive=1
2019-08-22T22:11:34.810 …
> selinux: ignore smartd

- teuthology/task/install/__init__.py
- teuthology/task/install/rpm.py
purge_data was used to remove any Ceph daemon metadata remaining after the 
teardown phase of the install task runs. In particular, the ceph task was 
known to leave OSD metadata behind in the OSD directories under /var/lib/ceph.
While the install task causes the ceph-osd package to be installed and creates
directories under /var/lib/ceph, it is the ceph task that actually
populates these directories. Thus, their "unpopulation" should be
implemented in the ceph task, and not here in the install task.
(If the directories were empty after the ceph task teardown phase, they would be
removed when the install task removes the ceph-osd package from the system. But 
the package management tool refuses to remove them when they contain files not 
owned by a package.)
Not running purge_data during …
> install: drop purge_data and related code

- teuthology/orchestra/remote.py
Use mktemp instead of Python's tempfile.mktemp since coreutils is more
easily available.
> orchestra/remote: rewrite mktemp to use coreutils mktemp

- teuthology/describe_tests.py
- teuthology/openstack/openstack-centos-6.5-user-data.txt
- teuthology/openstack/openstack-centos-7.0-user-data.txt
- teuthology/openstack/openstack-debian-8.0-user-data.txt
- teuthology/openstack/openstack-ubuntu-12.04-user-data.txt
- teuthology/openstack/openstack-ubuntu-14.04-user-data.txt
- teuthology/openstack/setup-openstack.sh
- teuthology/provision/openstack.py
- teuthology/suite/test/test_run_.py
- teuthology/test/test_run.py
Using only the last two numbers is problematic when mixing multiple
OpenStack clusters.
Conflicts:
teuthology/provision.py
> openstack: encode instance name with the full IP

- bootstrap
- teuthology/describe_tests.py
Just a couple of small bugfixes for running teuthology commands on a modern setup. Avoid symlink loops in teuthology-describe-tests and force the usage of python2 in the bootstrap script.
> Minor bugfixes for teuthology

- requirements.txt
- setup.py
> beanstalk: switch to py3 compatible package

- teuthology/config.py
- teuthology/repo_utils.py
- teuthology/suite/test/test_util.py
- teuthology/task/ansible.py
This is to be able to supply a custom location without changing
the ceph git base url.
Signed-off-by: Roi Dayan <roid@mellanox.com>
Conflicts:
teuthology/config.py
teuthology/suite.py
teuthology/test/test_suite.py
> config: add option for ceph cm ansible git url

- teuthology/task/install/rpm.py
The _package_overrides function is currently not required.
> install/rpm: Remove _package_overrides

- teuthology/misc.py
The str.format is not used anymore for ceph.conf.template
> misc: drop testdir replacement in skeleton_config

- teuthology/misc.py
- teuthology/test/test_misc.py
To ease porting and compatibility in order to avoid
usage of cStringIO.StringIO it is better to use
remote.sh method which supposed to return captured
value as a string.
> misc: use remote.sh instead of remote.run

- teuthology/misc.py
41a13eca480e38cfeeba7a180b4516b90598c39b fixed a longstanding bug that the lab
was relying on. Before the bug was fixed, the get_wwn_id_map function was doing:
```
try:
r = remote.run(
args=[
'ls',
'-l',
'/dev/disk/by-id/wwn-*',
],
stdout=StringIO(),
)
stdout = r.stdout.getvalue()
except Exception:
log.info('Failed to get wwn devices! Using /dev/sd* devices...')
return dict((d, d) for d in devs)
```
The bug was that "remote.run" was putting single quotes around the string
"/dev/disk/by-id/wwn-*" because it wasn't enclosed in Raw(...). The single
quotes were causing the command to fail, triggering the except clause, and that
was happening 100% of the time.
The fix in 41a13eca480e38cfeeba7a180b4516b90598c39b caused the command to start
succeeding, which caused execution to continue. As a …
> misc: temporary fix for "No space left on device" errors

- docs/intro_testers.rst
According to [1], ceph-qa-suite is deprecated (last commit is from
2016) and the QA suites are now in the ceph git repo in the qa/
directory. So point to that directory.
[1] https://github.com/ceph/ceph-qa-suite/
> docs: Fix link to ceph/qa suites in intro_testers.rst

- teuthology/orchestra/connection.py
This commit fixes 5ac7c2f and provides support for multiple identityfile,
besides paramiko.SSHClient.connect accepts list as well for key_filename,
pydoc excerpts:
key_filename:
the filename, or list of filenames, of optional private key(s) to
try for authentication
Fixes: https://tracker.ceph.com/issues/42543
> connection: key_filename can be a list

- teuthology/task/install/rpm.py
Our tests should be designed to not rely on any pre-existing repos. If there are
any pre-existing repos, these can potentially skew test results by causing
unexpected packages/package versions to be installed.
Therefore, wipe any pre-existing repos before adding the repos-under-test.
> install/rpm: wipe all zypper repos before adding repos-under-test

- docs/openstack_backend.rst
The --setup step was missing which lead to cryptic error messages when
running the following step (calling the dummy test suite).
> docs: Mention step to setup nodes on OpenStack

- teuthology/repo_utils.py
- teuthology/test/test_repo_utils.py
With newer git versions, the string when a branch is not found
is lower case[1].
This fixes the test TestRepoUtils.test_fetch_branch_fake_branch which
was failing due to this problem.
[1] https://github.com/git/git/commit/0b9c3afdbfb629363
> Fix fetch_branch() check for BranchNotFoundError with newer git

- teuthology/task/install/rpm.py
The 74034fe0348b94aedb247910f0d1c88842f4c3ac instroduced a failure:
Warning: No repositories defined.
Use the 'zypper addrepo' command to add one or more repositories.
The wipe command returns exit code 6 if there is no repos in the system.
> install/rpm: fix use the 'zypper addrepo' command

- teuthology/task/kernel.py
Signed-off-by: Rachana Patel <racpatel@redhat.com>
> using put_file method instead of python shutil.copyfileobj so it works for python 2 and python 3 both

- scripts/openstack.py
- teuthology/openstack/__init__.py
Instead of appending possible private keyfile paths internally, make
that the default for the --key-filename command line argument so users
see it when looking at the help.
> openstack: Make used private keys explicit

- teuthology/lock/query.py
- teuthology/misc.py
- teuthology/packaging.py
- teuthology/provision/cloud/openstack.py
- teuthology/provision/cloud/test/test_openstack.py
- teuthology/task/kernel.py
- teuthology/task/pcp.py
- teuthology/test/task/test_pcp.py
- teuthology/util/compat.py
Use py2/py3 compatible functions url* packages.
Python3
from urllib.parse import parse_qs, urljoin, urlparse, urlencode
from urllib.request import urlopen, Request
from urllib.error import HTTPError
Python2
from urlparse import parse_qs, urljoin, urlparse
from urllib import urlencode
from urllib2 import urlopen, Request, HTTPError
> python3: use compatible urllib packages

- teuthology/task/internal/redhat.py
skipping `yum udpate metadata` for rhel-8
for rhel-8 machines `yum update metadata` command fails saying that `no arguments for metadata` this is for downstream branch rh and not master
Signed-off-by: rakeshgm <rakeshgm014@gmail.com>
> skipping `yum udpate metadata` for rhel-8

- setup.py
Right now it's installed implicitly, but these feature tests require it:
https://github.com/ceph/ceph/pull/31922
Signed-off-by: Alfonso Martínez <almartin@redhat.com>
> Add cryptography as explicit dependency

- setup.py
valgrind.supp is used from ceph/qa, we should remove this from setup to avoid
any confusion
> valgrind.supp is used from ceph/qa

- teuthology/task/install/__init__.py
If overrides is None, repos will don't be assignmented.
In this case, will occur error "UnboundLocalError: local variable repos referenced before assignment"
Signed-off-by: dehao.shang@intel.com
> task/install: fix UnboundLocalError of local variable repos

- teuthology/task/kernel.py
> task/kernel: fix typo

- teuthology/task/internal/redhat.py
A temporary fix for `dbench` package not available seen in this run 
http://pulpito.ceph.redhat.com/rakesh-2020-01-06_12:06:20-rgw-nautilus-distro-basic-pluto/354305/
Signed-off-by: rakeshgm <rakeshgm014@gmail.com>
> workaround to install dbench for rhel-8

- teuthology/test/test_worker.py
- teuthology/worker.py
We no longer need to check for branches like 'argonaut', 'bobtail',
'cuttlefish' or 'dumpling'. These are long gone.
Removing the code simplifies it a bit.
Signed-off-by: Thomas Bechtold <tbechtold@suse.com>
> worker: Drop dead code handling old releases

- teuthology/task/internal/__init__.py
This way if systemd restarts  or is reinstalled (as it is on el8 at the
moment) we won't lose this setting.
> tasks/internal: put kernel.core_pattern in sysctl.conf too

- bootstrap
With setuptools 45 python2 support was dropped.
Signed-off-by: Jan Fajerski <jfajerski@suse.com>
> bootstrap: install setuptools 44

- teuthology/task/selinux.py
it's a workaround of https://tracker.ceph.com/issues/43229
> task/selinux: ignore SElinux denials caused by podman

- teuthology/suite/run.py
When running teuthology-suite with -t option, I see:
```
teuthology branch: wip-fix-opensuse-provisioning
ceph branch: wip-foo eb2fd5065c6e489ca8dd9282ba62ab231f144f7a
```
In other words, the ceph branch message has the SHA1 but the
teuthology branch message does not. This commit adds it.
> suite/run.py: provide teuthology hash along with branch

- teuthology/nuke/actions.py
- teuthology/orchestra/remote.py
- teuthology/task/selinux.py
task/selinux.py, orchestra/remote.py: disable SELinux for opensuse/suse distros
nuke/actions.py: added support for sle/opensuse distros
Signed-off-by: Roman Grigorev <rgrigorev@suse.de>
> Fix opensuse provisioning support

- teuthology/task/selinux.py
We ran into some odd grep bug treating the audit.log as binary and
wrongly returning a match result.
Fixes: https://tracker.ceph.com/issues/43797
> selinux: use text processing

- teuthology/task/ceph_ansible.py
Fixes: https://tracker.ceph.com/issues/43799
> ceph_ansible: Enforce python3 for virtualenv

- teuthology/task/ceph_ansible.py
Fixes: https://tracker.ceph.com/issues/43843
> ceph_ansible: Make sure cryptography version is compatible

- hammer.sh
Apparently `hammer.sh` is pretty old. It calls `teuthology-nuke` expecting the further call to `teuhology` will be able to still reach the nodes. However, it doesn't seem that anybody is turning them back these days.
The commit just drops the `teuthology-nuke` call.
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>
> hammer.sh: don't do teuthology-nuke anymore.

- docs/_static/worker_start.sh
The worker_start.sh script is using archive directory inside
the worker user home which cannot be changed, this patches
allows override ARCHIVE environment variable to address
this issue.
> worker_start: allow ARCHIVE variable override

- requirements2.txt
- requirements3.txt
We need to pump six to the latest 1.14.0 so we have
six.ensure_str() is available
> requirements: pip-compile -P six

- teuthology/task/kernel.py
Do not try to reconnect immediately after triggering the reboot,
because the reboot sequence might not have started yet (!)
Fixes: https://tracker.ceph.com/issues/44187
> task/kernel: after reboot, do not try to reconnect immediately

- teuthology/packaging.py
Now that https://github.com/ceph/chacra/pull/275 has been merged and
deployed, we can write this code without any kludge.
> packaging: remove zypper repo kludge

- requirements2.txt
- requirements3.txt
Suggesting using 2.8.0 version of apache-libcloud that introduces
a fix on openstack driver.
(https://github.com/apache/libcloud/pull/1367 is fixing issue
https://github.com/apache/libcloud/issues/1365)
Signed-off-by: Georgios Kyratsas <gkyratsas@suse.com>
> use libcloud 2.8.0 version 

- docs/siteconfig.rst
- teuthology/lock/cli.py
- teuthology/lock/ops.py
- teuthology/nuke/__init__.py
- teuthology/provision/__init__.py
- teuthology/provision/pelagos.py
- teuthology/provision/test/test_init_provision.py
- teuthology/provision/test/test_pelagos.py
Add provisioning support via Pelagos provisioner https://github.com/SUSE/pelagos/
Pelagios is  pxe boot and provisioning system which created especially for connecting bare metal nodes to ceph/teuthology testing system.
Integration test placed in pelagos repo pelagos/test_pelagos_teuthology/test_pelagos.py because depends on started Pelagios service
provision/pelagos.py: added support of Pelagos provisioning project, interface is compatible with FOG provisioner
provision/__init.py: added processing of pelagos section in teuthology configuration and provisioner instantiation
lock/*: added Pelagos provisioner instantiation
> provision: add Pelagos support

- teuthology/task/kernel.py
to address the failure of
```
File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/run_tasks.py", line 86, in run_tasks
manager = run_one_task(taskname, ctx=ctx, config=config)
File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/run_tasks.py", line 65, in run_one_task
return task(**kwargs)
File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/task/kernel.py", line 1326, in task
install_and_reboot(ctx, need_install)
File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/task/kernel.py", line 505, in install_and_reboot
install_kernel(role_remote, remote_pkg_path(role_remote))
File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/task/kernel.py", line 834, …
```
> task/kernel.py: should pass args with name

- teuthology/task/kernel.py
There is leftover, there should be remote.sh used instead of remote.run
> task/kernel.py: should pass args with name 2

- requirements2.txt
- requirements3.txt
- setup.py
The IPy module is a tool for handling of IPv4 and IPv6 addresses and
networks, the cephfs mount.py will use it to manage the IP addresses
to isolate the netns for each mount, which could let us get ride of
using ipmi command to hard shutdown the client node for some test cases.
Thanks @tchaikov very much for the help.
> requirements,setup: add ipy module for cephfs mount.py 

- teuthology/task/clock.py
when ntp is not config correctly, the clock task will be blocked
Signed-off-by: chuqifang <chuqifang@hisilicon.com>
> teuthology/task: add timeout for clock task

- teuthology/orchestra/daemon/systemd.py
- teuthology/task/internal/redhat.py
-  Added rhbuild attribute under redhat 
example:
```
redhat:
rhbuild: '4.x'
base-repo-url: <repo-url>
```
-  Code changes to retrieve correct daemon pid.
> added rhbuild attribute for redhat task and changes to retrieve correct daemon pid.

- teuthology/orchestra/test/integration/test_integration.py
- teuthology/task/hadoop.py
- teuthology/task/internal/__init__.py
- teuthology/task/mpi.py
- teuthology/task/ssh_keys.py
to be py3 compatible. this addresses the failure of
```
2020-04-05T12:35:02.036 INFO:teuthology.run_tasks:Running task ssh_keys...
2020-04-05T12:35:02.050 ERROR:teuthology.run_tasks:Saw exception from tasks.
File "/home/teuthworker/src/git.ceph.com_git_teuthology_py3/teuthology/run_tasks.py", line 86, in run_tasks
manager = run_one_task(taskname, ctx=ctx, config=config)
File "/home/teuthworker/src/git.ceph.com_git_teuthology_py3/teuthology/run_tasks.py", line 64, in run_one_task
task = get_task(taskname)
File "/home/teuthworker/src/git.ceph.com_git_teuthology_py3/teuthology/run_tasks.py", line 28, in get_task
module = _import('tasks', module_name, task_name, fail_on_import_error=True)
File "/home/teuthworker/src/git.ceph.com_git_teuthology_py3/teuthology/ …
```
> teuthology: s/cStringIO.StringIO/six.StringIO/

- teuthology/task/internal/__init__.py
This fix address failure like:
```
2020-04-10T10:35:13.508 ERROR:teuthology.run_tasks:Manager failed: internal.archive
File "/home/worker/src/teuthology_master/teuthology/run_tasks.py", line 167, in run_tasks
suppress = manager.__exit__(*exc_info)
File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
self.gen.next()
File "/home/worker/src/teuthology_master/teuthology/task/internal/__init__.py", line 363, in archive
fetch_binaries_for_coredumps(path, rem)
File "/home/worker/src/teuthology_master/teuthology/task/internal/__init__.py", line 318, in fetch_binaries_for_coredumps
dump_program))
File "/home/worker/src/teuthology_master/teuthology/orchestra/remote.py", line 325, in _sftp_get_file
sftp.get(remote_path, local_path)
File …
```
> task.internal.archive: fix 'Permission denied' error when coredump found

- teuthology/misc.py
- teuthology/orchestra/run.py
in Python3, `a / b` could return a float, and `safe_while()` uses
`itertools.islice()` under the hood, where `stop` should be None or an
integer. so let's use `a // b` instead.
> teuthology: pass integer as "tries" to safe_while()

- bootstrap
This PR is supposed to be different from #1362 only by one commit which makes bootstrap to use py3 by default.
THIS PR CAN BE MERGED AFTER 
i am also tracking the progress in https://trello.com/c/GNCbsxBW/573-python3-migration
> enable py3

- teuthology/task/ceph_ansible.py
Dashboard has been recommended to use by default for downstream builds.
This commit will allow grafana-server role to be added to the inventory file.
Signed-off-by: Vasishta <vashastr@redhat.com>
> Enables grafana-server role to be added to inventory file

- teuthology/lock/cli.py
Convert None type to empty str in sorted key lambda
The usage of .format method is also adjusted for empty
machine type values
Fixes: https://tracker.ceph.com/issues/45105
> lock/cli: fix broken teuthology-lock --summary for py3

- requirements2.txt
- requirements3.txt
python 3.8 needs a newer cffi version. So bump it. Otherwise, calling
"./bootstrap" with python3.8 will fail.
This is also done for the python2 requirements to be in sync.
Fixes: https://tracker.ceph.com/issues/45132
Signed-off-by: Thomas Bechtold <tbechtold@suse.com>
> requirements: Bump cffi version to 1.14.0

- scripts/polarion.py
- setup.py
- teuthology/polarion/__init__.py
- teuthology/polarion/frag_id.py
- teuthology/polarion/util.py
- teuthology/polarion/write.py
Generate unique frag-ids from each job fragments. if `frag_id` is found in one of the fragments, then add the `frag-id` from the YAML. finally, sort it in ascending order. 
This helps in getting the mapping of test cases in Polarion.  
> generate polarion frag-ids

- teuthology/orchestra/daemon/cephadmunit.py
py2: `str(signal.SIGHUP) == "1"`
py3: `str(signal.SIGHUP) == "signal.SIGHUP"`
Fixes: https://tracker.ceph.com/issues/45297
> cephadmunit: Python3 fix: signal.SIGHUP is no longer an int.

- teuthology/orchestra/remote.py
the remote file is created using "ubuntu" user. in ubuntu xenial,
superuser is able to write to that file using tar, it seems that "tar"
starts another process when writing to the dest file specified by "-f",
and that process does not have the privilege for writing that file.
so when we are trying to archive a directory on ubuntu/focal test node,
we have following error:
```
tar (child): /tmp/tmp.vkl0kAtc06: Cannot open: Permission denied
tar (child): Error is not recoverable: exiting now
tar: /tmp/tmp.vkl0kAtc06: Cannot write: Broken pipe
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```
and this is reproduciable with tar 1.30:
```
$ touch /tmp/helloworld
$ mkdir /tmp/foobar
$ sudo tar czf /tmp/helloworld -C /tmp/foobar -- .
tar (child): /tmp/helloworld: Cannot …
```
> teuthology/orchestra/remote.py: write remote file without sudo

- teuthology/orchestra/remote.py
This reverts commit 478bb3f661621c38ac0b9bb21389cc5b225c318d.
Fixes: https://tracker.ceph.com/issues/45255
> Revert "orchestra/remote.py: use ensure_online() helper in run()"

- scripts/queue.py
- teuthology/misc.py
- teuthology/orchestra/console.py
For now fixes only flake8 issues seen in new versions, we could as well get rid of flake8 check with py2 but thats up for another discussion.
As seen during flake8 debug
```
flake8 installed: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021
```
> fix some old flake8 issues

- teuthology/orchestra/console.py
otherwise we could have
```
File "<string>", line 1, in <module>
NameError: name 'file' is not defined
```
Fixes: https://tracker.ceph.com/issues/45512
> teuthology/orchestra: open log file in Python3 way

- scripts/suite.py
- teuthology/suite/__init__.py
- teuthology/suite/run.py
Add --filter-all parameter to suite to make it possible
precise test case selection, since --filter-in and
--filter-out do not allow narrow test case selection
using AND with filter list.
> suite: add filter-all parameter

- teuthology/orchestra/connection.py
Typical connection errors would cause a command to fail.
Fixes: https://tracker.ceph.com/issues/45438
> teuthology/orchestra/connection: add retry exceptions

- MANIFEST.in
- docs/INSTALL.rst
This PR removes mention of deleted file `requirements.txt` and
acknowledges the two separate requirements files, `requirements2.txt`
and `requirements3.txt`, for python2 and python3 respectively, in the
following files:
1.` MANIFEST.in`
2. `docs/INSTALL.rst`
I found the mention of `requirements.txt` in `teuthology/openstack/setup-openstack.sh`, but I wasn't entirely sure how to rectify that.
> docs: acknowledge py2 and py3 where requirements.txt is mentioned

- scripts/describe_tests.py
- scripts/suite.py
- teuthology/describe_tests.py
- teuthology/suite/__init__.py
- teuthology/suite/run.py
- teuthology/suite/util.py
- teuthology/test/test_describe_tests.py
Add --summary argument to teuthology-describe-tests for estimating run capacity, printing descriptions, dumping matrix,  yaml fragments.
> teuthology-describe-tests: add --summary command

- teuthology/provision/fog.py
- teuthology/provision/test/test_fog.py
Similar to how provision.cloud.openstack works, wait for a particular
file to be created before considering provisioning to be finished.
Unlike the cloud.openstack module, teuthology doesn't control the entire
process, so to avoid breaking any labs that aren't using a sentinel
file, make the feature optional and default to being inoperative.
> provision.fog: Add optional sentinel file

- teuthology/provision/fog.py
- teuthology/provision/test/test_fog.py
Similar to how provision.cloud.openstack works, wait for a particular
file to be created before considering provisioning to be finished.
Unlike the cloud.openstack module, teuthology doesn't control the entire
process, so to avoid breaking any labs that aren't using a sentinel
file, make the feature optional and default to being inoperative.
(cherry picked from commit 5c66b774517c0f330f23f087b184caa3f9dbd6db)
> backport: fog sentinel

- teuthology/suite/run.py
- teuthology/suite/test/test_run_.py
Only schedule --first-in-suite and --last-in-suite jobs
once per run when --num is provided for a teuthology-suite.
Fixes: https://tracker.ceph.com/issues/45520
> suite: schedule first and last in suite jobs once

- teuthology/run_tasks.py
sys.exc_clear() was removed in Python3, see
https://docs.python.org/3/whatsnew/3.0.html#index-22. so we should not
call it.
> teuthology/run_tasks: do not call sys.exc_clear() for clearing exception

- teuthology/run.py
for redhat testing, we test ceph composes which are generated internally. we don't need to do any package checking so not adding it from init_tasks only if redhat is in config
> run: exclude internal check_packages and buildpackages_prep for redhat

- teuthology/suite/build_matrix.py
- teuthology/suite/test/test_build_matrix.py
Test descriptions have structured representation of yaml
fragments the test config is composed from. Although
having the .yaml extentions in the description looks
redundant and has no use in the code.
It worth to say that no other files except yaml
participate in description composition.
This change removes many '.yaml' sufixes from
descriptions which make it more compact and easy
to read.
> suite/build_matrix: get rid of '.yaml' in descriptions

- docs/README.rst
This commit adds a hyperlink to [Running Integration Tests Using
Teuthology](https://docs.ceph.com/docs/master/dev/developer_guide/running-tests-using-teuth/) in docs/README.rst under the section Test Suites.
Signed-off-by: Shraddha Agrawal <shraddha.agrawal000@gmail.com>
> docs: add docs.ceph.com link in README.rst

- requirements2.txt
- requirements3.txt
- setup.py
podman's /etc/containers/registries.conf is written
in toml. In order to modify it, we need to parse the
config.
(cherry picked from commit 86baa47a507f9c171b6722422aea3011b38d1b25)
I need this to unstuck https://github.com/ceph/ceph/pull/35188
> py2: setup.py: add toml for qa/tasks/cephadm.py

- teuthology/orchestra/console.py
The smithi have really crappy/flaky BMCs.  I occasionally see `'wait for power on' reached maximum tries (5) after waiting for 20.0 seconds` but when I go to check the BMC, it just needed some more time.  So let's give it more time.
> console.py: Wait longer for IPMI timeouts

- bootstrap
python-pip was removed in debian/bullseye and ubuntu/focal, so let's
replace it with python3-pip. and more importantly, for python3 support
we should install python3-pip instead.
Fixes: https://tracker.ceph.com/issues/45384
> bootstrap: s/python-pip/python3-pip/ for python3 on debian derivatives

- teuthology/orchestra/run.py
- teuthology/orchestra/test/test_run.py
backport of #1499
(cherry picked from commit b7649dfd8507a64c2da7cfc387a46841bc55a7fb)
> py2: orchestra/run: py2 fix for copy_and_close

- scripts/suite.py
- teuthology/suite/__init__.py
- teuthology/suite/run.py
- teuthology/suite/test/test_init.py
- teuthology/suite/test/test_run_.py
This change is required to determine which teuthology
branch should be used for scheduling a run for the
given ceph branch.
In order to enable the functionality of this patch we need
submit and merge `qa/.teuthology` to ceph `master` 
with following content:
```
teuthology_branch: master
```
And add to `/etc/teuthology.yaml` on sepia server the line
```
teuthology_branch: py2
```
Obviously, all users have to update their teuthology sandboxes.
As far as other branches
> teuthology-suite: automate -t argument default value

- tox.ini
This fixes a failure to locate `py.test` using python3 on MacOS:
```
py3 runtests: commands[0] | py.test --cov=teuthology --cov-report=term -v teuthology scripts
File "/Users/zack/dev/teuthology/.tox/py3/bin/py.test", line 5, in <module>
from pytest import main
ModuleNotFoundError: No module named 'pytest'
```
> tox: Avoid system site-packages

- teuthology/misc.py
Valgrind v3.14 brought the `--exit-on-first-error` option which causes termination of the process on first encountered error. Although it does nothing for memory leaks, it shouldhelp with pin-pointing e.g. `UninitValue` without imposing the costly `--track-origins=yes`.
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>
> teuthology/misc: Valgrind exits on first detected error.

- teuthology/task/install/adjust-ulimits
For some cephfs test case it will run handreds of threads and with
some mounts in each, we need a larger limit on the number of open
file descriptors.
Fixes: https://tracker.ceph.com/issues/45829
> adjust-ulimits: use a larger numbers for open files

- teuthology/nuke/__init__.py
to silence following warning:
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
> nuke: s/yaml.load/yaml.safe_load/

- teuthology/task/clock.py
Increase timeout because 1 minute is not always enough
to configure ntp.
This is fixing the bug introduced with f054b20
> teuthology/task/clock: increase timeout

- teuthology/task/clock.py
Increase timeout because 1 minute is not always enough
to configure ntp.
(cherry picked from commit a84c87eae280c7c692f8ecc83f5647353834938d)
> py2 backport: teuthology/task/clock: increase timeout

- teuthology/orchestra/opsys.py
- teuthology/suite/util.py
- teuthology/test/test_packaging.py
as we don't build packages for el7 on master anymore. but we do build
packages for nautilus and octopus.
> teuthology/suite: use rhel8 for querying package version

- teuthology/run.py
This addresses issue introduced by PR 1520 commit:
b9fe404403db8f983a402ed64b85a2a292de66af
> run: fix typo after refactor

- docs/INSTALL.rst
- requirements.in
- update-requirements.sh
dependabot adds an entry in generated requirements.txt like
```
-e file:///home/dependabot/dependabot-updater/tmp/dependabot_20200617-72-1n8af4b  # via -r requirements.in
```
this is expected. as dependabot does not read docs/INSTALL.rst, hence
failed to apply `sed '/^-e / d'` to the generated file.
instead of teaching dependabot to read the manual, it's simpler
just ditch requirements.in .
see also #1367
> drop requirements.in

- teuthology/orchestra/daemon/systemd.py
- teuthology/orchestra/test/files/daemon-systemdstate-pid-ps-ef.output
- teuthology/orchestra/test/test_systemd.py
updating proc regex,
- removing unwanted white spaces.
- adding quotes to constitute regex as below.
```
2020-06-18T23:46:14.914 INFO:teuthology.orchestra.run.clara014:> ps -ef | grep "radosgw.*--name.*rgw.clara014.rgw0" | grep -v grep | awk {'print $2'}
2020-06-18T23:46:14.960 INFO:teuthology.orchestra.run.clara014.stdout:25084
2020-06-18T23:46:14.962 INFO:teuthology.orchestra.run.clara014:> sudo systemctl restart ceph-radosgw@rgw.clara014.rgw0
2020-06-18T23:46:15.053 INFO:teuthology.orchestra.run.clara014:> sudo systemctl show ceph-radosgw@rgw.clara014.rgw0 | grep -i state
2020-06-18T23:46:15.133 INFO:teuthology.orchestra.run.clara014.stdout:StateDirectoryMode=0755
2020-06-18T23:46:15.134 INFO:teuthology.orchestra.run.clara014.stdout:LoadState=loaded
2020-06-18T23:46:15.134 …
```
> Fix regex for 'ps -ef' in SystemDState::pid()

- teuthology/results.py
- teuthology/scrape.py
- teuthology/test/test_scrape.py
After the usual run of `teuthology-results`, the scraper script produces a summary of the results and stores it in `scrape.log` inside the `archive-dir` of the results.
- Added the scraper script from https://github.com/jcsp/scrape as `teuthology/scrape.py`.
- Modified the script at line 470 to include printing of the scrape logs.
- Modified `teuthology/results.py` to run the scraper after every result generation and emailing.
Since I don't have access to a paddle database, I did the following to test:
1. Installed the package using `pip install .`.
2. In the site-packages, commented out / filled with dummy data, the lines that required calling the endpoints on the database.
3. Then ran:
```sh
teuthology-results --archive-dir results --name rados --email a@b.com --dry-run --timeout 2
``` …
> Added Results Scraping after a suite is run

- teuthology/orchestra/daemon/cephadmunit.py
The logger is running in background and the output is mixed
with other loggers. Adding a recognizable suffix will
help to distinguish logging threads.
> orchestra/daemon/cephadmunit: add journalctl suffix

- teuthology/schedule.py
Addresses the issue when teuthology run gets stuck with
first_in_suite or laste_in_suite jobs in queued state.
Attention: This change requires both steps, which are not mutually exclusive
1) server teuthology worker restart, otherwise old worker's code will try to
remove reported job from paddles and exit with unexpected exception. 
2) user's teuthology runner environment should be updated to recent code, 
because new workers will not cleanup FIS and LIS jobs and they will remain
in paddles, correspondingly the run will get stuck.
Requires: a34fb6a
Fixes: http://tracker.ceph.com/issues/43291
> schedule: do not report status for first and last in suite jobs

- scripts/reimage.py
- setup.py
- teuthology/provision/pelagos.py
- teuthology/reimage.py
Add teuthology-reimage cli tool to be able to provision nodes using
Fog or Pelagos without locking and unlocking.
This is useful, for example, when someone just locks the node for
development or debugging purposes and do not want to release while
resetting the image, because it can happen that there are no free
nodes available.
> scripts: add reimage cli tool

- teuthology/task/kernel.py
The current code for checking if the running kernel version matches the
most recent kernel version in the repos does not work on opensuse when
"-k distro" is given.
This commit adds an opensuse-specific codepath with a version match
check that works in the opensuse testing environment.
> kernel: add kernel version matching code for opensuse

- teuthology/run_tasks.py
This was probably working fine due to six library which was removed
recently: https://github.com/ceph/teuthology/commit/9f99b9298265be583c350c71de47109bac4bf6f1
Error seen:
```
During handling of the above exception, another exception occurred:
File "/home/worker/src/github.com_ceph_teuthology_master/teuthology/contextutil.py", line 33, in nested
yield vars
File "/home/worker/src/github.com_ceph_teuthology_master/teuthology/task/install/__init__.py", line 612, in task
yield
File "/home/worker/src/github.com_ceph_teuthology_master/teuthology/run_tasks.py", line 151, in run_tasks
if e.message == 'too many values to unpack':
AttributeError: 'ValueError' object has no attribute 'message'
```
Signed-off-by: Shyukri Shyukriev <shshyukriev@suse.com>
> run_tasks.py: Python3 don't have exception.message anymore

- teuthology/__init__.py
After installing teuthology using pip there can be found error messages
in the log when running any command, for example 'teuthology --version':
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Can't get version from git rev-parse Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.
1.0.0
> teuthology: don't use git to define version for released teuthology

- teuthology/suite/test/test_util.py
- teuthology/suite/util.py
This will need to change to Bionic when we stop supporting luminous or must test Octopus.
> suite/util.py: Update Ubuntu default to Xenial

- teuthology/orchestra/remote.py
20s appears too short for some fog operations.
Fixes: https://tracker.ceph.com/issues/46503
> orchestra/remote: increase console timeout

- teuthology/lock/cli.py
This change makes --brief option to display 'up' and 'down' statuses.
Also locked and unlocked is displayed as 'free' and 'locked'.
If the locked_by field is empty then display nothing instead of 'None'.
Fixes: https://tracker.ceph.com/issues/45569
> lock/cli: show up/down status when --brief

- scripts/schedule.py
- scripts/suite.py
- teuthology/schedule.py
- teuthology/suite/run.py
This will allow to see what job config contents can be submitted to beanstalkd by storing them into the separate file in yaml multi-document format.
Having `--queue-backend` option can be later used for queuing the jobs into alternative to beanstalkd service, for example, we can queue jobs to the paddles database directly, or any other.
The yaml file can be easily read and any job config can be taken from it and used with teuthology-run directly to run tests without involving beanstalkd and paddles.
> teuthology-suite: allow dump job configs to a file instead of beanstalkd

- teuthology/orchestra/daemon/systemd.py
- Fix python3 comparison issue.
- Fix issue with the newline character.
http://pastebin.test.redhat.com/894147
```
1. The system-ctl status command response has newline character at the end of the output, which results empty string after split.
the issue occurs when empty string is given to re.match. so need to strip the command response before split.
2020-08-17T03:07:39.329 INFO:teuthology.orchestra.run.magna102:> sudo systemctl status ceph-mgr@magna102 | grep 'Main.*code=exited'
2020-08-17T03:07:39.376 INFO:teuthology.orchestra.run.magna102.stdout: Main PID: 73508 (code=exited, status=0/SUCCESS)
2020-08-17T03:07:39.377 ERROR:tasks.mixed_system_tests.system:[ CEPH.MGR ] : Daemon System tests - FAILED
2020-08-17T03:07:39.377 …
```
> fix py3 issue in pid method

- teuthology/kill.py
In some circumstances teuthology-kill does not unlock the nodes
if it is used to kill just a single job from a run, for example,
while a job in the middle of locking many targets the job_info
does not include targets yet, corresponding if someone kills
the job in the middles, the targets remains in locked state.
This commit address the issue.
> kill: find targets for killing a job

- scripts/suite.py
- teuthology/suite/run.py
Check if the passed testing priority is according to the range mentioned in
developer guide[1]. This patch also adds '--force-priority' flag which allows to skip
the priority check.
[1] https://docs.ceph.com/docs/master/dev/developer_guide/tests-integration-tests/#testing-priority
Signed-off-by: Varsha Rao <varao@redhat.com>
> teuthology-suite: Check the priority of jobs to be run

- teuthology/orchestra/remote.py
- teuthology/task/install/__init__.py
Every teuthology job cleans up its package install after completion.
This was necessary cleanup when we didn't reimage boxes before the use
of FOG as we wanted a "clean" slate for the next job to acquire the
machine. Now this is just unnecessary work which takes up valuable
machine time. For one job I looked at, this takes about 2 minutes.
We should still test that there are no unexpected issues with removing
the packages but this can be delegated to a small subset of smoke tests.
That will be posted in another PR to ceph.git.
> task/install: skip package removal by default

- teuthology/run_tasks.py
Correct the url generated, and include additional tags for filtering by suite/machine_type/os.
> run_tasks: improve sentry reporting

- teuthology/orchestra/remote.py
- teuthology/task/ansible.py
- teuthology/task/ssh_keys.py
This PR addresses:
```
2020-09-05T10:00:32.003 INFO:teuthology.task.ssh_keys:pushing keys to smithi086.front.sepia.ceph.com for ubuntu
2020-09-05T10:00:32.003 INFO:teuthology.orchestra.run.smithi086:> rm -f -- /home/ubuntu/.ssh/id_rsa
2020-09-05T10:00:32.046 INFO:teuthology.orchestra.run.smithi086:> touch /home/ubuntu/.ssh/id_rsa && chmod 500 -- /home/ubuntu/.ssh/id_rsa
2020-09-05T10:00:32.095 INFO:teuthology.orchestra.run.smithi086:> set -ex
2020-09-05T10:00:32.096 INFO:teuthology.orchestra.run.smithi086:> dd of=/home/ubuntu/.ssh/id_rsa conv=notrunc oflag=append
2020-09-05T10:00:32.140 INFO:teuthology.orchestra.run.smithi086.stderr:+ dd of=/home/ubuntu/.ssh/id_rsa conv=notrunc oflag=append
2020-09-05T10:00:32.142 INFO:teuthology.orchestra.run.smithi086.stderr:dd: failed to open …
```
> Use remote.write_file instead of misc.create_file

- teuthology/orchestra/remote.py
- teuthology/task/ansible.py
Raise FileNotFoundError exception if the file passed to
remote.read_file was not found.
> orchestra/remote: raise FileNotFoundError in read_file

- bootstrap
follow the suggestion from pip
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
> bootstrap: use pip --use-feature=2020-resolver

- bootstrap
pip might be too old so the --use-feature flag is not available. That
leads to:
$ ./bootstrap
Removing old virtualenv because it uses system site-packages
created virtual environment CPython3.8.5.final.0-64 in 173ms
creator CPython3Posix(dest=/home/tom/devel/ceph/teuthology/virtualenv, clear=False, global=False)
seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/tom/.local/share/virtualenv)
added seed packages: pip==20.1.1, setuptools==50.3.0, wheel==0.35.1
activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Usage:
pip install [options] <requirement specifier> [package-index-options] ...
pip install [options] -r <requirements file> [package-index-options] ...
pip install …
> bootstrap: Do not use --use-feature=2020-resolver for pip upgrade

- teuthology/task/install/rpm.py
When installing some packages, if the mirror server failed with
503 code, which means the mirror server temporarily not available,
we should retry it later. But the yum tool just skips it and
retries other mirrors, which may not contain them.
For the cephfs suites, there maybe will fire the many test cases
at the same time, and for each test case it may fire several nodes
to install tens of packages at the same time. This may cause the
mirror server overloaded.
We need one safe method to retry it.
Fixes: https://tracker.ceph.com/issues/47166
> rpm: retry installing the package if the mirror server is busy

- teuthology/task/install/rpm.py
yum is an alias for dnf on modern RHEL-like systems but it's not
100% compatible. The "install" command does not upgrade packages
unless you give it a specific version to install. Additionally,
the code was incorrectly inserting two blank arguments that resulted
in "yum install" failing.
Signed-off-by: Jason Dillaman <dillaman@redhat.com>
> task/install/rpm: fix issued with upgrading packages under DNF

- teuthology/task/clock.py
- Updated ntp, chrony configuration file based on the RHEL version.
http://pulpito.ceph.redhat.com/sunnagar-2020-10-22_05:33:14-smoke:ceph-ansible-master-distro-basic-psi/
> updated ntp and chrony config files based on rhel-version

- teuthology/misc.py
lsb_release -is identifies CentOS 8 Stream as CentOSStream.
Teuthology should recognize this as 'rpm'.
Signed-off-by: Marcus Watts <mwatts@redhat.com>
> misc: CentOSStream => rpm

- teuthology/task/install/deb.py
- teuthology/task/kernel.py
Fixes: https://tracker.ceph.com/issues/46878
> task/install/deb: retry installing the package if resource temporarily unavailable

- teuthology/packaging.py
- teuthology/suite/util.py
The package repo might be done, but the build must be totally
complete for the container to be present.  For a specific build
(in global variables, for now), demand that the build be complete
before claiming packages exist.  This allows suite jobs to
fail or --newest to continue searching when the container isn't
done.
Signed-off-by: Dan Mick <dmick@redhat.com>
> Check shaman not only for repo but for build complete

- teuthology/orchestra/connection.py
Out of the box, centos 8 ssh daemon makes this file,
/etc/ssh/ssh_host_ecdsa_key.pub
containing a key of type "ecdsa-sha2-nistp256", which was
not recognized by the existing teuthology logic.
Use logic in paramiko.hostkeys to recognize the new key types.
Signed-off-by: Marcus Watts <mwatts@redhat.com>
> orchestra/connection: accept ecdsa (and future) host key types.

- docs/detailed_test_config.rst
- teuthology/misc.py
- teuthology/task/internal/__init__.py
* misc: add an optional write_to argument to misc.pull_directory()
so the caller can optionally specify the function to write
to local file.
* task/internal: add a global option "log-compress-min-size" which
defaults to "128MB". if the size of a file pulled from remote
host is greater or equal to the specified size, it will be
compressed with gzip with the extension of ".gz" before
stored in the archive directory.
> task.internal.archive: gzip archived file size > 128MB

- docs/detailed_test_config.rst
- teuthology/packaging.py
There has some cases we need to specify the particalur option to
override the one parsed from the remote os.
> packaging: try noarch repo if arch repo doesn't exist

- teuthology/orchestra/remote.py
- teuthology/orchestra/run.py
Applied changes:
- Add quiet option to remote.run and subsidiary function calls
- Logging commands now directed to DEBUG instead of INFO logger
This is usefull when we want suppress logs for some kind of commmands like
reading binary files or logging useless data to stdout/stderr as well as
dumping some vulnarable information.
> orchestra: introduce quiet mode for remote.run

- teuthology/orchestra/connection.py
The Traceback clutters the log and messes up greps for Tracebacks.
> orchestra: squelch Traceback for expected auth failures

- teuthology/exceptions.py
Commands like those running workunits include the ceph sha1 being
tested, so they're not useful for grouping. This also lets us group
together other tests if we like, for example to map tests with small
differences in configuration to the same fingerprint for sentry.
Also use the plain command, it's already a string at this point
so there's no reason to add spaces between its characters.
> exceptions: only use one of label or command for fingerprint

- teuthology/misc.py
This commit is a follow-up to a98eb3e1405c8ca8f6933eb0356c03955e4e2e83 where Valgrind has been configured to exit on first-seen error as it was (wrongly!) assumed that all components are green when it comes to the Valgrind verification.
This assumption turned out to be broken for RGW which got a few issues over the course as a result of having the Valgrind checks knocked out as a side effect of the python3 transition \[1\]. In the consequence, multiple problems accumulated and introducing a mechanism to disable the early exit to e.g. develop a list of these issues looks desirable.
\[1\]: https://github.com/ceph/teuthology/pull/1503#issuecomment-762837504
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>
> teuthology/misc: make the Valgrind's early exit configurable.

- teuthology/task/install/redhat.py
script modified to remove packages based on OS in the cleanup task.While uninstalling packages, both rpm and deb packages are getting first and in the next step checking the OS name and removing the packages.
As part of fix first checking the OS name after that getting the appropriate packages to remove.
> task/install/redhat: Removing packages based on OS in cleanup task

- teuthology/dispatcher/supervisor.py
This is the same default as reimaging uses,
though it's not too important in the supervisor.
> dispatcher: allow empty os_type for fake config

- teuthology/dispatcher/__init__.py
- teuthology/repo_utils.py
- teuthology/worker.py
If the commit is behind head, we need more history to clone it.
In the future we may be able to configure a git mirror to allow fetching an exact commit to speed this up.
For now, just clone the whole branch, and properly handle the error if the commit is not found.
> dispatcher/repo_utils: handle missing commits better

- teuthology/dispatcher/supervisor.py
If we can't connect to the machines anymore, we still need to clean
up.
> dispatcher/supervisor: always unlock machines and save status

- teuthology/dispatcher/supervisor.py
It would be great to have an extension for easy log identification.
> dispatcher: add .log extension for supervisor log

- teuthology/suite/run.py
Don't let users guess the job count.
> teuthology-suite: Add job count to priority error msg.

- scripts/nuke.py
- teuthology/dispatcher/supervisor.py
- teuthology/kill.py
- teuthology/nuke/__init__.py
Include failure messages so we can tell why jobs are marked dead. Also fix a hang in cleaning up when we hit the max jobs timeout due to logs continuing to grow - kill the processes creating them before collecting the logs.
> supervisor: improve error handling for dead jobs

- teuthology/ls.py
- no error when teuthology.log is missing (provisioning)
- leave off pid
> ls: nicer ls output

- teuthology/nuke/__init__.py
nuke() is called outside of the cli with a ctx that does not include
all the cli args. Use a default parameter for the functions instead of ctx.
> nuke: only use keep_logs from the cli

- teuthology/nuke/__init__.py
- teuthology/test/test_nuke.py
This is causing errors in many jobs now due to lack of ctx.no_reboot in internal nuke callers.
> nuke: fix no_reboot only being present in the cli and add unit tests

- teuthology/suite/placeholder.py
This was increased for some mgr issues in
044384be450a557f56a2b39bf7d0e71e69d45cd3, but isn't helping much now
and is filling up disks for long-running tests.
> suite: lower debug_ms for osd back to 1

- teuthology/orchestra/daemon/cephadmunit.py
The osd thrashing is sending lots of signals (sighup) and can easily race with
a daemon shutting down entirely.
This makes us match the behavior of the original state.py signal() method.
> orchestra/daemon/cephadmunit: ignore exception when sending signal

- teuthology/orchestra/daemon/state.py
The cephadmunit takes fsid.  The old state.py handler needs to be able to take it without breaking later.  This came up due to https://github.com/ceph/ceph/pull/39304
> orchestra/daemon/state: do not pass fsid property to run() later

- teuthology/task/selinux.py
['type=AVC msg=audit(1614438637.552:5615): avc: denied { read } for pid=876 comm="sssd" name="resolv.conf" dev="sda1" ino=265261 scontext=system_u:system_r:sssd_t:s0 tcontext=unconfined_u:object_r:admin_home_t:s0 tclass=file permissive=1']
(currently seen on rhel 8.3)
> selinux: ignore issues with sssd

- teuthology/task/internal/__init__.py
This is related to dnsmasq.  When installing hte kubic podman 3.0.1
packages,
Running scriptlet: dnsmasq-2.79-13.el8_3.1.x86_64                                                                                                                                                                                                                                                                                                                                                                                                                            14/16
/var/tmp/rpm-tmp.6MFp00: line 5:  9079 Segmentation fault      (core dumped) systemd-sysusers -  &> /dev/null <<SYSTEMD_INLINE_EOF
u dnsmasq - "Dnsmasq DHCP and DNS server" /var/lib/dnsmasq
SYSTEMD_INLINE_EOF
Installing       : …
> task/internal: ignore systemd-sysusers core file

- teuthology/nuke/__init__.py
This ensures jobs that time out can still have their logs gathered.
> nuke: don't power-off machines when not rebooting

- teuthology/nuke/__init__.py
This reverts commit c48eb744081d22bc82d7d099d4edb67ae02551e0, reversing
changes made to b96569170f15eae4604f361990ea65737b28dff1.
This is causing log gzipping to fail because the logs already exist as .gz files.
My guess is that the logs are left over from previous, but I'm not sure how
that would happen.
In any case, the merge of this PR corresponds exactly to when we started seeing
the log gzip failures.
> Revert "Merge pull request #1631 from jdurgin/wip-nuke-poweroff"

- teuthology/misc.py
this specifically is for interactive on error mode, where we usually do
not specify archive_path, which fails without this check
Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>
> check ctx.archive is present or not in yaml config

- teuthology/lock/query.py
Retry paddles requests, and for get_status() return an empty dict
rather than None so callers behave.
get_status() failing in particular has caused the dispatcher and jobs
to fail several times over the past few weeks. With this change, we
should be able to run multiple paddles workers again, since all the
common callers will retry on error.
> lock/query: make robust against paddles errors

- teuthology/orchestra/remote.py
Move methods that operate on a remote machine without depending on
another remote machine from orchestra.remote.Remote to a different class
in same module. This enables vstart_runner to reuse these methods.
Related PR: https://github.com/ceph/ceph/pull/37667
> remote: move non-file transfer methods from Remote

- bootstrap
this reverts f2607ee8ce149f2951c5fd62c259fc4fa3ddcb5a
to silence the warning from pip:
WARNING: --use-feature=2020-resolver no longer has any effect, since it
is now the default dependency resolver in pip. This will become an error
in pip 21.0.
> bootstrap: do not pass '--use-feature=2020-resolver' to pip

- teuthology/kill.py
`<kyr> looks like because bootstrapping failed, the teuthology-kill was not able to find machine_type and owner from the run archive directory, the directory has been created but no actual job started somehow`
> kill.py: Allow deleting runs where bootstrap is failing

- teuthology/task/internal/syslog.py
Avoid the problem of tests failing by not checking for magic strings in misc.log--these were intended for kern.log checks.
It is still a bit of a mystery why there is a difference in behavior when ceph daemons log to stdout/stderr (output *never* makes its way to misc.log) vs ceph daemons logging to the journald socket (https://github.com/ceph/ceph/pull/40640) (logs *sometimes* end up in misc.log).
> task/internal/syslog: avoid failing runs when ceph daemon logs go to syslog misc.log

- teuthology/run.py
- teuthology/task/internal/__init__.py
- teuthology/task/internal/redhat.py
- Setup container registry login task is essential to access Ceph monitoring images from Red Hat registry source.
**Test result:**
- setup_container_registry attribute is provided in config with correct registry name.
http://magna002.ceph.redhat.com/ceph-qe-logs/Sunil/test_container-login-1405/teuthology.log
- setup_container_registry attribute is not provided in config.
http://magna002.ceph.redhat.com/ceph-qe-logs/Sunil/test_container-login-1405-02/teuthology.log
- setup_container_registry attribute is provided in config with incorrect registry name.
http://magna002.ceph.redhat.com/ceph-qe-logs/Sunil/test_container-login-1405-03/teuthology.log
> task/internal/redhat.py: added container tool login support

- teuthology/packaging.py
Without this restriction a failed arm64 build will result in the
container build reporting failure.
Fixes: https://tracker.ceph.com/issues/50922
> Restrict build_complete check to x86_64

- scripts/suite.py
- teuthology/suite/__init__.py
right now the default_machine_type fallback is set to None via some internal
mangaling, this makes users always have to pass --machine_type which mostly we
prefer to smithi's . Hence, making it a default unless otherwise, should be
helpful for users.
Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>
> teuthology-suite: add default machine type(smithi)

- teuthology/nuke/__init__.py
If the process has been kill -STOPped, then we'll unlock the machines, but
the process will stick around and we'll try to nuke it again later,
zapping the machines after they're being used by some other job, leading
to failures.  (Usually this manifests as an error when the other job stops
where it has trouble gzipping the logs.)
> nuke: kill -9 the teuthology process

- teuthology/orchestra/opsys.py
- teuthology/test/test_get_distro_version.py
- teuthology/test/test_packaging.py
- Ubuntu (20.04) Focal should be the default now.  It's the latest and we target it for octopus, pacific, and master.
- RHEL and CentOS 8.4 have been available for weeks
- In the process of adding support for CentOS 9 Stream.  May as well add it here now.
> Update distro maps

- scripts/suite.py
- teuthology/suite/run.py
Add check_num_jobs() to prevent users from accidentally scheduling too many jobs, like
in rfriedma-2021-06-26_19:32:15-rados-wip-ronenf-scrubs-config-distro-basic-smithi.
JOBS_TO_SCHEDULE_THRESHOLD, set to 500 (most runs have fewer jobs than this),
will disallow users from scheduling more than 500 jobs. Users can schedule
more than 500 jobs by disabling this check using the --disable-num-jobs-check flag.
Testing:
- Default behavior
```
2021-07-09 21:52:27,306.306 INFO:teuthology.suite.util:Memo: ./virtualenv/bin/teuthology-schedule --name nojha-2021-07-09_21:52:08-rados-wip-51354-3-distro-basic-smithi --worker smithi --dry-run --priority 60 -v --first-in-suite --subset 1/5000 --seed 7987
File "./virtualenv/bin/teuthology-suite", line 11, in <module> …
```
> teuthology/suite/run.py, scripts/suite.py: disallow scheduling too many jobs

- docs/siteconfig.rst
- scripts/suite.py
- teuthology/config.py
- teuthology/suite/__init__.py
- teuthology/suite/run.py
Rename --disable-num-jobs-check to --job-threshold:
- for shorter recallable name;
- to allow change threshold value via parameter;
- to allow define default threshold value in teuthology config.
Use `--job-threshold 0` to disable job threshold check.
> suite: rename disable-num-jobs-check to job-threshold

- .readthedocs.yml
to address the missing document of
https://docs.ceph.com/projects/teuthology/en/latest/commands/list.html,
they require that teuthology cli tools accessible when building sphinx
document.
> .readthedocs: add .readthedocs.yml

- teuthology/task/ceph_ansible.py
Upgrading ansible is problematic as it conflicts with the installed
package on Ubuntu 20.04 so don't try to use system packages.
Add LANG environment variable to 'pip install ansible' command to work
around pip failing due to file names in ansible package with exotic
characters.
Fixes: https://tracker.ceph.com/issues/51856
> ceph_ansible: Remove --system-site-packages

- teuthology/task/internal/redhat.py
use rh  stage creds from config file
> task/internal/redhat: remove rh stage creds

- bootstrap
- tox.ini
Python3 uses locale.getdefaultlocale() to get the locale, which is used
to determine the encoding of filenames. 
see https://docs.python.org/3/library/locale.html
there is chance that the
specified locale is not capable of decoding the filenames encoded in
non-latin-1 characters, in that case, pip just fails to decompress that
file, like:
```
me/jenkins-build/build/workspace/teuthology-pull-requests/.tox/flake8/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
return self._prepare_linked_requirement(req, parallel_builds)
File "/home/jenkins-build/build/workspace/teuthology-pull-requests/.tox/flake8/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 550, in _prepare_linked_requirement
local_file = unpack_url(
File …
```
> tox.ini: set a UTF-8 locale for decoding non-latin chars

- teuthology/test/test_worker.py
When home directory contains .teuthology.yaml the test_prep_job
can pick unexpected values, like teuthology_path which makes
tests fail.
This fix overrides teuthology config to avoid unexpected behaviour.
> test/test_worker: fix test_prep_job teuth_config mocking

- teuthology/orchestra/test/test_cluster.py
- teuthology/orchestra/test/test_connection.py
- tox.ini
> tests: Drop fudge

- teuthology/lock/ops.py
In unlock_one, we currently have a retry mechanism that is only triggered on a particular exception. With this change, we retry the request to unlock no matter what the cause of failure.
Fixes: https://tracker.ceph.com/issues/50921
Signed-off-by: Aishwarya Mathuria <amathuri@redhat.com>
> lock/ops.py: Fix retry mechanism for unlock_one

- teuthology/report.py
the function `try_push_job_info()` is not
updating `job_info` dictionary properly since
we want to update `job_info` with `extra_info`,
however, in lines 498 and 499 we are assigning
`job_info` to a copy of `extra_info` and updating
`job_info` with `job_config` which is incorrect.
Instead, we should assign `job_info` with
a copy of `job_config` and update `job_info` with
`extra_info`
> Fix dictionary update in try_push_job_info()

- teuthology/task/internal/__init__.py
Debugging this failure:
```
File "/home/teuthworker/src/git.ceph.com_git_teuthology_c56135d151713269e811ede3163c9743c2e269de/teuthology/run_tasks.py", line 176, in run_tasks
suppress = manager.__exit__(*exc_info)
File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
next(self.gen)
File "/home/teuthworker/src/git.ceph.com_git_teuthology_c56135d151713269e811ede3163c9743c2e269de/teuthology/task/internal/__init__.py", line 398, in archive
fetch_binaries_for_coredumps(path, rem)
File "/home/teuthworker/src/git.ceph.com_git_teuthology_c56135d151713269e811ede3163c9743c2e269de/teuthology/task/internal/__init__.py", line 320, in fetch_binaries_for_coredumps
dump_program = dump_out.split("from '")[1].split(' ')[0]
IndexError: list index out of range
``` …
> task/internal/__init__: print core file output before splitting

- requirements.txt
- teuthology/test/test_misc.py
See commit messages for details.  Pytest 6.2.5 exposed the use of asctime, which may not be present on a LogRecord.  Luckily it's much simpler to use crtime, and then we can update pytest.
> Stop using LogRecord.asctime (not stable); move to pytest 6.2.5

- teuthology/suite/matrix.py
Give folks at least some hint about where things might
be broken:
```
AssertionError: Sum requires non-empty _submats: 0-distro
```
Signed-off-by: Sebastian Wagner <sewagner@redhat.com>
> teuthology/suite/matrix.py: Add item to assert msg

- teuthology/beanstalk.py
There is a deprecation error when beanstalk parser called:
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe
```
Since beanstalkc3 does not want to apply a fix for that
we can override yaml parser to suppress the error message
from the log.
Fixes: https://tracker.ceph.com/issues/44225
> teuthology/beanstalk: workaround yaml load deprecation

- teuthology/misc.py
We want to see output of commands with nice formatting,
for example when there are yaml data
> misc/sh: do not strip output from left

- teuthology/dispatcher/supervisor.py
- teuthology/dispatcher/test/test_reimage_error_mark_machine_down.py
Introduce a new feature where we mark the machine down
if we found more than 10 consecutive reimaging failure
when performing teuthology tests.
Signed-off-by: Kamoltat <ksirivad@redhat.com>
> dispatcher/supervisor: Mark machine down if reimage error >= 10x

- teuthology/task/kernel.py
> teuthology/tasks/kernel: switch firmware branch name

- teuthology/task/ansible.py
- teuthology/test/task/test_ansible.py
- teuthology/test/task/test_ceph_ansible.py
Currently ansible tasks are logging to
teuthology.log. We want to separate this to
it's own log files for better readability.
Signed-off-by: Kamoltat Sirivadhna <ksirivad@redhat.com>
> task/ansible: move ansible logs to ansible.log

- teuthology/dispatcher/supervisor.py
- teuthology/kill.py
- teuthology/lock/ops.py
- teuthology/misc.py
- teuthology/nuke/actions.py
- teuthology/orchestra/daemon/cephadmunit.py
- teuthology/orchestra/daemon/state.py
- teuthology/orchestra/daemon/systemd.py
- teuthology/provision/cloud/openstack.py
- teuthology/provision/downburst.py
- teuthology/provision/fog.py
- teuthology/provision/openstack.py
- teuthology/provision/pelagos.py
- teuthology/repo_utils.py
- teuthology/report.py
- teuthology/results.py
- teuthology/suite/__init__.py
- teuthology/suite/run.py
- teuthology/suite/util.py
- teuthology/task/install/__init__.py
- teuthology/task/kernel.py
- teuthology/task/pcp.py
- teuthology/worker.py
Avoiding this warning:
/home/runner/work/teuthology/teuthology/teuthology/task/install/__init__.py:285: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
> teuthology: convert deprecated method name

- teuthology/kill.py
When calling kill for a run which is still in beanstalkd
queue there is no job directories created in archive
and there is no way to find out which machine type to use
the teuthology-kill reports that you must manually provide
machine type for the run, which is often borring and quite
inconvenient.
Instead of torturing user to recall a tube for the run name
we just ask paddles if it has anything logged and use the
machine type from what we receive from it.
> kill: get machine type from paddles for the run

- docs/docker-compose/README.md
Added instructions that will help users
set up ansible inventory files in after they
built their local teuthology container. This
part is needed when ansible tasks are executed
when jobs are running.
Signed-off-by: Kamoltat <ksirivad@redhat.com>
> docs/docker-compose: add ansible inventory to README

- teuthology/orchestra/cluster.py
- teuthology/orchestra/test/test_cluster.py
Make cluster.run able to execute a command in parallel on all
nodes and wait for completion.
In order to run a command in parallel on all nodes of the
cluster, instead of combination:
```
run.wait(cluster.run(wait=False, args=...))
```
this patch makes it possible to do the same just by:
```
cluster.run(parallel=True, args=...)
```
the `wait` arguments defaults to True in this case.
Also, the behavior of the method is not changed
when `wait` is set to False (like in the first example),
so it is supposed to be backward compatible.
> orchestra/cluster: make run parallel and wait

- teuthology/task/ansible.py
We only want output generated by ansible itself in ansible.log
> task.ansible: Don't direct task's logging to file

- .github/workflows/ci.yml
If we do this, we can drop the Jenkins job. The openstack tests are
currently all skipped, so we can just leave them out for now.
> github actions: Run docs build during CI

- teuthology/run.py
- teuthology/task/ansible.py
- teuthology/test/test_run.py
Fetching tasks automatically did not work for non-scheduled jobs because it never actually imported them, like scheduled jobs (which have suite_path set) do a few lines earlier.
> fixes for running non-scheduled jobs 

- docs/docker-compose/docker-compose.yml
- docs/docker-compose/start.sh
paddles use quay.io
docker-compose.yaml: teuthology depends on healthy
paddles rather pulpito
Signed-off-by: Kamoltat Sirivadhna <ksirivad@redhat.com>
> docs/docker-compose: paddles use quay.io image

- teuthology/config.py
MutableMapping has been moved from collections to collections.abc.
> config: import MuableMapping based on python version

- teuthology/task/ceph_ansible.py
... in get_host_vars(). This had broken unit tests when a top-level
"ceph_ansible" key is present in the teuthology config.
> task/ceph_ansible: Fix attribute handling

- teuthology/orchestra/remote.py
In run method if a reconnect required there is a remote.reconnect
method called which is supposed to return True or False.
On failure it is the best to raise an exception early,
to make it clear what was the original error instead of
waiting until somewhere later teuthology fails with
some undeclared variables.
> orchestra/remote: throw exception on reconnect failed

- bootstrap
- docs/docker-compose/docker-compose.yml
- docs/docker-compose/start.sh
- docs/docker-compose/teuthology/Dockerfile
- docs/docker-compose/teuthology/teuthology.sh
- teuthology/exceptions.py
- teuthology/repo_utils.py
- teuthology/suite/run.py
- teuthology/test/test_repo_utils.py
Previously, we'd invalidate the build cache any time the source tree changed; that meant reinstalling every python dependency. This change splits dependency installation from the rest of the bootstrap process, so that we can avoid reinstalling deps unless `requirements.txt` or `bootstrap` changes.
> docker-compose: Speed incremental builds by caching dependencies

- teuthology/report.py
Most runs don't use --no-nested-subset and for those that used --subset,
the if conditions would correctly pickup "seed" (when it mattered).
However, when --subset was not specified in the original run, the "seed"
was not correctly picked up. Therefore, the result of inserting the "if
no_nested_subset is None:" before the "elif seed is None:" caused it to
never read the seed for most folks teuthology runs.
> qa: correct line processing logic

- teuthology/suite/__init__.py
teuthology-watch fails when run is complete and jobs' description
gets None value
Example:
2022-06-07 16:41:22,538.538 INFO:teuthology.suite:waiting for the run runner-2022-06-07_16:41:04-suse:tier0-ses7p-none-default-ecp to complete
2022-06-07 16:41:22,539.539 DEBUG:teuthology.suite:the list of unfinished jobs will be displayed every 5.0 minutes
2022-06-07 16:46:22,599.599 DEBUG:teuthology.suite:wait for jobs ['654']
2022-06-07 16:51:22,633.633 DEBUG:teuthology.suite:wait for jobs ['654']
2022-06-07 16:51:22,686.686 INFO:teuthology.suite:wait is done
File "/home/runner/src/teuthology_master/virtualenv/bin/teuthology-wait", line 33, in <module>
sys.exit(load_entry_point('teuthology', 'console_scripts', 'teuthology-wait')())
File …
> suite: fix type error when description is none

- teuthology/suite/run.py
Log total number of jobs scheduled, taking `--num` into consideration.
For a command with `--num 5`:
Previously -
```
2022-07-03 09:56:12,974.974 INFO:teuthology.suite.run:Suite smoke in /home/vallariag/src/github.com_vallariag_ceph-c_vallariag-testing-1768/qa/suites/smoke scheduled 2 jobs.
2022-07-03 09:56:12,974.974 INFO:teuthology.suite.run:22/24 jobs were filtered out.
```
Changed to -
```
2022-07-03 09:56:12,974.974 INFO:teuthology.suite.run:Suite smoke in /home/vallariag/src/github.com_vallariag_ceph-c_vallariag-testing-1768/qa/suites/smoke scheduled 2 jobs.
2022-07-03 09:56:12,974.974 INFO:teuthology.suite.run:22/24 jobs were filtered out.
2022-07-03 09:56:12,975.975 INFO:teuthology.suite.run:Scheduled 10 jobs in total.
```
Signed-off-by: Vallari Agrawal <val.agl002@gmail.com>
> suite/run: Log total number of jobs scheduled

- teuthology/suite/__init__.py
- teuthology/suite/run.py
- teuthology/suite/test/test_init.py
- teuthology/suite/test/test_run_.py
- teuthology/suite/test/test_util.py
- teuthology/suite/util.py
Do not send emails with `--dry-run` on schedule failures. 
Signed-off-by: Vallari Agrawal <val.agl002@gmail.com>
> suite: Do not send emails with --dry-run at schedule_fail

- teuthology/misc.py
It appears to be unnecessary, and causes Ubuntu 22.04 to respond with
zero keys.
> misc._ssh_keyscan(): Drop '-t rsa'

- teuthology/orchestra/opsys.py
- teuthology/test/test_get_distro_version.py
> opsys.py: Make Ubuntu 22.04 default

- bootstrap
Currently, we cannot do bootstrap for CentOSStream
so we are adding support for that.
Signed-off-by: Kamoltat Sirivadhna <ksirivad@redhat.com>
> boostrap: Add support for CentOSStream

- teuthology/task/internal/__init__.py
- teuthology/task/tests/test_fetch_coredumps.py
Added a case where if the core is compressed, then
we will try to open it as gzip and read the content
inside.
Also, add try and except when we are parsing
through the content to prevent the program from
crashing.
Create a unit test to test the function,
`fetch_binaries_for_coredumps()`
Fixes: https://tracker.ceph.com/issues/53206
Signed-off-by: Kamoltat <ksirivad@redhat.com>
> task/internal: open gzip file if core is compressed

- scripts/lock.py
The `--list` and `--brief` arguments are exclusive.
```
teuthology-lock: error: argument --brief: not allowed with argument --list
```
> lock: remove --list --brief example

- teuthology/provision/fog.py
- teuthology/provision/test/test_fog.py
Improve the error message when the user specifies a missing OS version for a machine type.
Old error message:
```
RuntimeError: Could not find an image for rhel 7.9
```
New error message:
```
RuntimeError: Fog has no cali_rhel_7.9 image. Available cali images: ['cali_rhel_8.6', 'cali_rhel_9.0']
```
> fog: suggest image names on error

- teuthology/orchestra/remote.py
Add a method mount() that checks if the given path is mounted or
unmounted without using "mount" of "findmnt" commands.
> orchestra/remote: add method to check if given path is mounted

- teuthology/provision/fog.py
Make sure the user knows of potential configuration problems, etc.
Fixes: https://tracker.ceph.com/issues/58015
Signed-off-by: Dan Mick <dmick@redhat.com>
> provision/fog.py: log exceptions while looping for ssh

- bootstrap
the package name isn't necessarily the name of the dependency
Signed-off-by: Dan Mick <dmick@redhat.com>
> bootstrap: rpm systems: use --whatprovides to test for package presence

- teuthology/suite/run.py
- teuthology/suite/test/test_run_.py
- teuthology/suite/test/test_util.py
- teuthology/suite/util.py
For a 'newest' value of N, we were calling find_git_parent N times. find_git_parent was invoking githelper's 'refresh' endpoint each time, which in my testing took 20-30 seconds. So, for a sha1 that needed 20 backtracks, I was seeing teuthology-suite take eight minutes to complete. With this change, it took 30 seconds for the same teuthology-suite invocation.
We were also not including the trailing slash on the 'refresh' endpoint, resulting in a 308 redirect each time - doubling the request count. That's fixed as well.
> suite: Speed up 'newest' feature

- bootstrap
`python3-devel` is only provided by `python36-devel` for whatever reason, and 3.6 is not new enough.
> bootstrap: Correct python3 package names for EL8/9

- teuthology/task/selinux.py
> task/selinux: Fix regressed grepping of audit logs

- teuthology/misc.py
... instead of lsb_release, as newer distros don't ship it.
Fixes: #58491
> misc.get_system_type: Use Remote.os

- docs/docker-compose/docker-compose.yml
PostgreSQL v15  has a notable change that revokes the CREATE permission from users except a database owner. So we can not execute paddles using it. As a workaround, I specify PostgreSQL version.
ref: https://www.postgresql.org/about/news/postgresql-15-released-2526/
Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>
> Specify PostgreSQL v14 to avoid permission errors.

- teuthology/scrape.py
SequenceMatcher can't get NoneType when comparing 2 dead jobs, adding check and compare for those jobs.
Fixes: https://tracker.ceph.com/issues/58264
Signed-off-by: Nitzan Mordechai <nmordec@redhat.com>
> scrapy: comparing dead job skip typeNone

- docs/siteconfig.rst
- teuthology/config.py
- teuthology/orchestra/connection.py
On systems where SSH is configured using ~/.ssh/config.d/, we don't have a great way of locating and processing the full configuration, so we might not find the correct key to use. Allow the user to specify one key to use for all test nodes if they wish.
> orchestra.connection: Look for 'ssh_key' in config

- docs/exporter.rst
- docs/index.rst
- teuthology/dispatcher/__init__.py
- teuthology/dispatcher/supervisor.py
- teuthology/exporter.py
- teuthology/kill.py
- teuthology/repo_utils.py
- teuthology/report.py
- teuthology/run_tasks.py
- teuthology/task/internal/__init__.py
- teuthology/task/kernel.py
This adds data for time spent while:
* locking nodes
* reimaging nodes
* running the bootstrap script
* running a job
* running each phase of each task in a job
> Add timing instrumentation to the exporter

- teuthology/dispatcher/supervisor.py
This should only really include first/last-in-suite jobs.
> sueprvisor: Do not instrument certain job times

- teuthology/misc.py
- teuthology/orchestra/remote.py
I was hoping to evaluate this in testing but apparently this is one of those parts of teuthology that needs merged into main to run. Anyway, I expect this should dramatically reduce the time teuthology spends compressing logs at the end of long tests.
> teuthology/misc: use parallel gzip to compress logs

- tox.ini
It's quite time-consuming, and we're not sure if it's in use at all.
> tox: Don't run openstack by default

- scripts/suite.py
- teuthology/suite/__init__.py
- teuthology/suite/run.py
Notify the user if `results.log` is missing when
they issue a rerun.
1. Edited teuthology-suite doc to
inform the user about how `--rerun` by
default parse `--seed`, `--subset` and
`--no-nested-subset` from `results.log`
by default.
2. In addition to being stored in `results.log`
`--seed` and `--subset` are now also stored in:
`teuthlogy.log`, `config.yaml` and `orig.config.yaml`.
Therefore, in the case where `results.log` is missing, the user can explicitly pass `--seed` and `--subset`.
Fixes: https://tracker.ceph.com/issues/59118
Signed-off-by: Kamoltat <ksirivad@redhat.com>
> teuthology-suite: --seed & --subset now also stored in teuthology.log, config.yaml and orig.config.yaml

- teuthology/task/install/__init__.py
- teuthology/task/install/rpm.py
enable the installation of packages in fedora copr repositories
this should unblock testing against centos9 by using the `ceph/el9` copr for missing python packages
in ceph, https://github.com/ceph/ceph/pull/50441 adds a `centos_9.stream.yaml` file, and i plan to add an override there:
```yaml
overrides:
install:
ceph:
enable_coprs: [ceph/el9]
```
> task: install supports enable_coprs array

- teuthology/task/kernel.py
rpm -q --last sorts by timestamp-of-install, which does not necessarily correlate with "latest version".  sort -rV does.
> task/kernel.py: sort installed kernels by version

- teuthology/provision/fog.py
- teuthology/provision/test/test_fog.py
When too many reimaging ops are running concurrently, we're seeing timeouts. This isn't a true fix, but should help things until we've got one.
> fog: Increase timeout in wait_for_deploy_task()

- teuthology/lock/ops.py
In the case of e.g. owners values not matching on an unlock attempt, we were exhausting all retries and failing to display the exact reason for the unlock failure. We can simply break on 403 errors and let the rest of the function do its thing.
> lock.ops.unlock_one: Fail sooner on 403, with msg

- teuthology/config.py
- teuthology/contextutil.py
- teuthology/provision/fog.py
- teuthology/test/test_contextutil.py
This will help with the sepia lab, being able to increase these
temporarily to handle a new fog server that is sometimes exceeding the
hardcoded timeouts.
> fog: make timeouts configurable

- teuthology/provision/__init__.py
This fixes a regression introuced in #1851. It hadn't been noticed because it only affects manual locking.
> provision: Avoid a possible AttributeError

- bootstrap
This fixes the lack of support for CentOS 9.Stream
> bootstrap: Tolerate a missing lsb_release

- teuthology/dispatcher/__init__.py
- teuthology/exporter.py
A design limitation of prometheus-client's multiprocessing mode is that each process creates files to store its own metrics; the exporter then has to read each file, even if the process which created it is dead.
This results in request latency growing over time, to the point of multiple seconds when the file count gets into the thousands. This eventually results in prometheus failing to fetch, leaving gaps in our data.
We can work around this by restarting at a regular interval; 24h seems like a fine place to start.
> exporter: Restart every 24h

- teuthology/task/ansible.py
- teuthology/test/task/test_ansible.py
The failure logs we capture are sometimes helpful, but are often too long, too complex, and too noisy to understand. Sentry also struggles to associate related failures because of the presence of unique data such as timestamps and URLs.
While I don't see a quick and generic solution to this, there are several common failure modes that can easily be summarized. This commit begins that work by looking for errors caused by network outages.
> ansible: Try to summarize failure logs

- teuthology/misc.py
We started seeing reimage failures with errors like: "teuthology.exceptions.MaxWhileTries: 'ssh_keyscan $host' reached maximum tries (6) after waiting for 5 seconds"
Let's be quite a bit more generous.
> misc.ssh_keyscan: Always retry, and retry more

- teuthology/orchestra/console.py
- teuthology/orchestra/remote.py
in case anything weird is being noticed and communicated by ipmitool, try to display anything it says
> orchestra/console: log output from pexpect commands

- teuthology/exceptions.py
This will cause Sentry to group events by their failure reasons, rather than lumping all AnsibleFailedErrors together
> exceptions.AnsibleFailedError: Add fingerprint()

- teuthology/task/ansible.py
To reduce unecessary duplication in e.g. Sentry.
> task.ansible.FailureAnalyzer: Sort failure items

- teuthology/__init__.py
This quiets messages like: "Converted retries value: 10 ->
Retry(total=10, connect=None, read=None, redirect=None, status=None)"
> Turn down logging for urllib3.util.retry

- teuthology/orchestra/console.py
This is a re-file of #1879.
Fixes: https://tracker.ceph.com/issues/62286
@dmick, I'm not sure if this was your intent, but we're logging a _lot_ more now after #1869. For example:
```
$ grep -a -A1 "console.*\(expect before\|output\):" /a/zack-2023-08-02_18:04:55-powercycle-reef-distro-default-smithi/7358307/teuthology.log > /tmp/7358307_console.txt
$ wc -l /tmp/7358307_console.txt
76 /tmp/7358307_console.txt
$ wc -c /tmp/7358307_console.txt
53344 /tmp/7358307_console.txt53344
```
> PhysicalConsole: Fix UTF-8 related failure

- teuthology/task/install/bin/stdin-killer
Fixes bugs in https://pulpito.ceph.com/pdonnell-2023-08-03_19:12:12-fs-wip-batrick-testing-20230803.140718-distro-default-smithi/
```
2023-08-03T19:40:10.942
INFO:teuthology.orchestra.run.smithi100.stderr:Traceback (most recent
call last):
2023-08-03T19:40:10.942
INFO:teuthology.orchestra.run.smithi100.stderr:  File
"/usr/bin/stdin-killer", line 213, in <module>
2023-08-03T19:40:10.943
INFO:teuthology.orchestra.run.smithi100.stderr:    os.setpgrp()
2023-08-03T19:40:10.943
INFO:teuthology.orchestra.run.smithi100.stderr:PermissionError: [Errno
1] Operation not permitted
```
> stdin-killer: do not setpgrp is already leader

- teuthology/nuke/__init__.py
This avoids a `TypeError: argument of type 'NoneType' is not iterable` when nuking a node whose description is None.
ex: https://sentry.ceph.com/share/issue/91172146663f4c71a6cbfe43725b2e07/
> nuke: Avoid a TypeError w/ null node description

- setup.cfg
- tox.ini
- Drop license_file: It's deprecated in favor of `license_files`, but the default value is
sufficient.
- tox: Avoid buggy sphinx versions
> Fix docs build

- teuthology/scrape.py
Problem:
- confusing warning message stating that the back trace is malformed
- We kept adding to the backtrace buffer even when we exceeded the `MAX_BT_LINES`
Solution:
- Correct the warning message to be "Ignoring backtrace that exceeds MAX_BT_LINES"
- reset the buffer once we exceeded MAX_BT_LINES
- Added some cases where we detect start/end of back trace.
Fixes: https://tracker.ceph.com/issues/62445
> teuthology/scrape: Fix bad backtrace parsing in Teuthology.log

- teuthology/misc.py
ssh-keyscan's output is unsorted, so this function wasn't deterministic.
> misc._ssh_keyscan: Sort keys before returning any

- containers/teuthology-dev/.teuthology.yaml
- containers/teuthology-dev/Dockerfile
- containers/teuthology-dev/containerized_node.yaml
- containers/teuthology-dev/teuthology.sh
This is nearly identical to docs/docker-compose/teuthology, but with some changes to better work with ceph-devstack. The bits in docs/docker-compose should be able to be adapted easily to work with this container.
> Add containers/teuthology-dev

- teuthology/kill.py
... so that we don't unlock nodes while their jobs are running.
> kill: Don't unlock nodes if killing procs fails

- systemd/teuthology-dispatcher@.service
- systemd/teuthology-exporter.service
These are copies of what is currently in use in sepia.
> Add systemd units for exporter and dispatcher

- teuthology/dispatcher/supervisor.py
This was causing a bad race condition, where we could unlock a node, then unlock it again via the nuke process after a different job had locked it.
Fixes: https://tracker.ceph.com/issues/64193
> supervisor: Do not nuke nodes after jobs finish

- teuthology/__init__.py
The project [teuthology-api](https://github.com/ceph/teuthology-api) requires threads to be not patched.
Currently, we are using "teuth-api" branch of teuthology where threads are not patched. With this commit, we'll be able to use the "main" branch as a dependency.
> teuthology/__init__.py: don't patch threads when running via teuthology_api

- teuthology/task/kernel.py
At some point in the past, the layout of the rpm package has changed. There is no file matching "/boot/vmlinuz-" there anymore, instead there is "vmlinuz" file at the root of the modules directory.  For reference:
deb:
-rw-r--r-- root/root  11527168 2024-02-13 16:25 ./boot/vmlinuz-6.8.0-rc4-ga64ccd305b28
-rw-r--r-- root/root     72614 2024-02-13 16:25 ./lib/modules/6.8.0-rc4-ga64ccd305b28/modules.order
rpm:
/lib/modules/6.8.0-rc4-ga64ccd305b28/modules.order
/lib/modules/6.8.0-rc4-ga64ccd305b28/vmlinuz
> kernel: make get_image_version() work for rpm

- teuthology/orchestra/console.py
... from 40s to 120s. A physical host being slightly slow to boot should not cause a reimage failure.
> orchestra.PhysicalConsole: Increase timeout

- teuthology/orchestra/daemon/cephadmunit.py
Fixes a couple of problems in CephadmUnit.start() method:
1. Explicitly pass `start_cmd` as "args" keyword because Remote.run expects keyword arguments.
Fixes: https://tracker.ceph.com/issues/65162
2. `is_started` isn't set to true. When running() is called after start(), then it would
return false, which is not correct since the daemon has been started by calling start().
> fix cephadmunit start() method

- scripts/suite.py
- teuthology/suite/__init__.py
- teuthology/suite/run.py
This will allow us to disable the kdb when running the jobs.
URL: https://tracker.ceph.com/issues/64471
> suite: add the kdb option support

- teuthology/kill.py
By testing access to /bin/true, we were getting false negatives as we meant to be testing for access to /bin/kill. With our configuration, any sudo access indicates access to /bin/kill.
> kill: Fix test-admins' ability to kill

- teuthology/describe_tests.py
- teuthology/suite/merge.py
- teuthology/suite/run.py
When a script may use Lua's prng, we want it to produce the same sequence during a rerun.
Looks like:
```
2024-03-19 16:33:08,391.391 INFO:teuthology.suite:Using random seed=8131
2024-03-19 16:33:08,392.392 INFO:teuthology.suite.run:kernel sha1: distro
2024-03-19 16:33:08,716.716 DEBUG:teuthology.repo_utils:git ls-remote https://git.ceph.com/ceph-ci.git wip-batrick-testing-20240318.181317 -> b6ae24918b03b1b8a19c9263a50655bba80bb810
2024-03-19 16:33:08,716.716 INFO:teuthology.suite.run:ceph sha1: b6ae24918b03b1b8a19c9263a50655bba80bb810
2024-03-19 16:33:08,717.717 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=centos%2F8%2Fx86_64&sha1=b6ae24918b03b1b8a19c9263a50655bba80bb810
2024-03-19 16:33:09,010.010 …
```
> teuthology/suite: initialize lua prng using run's seed

- teuthology/task/install/__init__.py
Currently the install task requires these to be defined only in the definition of the install task itself. Overrides are ignored.
> teuthology/task/install: apply extra_system_packages overrides

- teuthology/packaging.py
The current logic assumes that there is only one build for each distro/flavor per SHA1. However, there is a bug in the jenkins infrastrucutre that sometimes causes multiple builds to trigger for one SHA1. In many of these cases, the first build succeeds, but the second fails. Teuthology only looks at the latest build, notices that it failed, and gives up. However, with this logic, teuthology can go back farther and notice that there is indeed a successful build earlier in the lineup.
Here is an example in which the first centos 8 x86_64 build succeeded, but a second build on top of it failed. Teuthology could only detect the latest failed build: https://shaman.ceph.com/builds/ceph/wip-pdonnell-testing-20240503.010653-debug/ec1d3bd17a3db9d74296aa618f8d63c801bb647e/
Addresses this failure …
> teuthology: modify logic to check for multiple completed builds

- teuthology/suite/__init__.py
teuthology.front no longer allows access to the run directories for general users. In fact, it's not required because we are already getting run information from paddles.
This commit makes it more stringent in --rerun handling: if seed/subset/no_nested_subset do not match, exit failure rather than try to continue. Without a subset, many suites are so large that teuthology-suite will run for several minutes before ultimately failing to schedule due to the quantity of jobs. It also doesn't make sense to rerun a suite when these values do not match.
> teuthology/suite: use paddles solely for rerun info

- bootstrap
On Fedora 38 -
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
Also see: https://fedoraproject.org/wiki/Changes/Fedora_Linux_in_os-release.
With this "./boostrap install" works fine on Fedora 38 at least.
> boostrap: expect "FedoraLinux" along with "Fedora"

- teuthology/suite/__init__.py
Fixes: https://tracker.ceph.com/issues/66302
> teuthology/suite: use valid subset default for rerun without --subset

- bootstrap
- containers/teuthology-dev/Dockerfile
- docs/docker-compose/testnode/Dockerfile
- docs/docker-compose/testnode/testnode_start.sh
- docs/docker-compose/teuthology/Dockerfile
- docs/docker-compose/teuthology/teuthology.sh
- teuthology/orchestra/opsys.py
- teuthology/orchestra/test/test_opsys.py
- teuthology/provision/fog.py
This isn't exhaustive; these are issues I ran into when updating ceph-devstack to work with centos 9 hosts.
> Various updates to support newer OSes

- teuthology/suite/run.py
- teuthology/suite/util.py
> suite.Run.schedule_jobs: Unmask error in dry-run

- scripts/node_cleanup.py
- teuthology/lock/ops.py
- teuthology/lock/query.py
This mainly gets the command working without having to invoke with `--owner` for each user who has jobs running.
> Fixes for teuthology-node-cleanup

- teuthology/orchestra/daemon/cephadmunit.py
- teuthology/orchestra/daemon/state.py
The method is used by DaemonWatchdog to determine if DaemonState/CephadmUnit daemons are active or finished.
Use-case example: https://github.com/VallariAg/ceph/commit/8c2e7c00397ed4f7024fd8a492fbc5716f6de4c5
Run example: https://pulpito.ceph.com/vallariag-2024-06-28_12:47:41-rbd:nvmeof-ceph-nvmeof-mon-distro-default-smithi/
> orchestra/daemon: add finished() method in DaemonState and CephadmUnit

- teuthology/orchestra/connection.py
While working on getting (parts of) teuthology to run locally I found it simpler to extend the ssh configuration used by paramiko.
> orchestra/connection: ssh configuration options

- teuthology/task/selinux.py
This was tracked in [1], but the addition of the context to the allowlist in ceph.git commit 7a6389272aff ("qa: ignore container checkpoint/restore related selinux denials for centos9") doesn't cover krbd suite which doesn't pull in any distro snippets.
Since this denial has nothing to do with Ceph [2], let's ignore it globally.
[1] http://tracker.ceph.com/issues/64616
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2259622
> teuthology/task/selinux: ignore denials in agetty

- teuthology/suite/util.py
We used to do the refresh every time, which wasn't good. Then we didn't do it at all, which was fine until someone tried to schedule against a commit in the few minutes before the mirror picked it up. Let's try doing it when necessary :)
Fixes: #66893
> find_git_parents: Refresh mirror when required

- teuthology/kill.py
... if we can't get it from the filesystem. This is necessary because of the teuthology archive's restricted permissions on teuthology.front.
> kill.kill_job: Get job data from paddles

- teuthology/misc.py
- teuthology/provision/test/test_fog.py
- teuthology/run.py
- teuthology/suite/merge.py
- teuthology/task/__init__.py
- teuthology/task/ansible.py
- teuthology/task/cephmetrics.py
- teuthology/task/tests/__init__.py
- teuthology/test/task/test_ansible.py
- teuthology/test/test_report.py
- teuthology/test/test_run.py
- teuthology/util/loggerfile.py
The 'tests' task had been broken for a very long time. It hasn't passed in years, and
had additionally been masking test failures including some regressions.
This PR:
* Fixes masking of failures in setup/teardown methods
* Actually runs all of our tests
* Excludes tests that need remote nodes when they are not available
* Improves logging and reporting
* Adds support for running in CLI mode
* Fixes several minor test bugs
> Get the 'tests' task working again

- teuthology/dispatcher/__init__.py
- teuthology/kill.py
On macOS dispatcher while trying to go through process list gets stuck
on some of the system processes like launchd, logd, systemstats, etc.
and quites unexpectedly with PermissionError and psutil.AccessDenied
exceptions.
Fixes: https://tracker.ceph.com/issues/67313
> Fix access denied from psutil on macOS

- requirements.txt
- scripts/test/test_exporter_.py
- setup.cfg
- teuthology/dispatcher/__init__.py
- teuthology/dispatcher/supervisor.py
- teuthology/exporter.py
- teuthology/kill.py
- teuthology/provision/__init__.py
- teuthology/repo_utils.py
- teuthology/report.py
- teuthology/run_tasks.py
- teuthology/test/test_imports.py
Also improves the import test performance from 38s to 1s, on my machine.
`teuthology-exporter` on `teuthology.front` is running this branch and behaving normally.
This test run passed unit tests: https://pulpito-ng.ceph.com/runs/zack-2024-07-26_19:28:33-teuthology:no-ceph-main-distro-default-null
> Disable prometheus when exporter isn't running

- teuthology/test/test_repo_utils.py
On macos there are bunch of tests fails because system git version output cannot be parsed because of extra ending.
Output example for macOS:
```
git version 2.39.3 (Apple Git-146)
```
Output example for linux:
```
git version 2.45.2
```
> test/test_repo_utils: correctly parse system git version

- bootstrap
Allow bootstrap to use path outside of teuthology repo root directory for building virtualenv.
> bootstrap: fix VENV variable utilization

- teuthology/orchestra/run.py
Finally get rid of deprecation warning for 'pipes':
```
teuthology/orchestra/run.py:12
/teuthology/teuthology/orchestra/run.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
import pipes
```
> orcherstra/run: don't use pipes, but shlex

- containers/teuthology-dev/teuthology.sh
- docs/siteconfig.rst
- scripts/suite.py
- teuthology/config.py
- teuthology/dispatcher/__init__.py
- teuthology/dispatcher/supervisor.py
- teuthology/dispatcher/test/test_dispatcher.py
- teuthology/suite/__init__.py
- teuthology/suite/placeholder.py
- teuthology/suite/run.py
- teuthology/suite/test/conftest.py
- teuthology/suite/test/test_placeholder.py
- teuthology/suite/test/test_run_.py
- teuthology/test/test_misc.py
- teuthology/util/test/test_time.py
- teuthology/util/time.py
This feature has two parts:
* Specifying expiration dates when scheduling test runs
* A global maximum age
Expiration dates are provided by passing `--expire` to `teuthology-suite` with
a relative value like `1d` (one day), `1w` (one week), or an absolute value like
`1999-12-31_23:59:59`.
A new configuration item, `max_job_age`, is specified in seconds. This defaults
to two weeks.
When the dispatcher checks the queue for the next job to run, it will first
compare the job's `timestamp` value - which reflects the time the job was
scheduled. If more than `max_job_age` seconds have passed, the job is skipped
and marked dead. It next checks for an `expire` value; if that value is in the
past, the job is skipped and marked dead. Otherwise, it will be run as usual.
> Add job expiration dates

- teuthology/orchestra/daemon/cephadmunit.py
This reverts commit 2c6d64a222b4d38d4782ed407e045a86df0a6524.
Related tracker: https://tracker.ceph.com/issues/66883
See the tracker for analysis on how this commit causes unintended behavior in teuthology tests that involve thrashing.
> Revert "orchestra/daemon/cephadmunit.py: fix method kill_cmd()"

- teuthology/contextutil.py
- teuthology/lock/query.py
- teuthology/suite/test/test_util.py
- teuthology/suite/util.py
This PR provides fixes for several issues introduced in #1816:
1) make use of `tries` argument in `list_lock()` instead of hardcoded infinite loop
2) make `safe_while()` sleep between tries again when `tries` < 0, i.e. in case of infinite retries
3) (unrelated) report number of spent tries by safe_while correctly
4) try to get `list_lock()` only once when we're trying get architectures by given machine type for `teuthology-suite`.
https://tracker.ceph.com/issues/67377
> contextutil.safe_while does not sleep between tries if needed to loop infinitely

- setup.cfg
When building wheel for teuthology using `python3 -m build` there are generated two dist files tar.gz and whl for redistribution, both include test files.
This makes test files excluded from 'whl' package, but leave them in tar.gz.
> setup.cfg: exclude tests from wheel package

- scripts/suite.py
- teuthology/suite/run.py
- teuthology/suite/util.py
The option can be used to specify the workunit sha1, it will override the --suite-branch option if both are provided. If --suite-repo is specified, it will search for the --suite-sha1 in this repo otherwise it will look for the sha1 in the default suite repo.
> suite/run: Add a option to specify suite sha1

- teuthology/task/install/packages.yaml
FIxes: https://tracker.ceph.com/issues/68037
> teuthology/task: drop packages that are not built

- teuthology/suite/run.py
- teuthology/suite/test/test_run_.py
pulpito-ng is gaining the ability to kill runs, and for non-admin users will match the user's github username with the test run's owner value to decide if the user is allowed to kill the run (admin users can kill any run). To generate the run name, we normally use the active user account's name.
It could be confusing if a user passed `--owner` but then still sees their unix account name used to name the run; this change lets us use more consistent naming without adding yet another flag (`--user`) to `teuthology-suite`.
Edit: The pulpito-ng PR: https://github.com/ceph/pulpito-ng/pull/51
> suite: use owner value for user name

- teuthology/lock/query.py
When we encounter a node that's locked with a description that doesn't look like it points to a job, avoid the inevitable 404 we'd get from paddles. Without this, the cleanup process gets short-circuited.
> lock: Avoid querying paddles for non-jobs

- teuthology/suite/merge.py
- teuthology/suite/run.py
- teuthology/suite/test/test_run_.py
- teuthology/task/kernel.py
This PR is to support: https://github.com/ceph/ceph/pull/60386
Also, this PR fixes a bug: `teuthology/tasks/kernel: default branch should be "distro"`. When the `kernel` dictionary is empty, the `kernel` task should assume `distro`.
> teuthology/suite: pass the base config to scripts

- containers/teuthology-dev/Dockerfile
This container is built and pushed via GitHub Actions. GHA likes to provision a personal access token for each job that gives tightly-scoped access to the git repository to the job. When we build our container, we end up including `.git/config`, which contains the token. Later, in ceph-dev-stack's CI, an `ls-remote` is run against ceph.git, which ends up causing git to prompt for credentials even though the repo is public. Removing the token should allow reading all the relevant repos from the built container image.
> containers/teuthology-dev: Remove access token

- teuthology/config.py
Allow changing the default "user" location of the teuthology configuration yaml using the (optional) TEUTHOLOGY_CONFIG environment variable. This change aids my effort to run a customized local teuthology environment.
> config: allow reading teuthology config from env var location

- teuthology/orchestra/remote.py
- teuthology/orchestra/test/test_remote.py
Add support for seek and sync in write_file.
This patch will allow for partial writes and sync on completion of write.
This is to support strided writes for cephfs on a multi-mount system.
> teuthology: Add support for seek and sync in write_file

- teuthology/__init__.py
We don't need to support backward compatibility with python 2.
> teuthology: drop __future__ import for print

- teuthology/dispatcher/supervisor.py
No need to use serializer, because everything needed to unlock machines already present in job config.
> dispatcher/supervisor: use job config only to unlock targets

- teuthology/orchestra/run.py
If one of the command args in remote.run is None then there is exception occurs while trying to qoute argument list:
TypeError: expected string or bytes-like object
This fix addresses the issue and gives user better idea what is happening, and how to fix the error.
Fixes: https://tracker.ceph.com/issues/64452
> orchestra/run: better handle weird args

- scripts/node_cleanup.py
- teuthology/dispatcher/supervisor.py
- teuthology/lock/query.py
And some debugging which helped me discover this bug.
> supervisor: Unlock nodes after reimage failure

- teuthology/orchestra/opsys.py
Update Distro codename map with AlmaLinux, RockyLinux, and Tumbleweed openSUSE versions
> opsys: add AlmaLinux and RockyLinux and Tumbleweed to distro codename map

- teuthology/misc.py
Turtles.
Merge when Octopus is EOL. For reals.
See #1772 and #1624 for history.
> Revert "Merge PR #1772 into master"

- teuthology/task/internal/__init__.py
Fixes: https://tracker.ceph.com/issues/61586
> task/internal/__init__.py:  Revisit core program extraction regex

- teuthology/provision/downburst.py
Allow cloud-init preinstall ntp or chrony because we may want not to use ceph-cm-ansible (which is not installing it now as well) so nodes can sync time in order to run all the test successfully when bare cloud images are used.
> When downburst used, command cloud-init to install ntp or chrony for time sync 

- teuthology/task/install/rpm.py
This PR provides fixes combination of two bugs:
- Mistaken appending elements to a list parameter of the function 'rpm': sequential calls of _update_package_list_and_install modified 'rpm' parameter from within the function, because 'rpm' is an object.
- Two attempts to add same packages because of conditional, just do it once after all checks occur.
> Fix packages duplication when extra system packages requested

- teuthology/scrape.py
- teuthology/test/test_scrape.py
Scrape script that trying to find backtrace in gzip log files can hit TypeError: a bytes-like object is required, not 'str' error and fail to collect results. the gzip file need to be decoded.
Fixes: https://tracker.ceph.com/issues/64402
> scrape: searching backtrace with gzip

- teuthology/suite/run.py
- teuthology/suite/test/test_run_.py
In schedule_suite() we only try to find backtracked sha1
for ceph sha1 when --newest is provided and packages are
not found in shaman. However, what about suite_sha1?
Currently, we do not use the backtracked sha1 for suite_sha1.
This commit will make sure that suite_sha1 is using
the backtracked sha1 when ceph_branch and suite_branch are the same and
ceph_repo and suite_repo are the same. This ensures that suite_sha1
only use the backtracked sha1 when the user clearly expects
shaman to not have the latest sha1 and want to use the --newest sha1
for both the ceph code base and suite qa code base.
Additionally, the unit-test in this PR will also cover the changes in:
https://github.com/ceph/teuthology/pull/2054
Fixes: https://tracker.ceph.com/issues/71668
> suite/run.py: suite_hash should use backtracked sha1

- .github/workflows/dev_container.yml
Build the image for PRs but do not push.
For pushes to main branch, push to registery.
To prevent situations like https://tracker.ceph.com/issues/72056
Depends on https://github.com/ceph/teuthology/pull/2063
> ci: run dev_container build for PRs

- .github/workflows/dependencies.yml
- bootstrap
- containers/teuthology-dev/Dockerfile
- teuthology/orchestra/remote.py
- teuthology/orchestra/test/test_remote.py
Add utility method to resolve a hostname from within remote host. This is useful to resolve ip address of the remote host itself, because getting ip address from transport object of ssh is not suitable because it may have only bastion host and port, which is not relevant for the purpose of configuring a cluster.
> orchestra/remote: add resolve_ip method

- teuthology/orchestra/opsys.py
The release 9.5 is gone and all files removed on RockyLinux and AlmaLinux sites, so just update defaults to the latest.
> orchestra/opsys: release shift to 9.6 for rocky and alma linux

- teuthology/openstack/__init__.py
- teuthology/orchestra/test/test_connection.py
We would rather not have openstacksdk be a requirement for all installs, since
most do not use it. This change will not disturb people who install the
openstack extra, which pulls in that and other packages.
Signed-off-by: Zack Cerza <zack@cerza.org>
> openstack: Do not immediately throw ImportError

- teuthology/openstack/__init__.py
In some OpenStack deployments, the server JSON includes 'attached_volumes'
instead of `os-extended-volumes:volumes_attached`. The existing 
get_volumes function only checked the latter, which caused it to always 
return an empty list on these clouds.
This patch updates get_volumes() to:
- Safely access self.info without breaking
- Fallback to 'attached_volumes' if 'os-extended-volumes:volumes_attached'
is not present
- Return the list of volume UUIDs consistently
With this change, teardown logic (volume cleanup on destroy) works 
correctly across both types of openstack responses.
> Fix: handle attached_volumes field when fetching volumes from openstack
