ceph/teuthology

docs/contents.rst, docs/siteconfig.rst
=> Add documentation for teuthology.yaml

teuthology/task/install.py
=> Point yum repo at gitbuilder_host

teuthology/contextutil.py, teuthology/run_tasks.py, teuthology/task/internal.py
http://tracker.ceph.com/issues/10529 and http://tracker.ceph.com/10530
=> Two bugs: vps hostkeys and interactive-on-error multiple activation

scripts/suite.py
=> teuthology-suite: default -v

scripts/suite.py
=> Revert "teuthology-suite: default -v"

docs/siteconfig.rst, scripts/suite.py, teuthology/config.py, teuthology/worker.py
=> Change default results_timeout to 12h

teuthology/nuke.py, teuthology/task/install.py
=> Remove duplicate package list from install task

teuthology/orchestra/daemon.py
This is needed for the failure injection tests.
=> DaemonState: add wait()

teuthology/ceph.conf.template
so we can test legacy tunables
=> ceph.conf: mon warn on legacy tunables = false

teuthology/task/kernel.py
We *could* work around this, but I don't want to mask bugs in the build
system.
=> If the version file is empty, complain.

teuthology/misc.py, teuthology/task/hadoop.py
This isn't perfect yet, but it does use (1) Hadoop 2x series and (2) uses the gitbuilder bindings for the new hadoop-cephfs branch and (3) has been tested with the new wordcount.sh workunit in ceph branch 'hadoop' with outstanding pull request.
=> Hadoop 2.0 Task

teuthology/lock.py
Because of the way we were checking nodes against running jobs, it was
possible to falsely report nodes as stale if they were part of a job
that was transitioning from the waiting to running state.
=> Avoid race condition in find_stale_locks()

teuthology/task/install.py
=> Set check_obsoletes = 1 in yum's priorities.conf

teuthology/task/install.py
If we fail later anyway, fine. If not, yay!
=> Don't fail just because apt-get update does

teuthology/task/install.py
For issue: http://tracker.ceph.com/issues/10926
I tested this out in the octo lab.  The install task passed with this branch, but failed with master.
passed: http://pulpito.ceph.redhat.com/andrewschoen-2015-02-23_15:58:54-teuthology-master---basic-magna/
failed: http://pulpito.ceph.redhat.com/andrewschoen-2015-02-23_15:59:03-teuthology-master---basic-magna/
=> Do not install packages with a specified version, fixes #10926

teuthology/task/hadoop.py
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
=> hadoop: support rhel and ubuntu

teuthology/task/install.py
Because of the split of ceph-devel, upgrading ceph-devel with an
explicit version does not allow check_obsoletes to work.
For, http://tracker.ceph.com/issues/10936
=> Do not specify a version when upgrading ceph on rpm-based systems.

teuthology/config.py
=> Don't use yaml in FakeNamespace's repr()

teuthology/task/install.py, teuthology/test/task/test_install.py
Fixes: http://tracker.ceph.com/issues/11243
=> Verify version for other projects besides ceph in the install task

teuthology/task/install.py, teuthology/test/task/test_install.py
See: http://tracker.ceph.com/issues/11248
=> Disable version check when ceph-deploy is used to install ceph.

scripts/update_inventory.py, setup.py
This ought to also replace teuthology-updatekeys, but might not be as
fast yet.
=> Add teuthology-update-inventory command

teuthology/task/internal.py
with '-p' when mkdir
Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>
=> Make parent directories as needed

teuthology/task/ssh_keys.py
The other changes are my text editor automatically removing end-of-line whitespace.
=> When modifying authorized_keys, store a backup

teuthology/task/kernel.py
=> Docs for using koji in the kernel task.

teuthology/task/kernel.py
It was being suppressed needlessly. Also fix lots of linter issues.
=> Log stderr in get_latest_image_version_deb()

teuthology/task/ssh_keys.py
=> ssh_keys: stop using sed, use saved backup of authorized_keys instead

teuthology/suite.py
=> Fix branch selection logic

bootstrap
Added openSUSE and SLES conditions in bootstrap.
Signed-off-by: Kapil Sharma ksharma@suse.com
=> Added openSUSE and SLES conditions in bootstrap.

docs/siteconfig.rst, teuthology/config.py, teuthology/task/internal.py, teuthology/test/test_config.py
Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>
=> Make the number machines to be reserved configurable

teuthology/task/kernel.py
http://tracker.ceph.com/issues/11627
=> Remove old kernels on RPM-based systems

teuthology/suite.py
Signed-off-by: Samuel Just <sjust@redhat.com>
=> suite: print out subset chosen

teuthology/task/internal.py
=> task/internal: account for locked machines acquired on previous loops

teuthology/task/kernel.py
http://tracker.ceph.com/issues/11684
=> Update kernel dependencies on Ubuntu

teuthology/config.py, teuthology/suite.py, teuthology/task/install.py, teuthology/task/internal.py, teuthology/test/task/test_install.py, teuthology/test/test_suite.py
http://tracker.ceph.com/issues/11645
=> Use kernel_flavor when polling gitbuilders

teuthology/suite.py, teuthology/task/install.py, teuthology/test/test_suite.py
http://tracker.ceph.com/issues/11772
http://qa-proxy.ceph.com/teuthology/zack-2015-05-26_15:15:15-teuthology:ceph-master---basic-vps/910011/teuthology.log
=> Use CentOS packages on RHEL

teuthology/lock.py
http://tracker.ceph.com/issues/11812
http://tracker.ceph.com/issues/11813
=> teuthology-lock usability

teuthology/task/install.py
... in _update_deb_package_list_and_install()
=> Use requests locally instead of wget remotely

teuthology/report.py
=> ResultsReporter: add get_job()

teuthology/misc.py, teuthology/suite.py, teuthology/test/test_get_distro_version.py, teuthology/test/test_suite.py
=> Bump default OS versions

scripts/nuke.py, teuthology/nuke.py
=> Add --dry-run to teuthology-nuke

teuthology/task/ansible.py, teuthology/test/task/test_ansible.py
=> Add extra_vars support for Ansible

teuthology/task/internal.py
http://tracker.ceph.com/issues/11808
=> Keep better count of locked nodes

teuthology/lock.py
Also, clean up the status selection a tiny bit with winnow()
=> lock.py: allow selection of machines to list by os-type/os-version

teuthology/lock.py
=> lock.py: json-query was matching any; make it match all

teuthology/task/install.py
=> Changes for rh installer to work

teuthology/task/kernel.py
My last PR fixed one bug and introduced another, despite my testing. This one should fix that bug, and also adds some more logging to help trace future issues.
=> More distro kernel fixes

scripts/lock.py
=> scripts/lock.py: fix help for --json-query

teuthology/__init__.py, teuthology/lock.py, teuthology/report.py
Also, do it only in teuthology/\_\_init\_\_.py
=> Silence urllib3 logging whether it's bundled in requests or not

teuthology/suite.py
=> suite.py: say *which* path is invalid in _build_matrix

scripts/queue.py, teuthology/beanstalk.py
=> teuthology-queue --pause

bootstrap, setup.py
See
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning
=> Fix InsecurePlatformWarning from urllib3

teuthology/orchestra/run.py
http://tracker.ceph.com/issues/8313 Fixes: #8313
=> orchestra: decode('utf-8') before logging

teuthology/nuke.py
https://bugzilla.redhat.com/show_bug.cgi?id=1233329
http://tracker.ceph.com/issues/12005
=> Work around BZ 1233329

teuthology/lock.py
=> lock.py: handle statuses with no description

bootstrap
Adds an 'install' flag to the bootstrap that if given will install any missing packages needed for the bootstrap. This requires the user running ./bootstrap have sudo privileges.
=> bootstrap: apt/yum install the list of dependencies if missing

teuthology/task/internal.py
=> include the machine type when waiting for machines

teuthology/task/internal.py
=> syslog: Set SELinux context for logfiles

teuthology/lock.py
=> lock: add debian 8.0 (jessie) as vps target

teuthology/misc.py, teuthology/test/test_misc.py
http://tracker.ceph.com/issues/10086
=> Allows other users besides ubuntu

bootstrap, setup.py, teuthology/test/test_provision.py, tox.ini
=> Fix dependency handling and unit tests

docs/siteconfig.rst, teuthology/config.py, teuthology/suite.py, teuthology/worker.py
In case we want to reference a local directory instead of reseting from
a clone of teuthology.
=> implement teuthology_path similar to suite_path

teuthology/worker.py
It is convenient for integration tests as a way for the worker to be
instructed to shutdown cleanly.
=> add stop_worker: as a mean to shutdown the worker

teuthology/orchestra/remote.py, teuthology/task/internal.py
http://tracker.ceph.com/issues/12622
=> Add Remote.chcon()

teuthology/task/selinux.py
http://tracker.ceph.com/issues/12605
=> SELinux: Rotate and archive audit.log

teuthology/task/knfsd.py
Fixes: #9994
Signed-off-by: Yan, Zheng <zyan@redhat.com>
=> tasks/nfs: make sure NFS kernel server is started

teuthology/beanstalk.py
=> When listing jobs, show their priority

teuthology/task/kernel.py
This fixes issue: http://tracker.ceph.com/issues/12795
=> kernel: use packaging.GitbuilderProject to talk with gitbuilder.

teuthology/packaging.py
=> packaging: add jessie codename

README.rst
Clone from master instead of a designated branch.
=> openstack: update HOWTO

teuthology/task/install.py
Version check for 1.3.1  bit of restructure for overrides and add ansible task
=> Add version check for 1.3.1, add ansible task

teuthology/suite.py
http://tracker.ceph.com/issues/12995
=> Fix bug in using priority 0

teuthology/openstack/__init__.py, teuthology/openstack/openstack-debian-8.0-user-data.txt
=> openstack: add jessie / debian 8 support

teuthology/packaging.py
See: http://tracker.ceph.com/issues/13030
=> packaging: correctly select flavor when initializing with a remote

docs/siteconfig.rst, teuthology/openstack/setup-openstack.sh
Do not clone from an obsolete development branch by default.
=> openstack: clone from the teuthology master

teuthology/openstack/__init__.py
=> openstack: upgrade to debian 8.2.0

teuthology/openstack/__init__.py
Get the latest CentOS 7 cloud image.
=> openstack: update CentOS image

teuthology/suite.py
See: http://tracker.ceph.com/issues/13125
=> suite: fixes a bug that causes the email results job to not be scheduled

setup.py
=> openstack: workaround os-client-config 1.7.0 regression

teuthology/openstack/openstack-centos-6.5-user-data.txt, teuthology/openstack/openstack-centos-7.0-user-data.txt, teuthology/openstack/openstack-ubuntu-user-data.txt
=> openstack: get rid of failed attempt to use ephemerals

README.rst
=> README.rst: minor grammar/style fixes (first half)

teuthology/ceph.conf.template
This will make it more likely for us to hit #13116
=> ceph.conf: short cephfs data pool replay window

teuthology/openstack/__init__.py, teuthology/openstack/openstack-centos-6.5-user-data.txt
=> openstack: update CentOS 6 cloud image

scripts/prune_logs.py, scripts/test/test_prune_logs.py, setup.py, teuthology/prune.py
Wrote this a while back but it slipped off my radar.
=> Add teuthology-prune-logs

README.rst
=> openstack: document common pitfalls and OpenStack tenant grants

teuthology/openstack/test/openstack.yaml
It depends on other commits that were not merged yet.
=> openstack: do not buildpackages by default

docs/siteconfig.rst, teuthology/config.py, teuthology/openstack/setup-openstack.sh
http://tracker.ceph.com/issues/13249
=> config: ~/teuthology.yaml check_package_signatures hint

teuthology/openstack/__init__.py
=> openstack: open ports 1:65356 for all targets

teuthology/lock.py
=> Break out of retry loop

teuthology/provision.py
=> openstack: remove dead code

teuthology/openstack/__init__.py
=> openstack: the web interface is pulpito

teuthology/misc.py
=> misc: .sh must not log the output twice on error

teuthology/task/install.py
=> install: document tag, branch and sha1 precedence

teuthology/test/test_suite.py
=> TestSuiteMain.test_main(): don't hit the network

teuthology/openstack/openstack-teuthology.init
=> openstack: wait for server delete to complete

teuthology/openstack/__init__.py
=> openstack: set dreamhost if OS_AUTH_URL has dream.io

teuthology/openstack/__init__.py, teuthology/openstack/test/test_openstack.py
=> openstack: try to get private IP from neutron

teuthology/openstack/openstack-user-data.txt
=> openstack: add 8.8.8.8 as a last resort resolver

teuthology/openstack/setup-openstack.sh
=> openstack: only consider IPv4 subnets

bootstrap, setup.py
See
https://bitbucket.org/pypa/setuptools/issues/464/typeerror-in-install_wrapper_scripts
=> Work around setuptools 18.6 regression

teuthology/openstack/__init__.py
=> openstack: teuthology for 100 or more need 32GB

teuthology/openstack/openstack-teuthology.init
=> openstack: run 20 server/deletion at a time

teuthology/config.py, teuthology/lock.py, teuthology/misc.py, teuthology/nuke.py, teuthology/openstack/__init__.py, teuthology/openstack/test/openstack-integration.py, teuthology/openstack/test/test_openstack.py, teuthology/test/test_config.py, teuthology/worker.py
http://pulpito.ovh.sepia.ceph.com:8081/zack-2015-12-02_17:37:23-smoke-master---basic-openstack/
=> Use the newer config API

teuthology/nuke.py, teuthology/test/test_nuke.py
The openstack server/volume show typically takes a few seconds to
complete due to the provider API slowness/throttling. It is possible that
a volume/instance found with openstack server list no longer exists when
running openstack server show to get more information about it.
=> nuke: --stale-openstack must cope with disappearing volumes / instances

.gitlab-ci.yml
=> enable GitLab CI

teuthology/openstack/__init__.py, teuthology/openstack/openstack-ubuntu-12.04-user-data.txt, teuthology/openstack/openstack-ubuntu-14.04-user-data.txt
tracker.ceph.com/issues/13520 Fixes: #13520
=> openstack: add support for ubuntu 12.04

teuthology/openstack/__init__.py
The setup() function of TeuthologyOpenStack creates an OpenStackInstance
datamember to cache results and avoid running numerous duplicate
commands.
=> openstack: use OpenStackInstance in TeuthologyOpenStack

teuthology/misc.py, teuthology/openstack/__init__.py, teuthology/openstack/test/test_openstack.py, teuthology/provision.py, teuthology/test/test_misc.py
Instead of waiting for the completion of the ssh command,
display stdout/stderr continously.
=> openstack: TeuthologyOpenStack.ssh continuous output

teuthology/task/clock.py
=> clock: get the servers to use for ntpdate from ntp.conf

teuthology/misc.py
=> misc: get_pkg_type to infer the package time from the os_type

openstack-delegate.sh, tox.ini
=> tests: delegate integration tests to OpenStack

teuthology/openstack/setup-openstack.sh
The init.d fres, but does nothing.
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>
=> dnsmasq is not actually restarting

teuthology/task/selinux.py
dmidecode intermittently appears in denial list causing the test to fail
=> Ignore few se denials in log parsing

README.rst
The other providers are likely to work but since they are not actively
tested, it is better no to claim they do.
=> doc: only OpenStack with OVH is supported

teuthology/nuke.py
This is http://tracker.ceph.com/issues/14517
=> Fix -nuke --stale-openstack

teuthology/prune.py
=> prune: Process log dirs in order of ctime

teuthology/misc.py
=> Revert "misc: ignore some unusable block devices"

teuthology/task/install.py
Note that our kludge to handle extras does not include debuginfo packages,
which means we won't get those for ceph-deploy runs for now.
=> task/install: only install debug packages if debuginfo: true

teuthology/worker.py
=> worker: When running a job, log the full command

teuthology/misc.py
=> get_distro_version: Always return a string

setup.py
=> openstack: package CentOS 7.2 data file

scripts/openstack.py
=> openstack: add --wait to block until the suite finishes

tox.ini
=> openstack: test selection for openstack-integration

teuthology/repo_utils.py
This will cause git repos on-disk to be updated to point at the correct
remote based on config.ceph_git_base_url
=> repo_utils: Call git set remote-url

README.rst
=> README.rst: mention teuthology-openstack in Provided Utilities

teuthology/misc.py
=> misc.get_wwn_id_map: not finding wwns is not an error

teuthology/nuke.py, teuthology/task/install.py, teuthology/task/packages.yaml, teuthology/test/task/test_install.py
This is aimed at addressing:
http://tracker.ceph.com/issues/15014
That will also require a suite change to apply a different package list.
There's also a bit of cleanup here.
=> install task: Make package lists configurable

teuthology/task/install.py
=> install: Fix non-idempotent check_obsoletes tweak

teuthology/openstack/setup-openstack.sh
http://tracker.ceph.com/issues/14997 Fixes: #14997
=> openstack: protect against stale keypairs

teuthology/task/install.py
rh version update and minor updates
Signed-off-by: Vasu Kulkarni vasu@redhat.com
=> rh version update

teuthology/openstack/__init__.py
=> openstack: add wget command for openSUSE Leap 42.1 VM image

teuthology/task/parallel.py
This syntax is consistent with task configuration everywhere else.
The subtley of different syntax for this task made modifying suites
error-prone. Keep the existing syntax so we don't have to change all
the upgrade suites in each ceph-qa-suite branch.
=> task/parallel: accept lists of tasks in referenced sections

teuthology/openstack/__init__.py
=> openstack: open UDP ports required by NFS

teuthology/task/install.py
=> Rebase 2.0 to 10.1.0

teuthology/lock.py, teuthology/packaging.py
=> add ubuntu 16.04 xenial support

setup.py
=> Work around pip dependency issue w/ nova and Babel

teuthology/suite.py
Directory names closer to the root than /suites are not used by the filter.
Fixes 15470
=> Restrict filter to not scan too far up a path.

setup.py
=> Unpin paramiko

bootstrap
Changes for Redhat Linux
http://fpaste.org/348380/36955145/raw/
=> Changes for bootstrap to work on RHEL

teuthology/prune.py
This will likely free up a large amount of data on sepia's log storage cluster
=> prune: also remove mon data in jobs' 'data' subdir

teuthology/suite.py
http://tracker.ceph.com/issues/15711
Fixes: 15711
=> Always mention name and sha1 when scheduling fails

teuthology/orchestra/remote.py, teuthology/orchestra/test/test_remote.py
http://tracker.ceph.com/issues/15427
=> Remote: log file sizes before transferring

scripts/suite.py, teuthology/exceptions.py, teuthology/suite.py, teuthology/test/test_suite.py
=> suite.py: allow specifying ceph sha1

teuthology/describe_tests.py, teuthology/suite.py, teuthology/test/fake_fs.py, teuthology/test/test_describe_tests.py, teuthology/test/test_suite.py
This involves a little work in the tests.
=> Give a better error message for "suite not found"

teuthology/task/pcp.py, teuthology/test/task/test_pcp.py
http://tracker.ceph.com/issues/16049
Fixes: 16049
=> pcp: Don't fail a job if graph downloading fails

teuthology/provision.py
=> Bump downburst VMs to 4GB

teuthology/provision.py
http://tracker.ceph.com/issues/16302
Fixes: 16302
=> Install python 2.7 on ubuntu downburst VMs

teuthology/suite/__init__.py, teuthology/suite/build_matrix.py
We were processing the --subset arg well after it was necessary :-/
http://tracker.ceph.com/issues/16335
Fixes: 16335
=> Fix regression in --subset

teuthology/task/valgrind.supp
=> valgrind: add supporession for rocksdb thread local leaks

teuthology/__init__.py
=> Add teuthology git version query/logging

teuthology/__init__.py
=> Revert "Add teuthology git version query/logging"

teuthology/__init__.py
Round 2, this time with testing
=> teuthology: log version number

teuthology/repo_utils.py
We can selectively skip fetching and/or bootstrapping if either have
been completed successfully in the last 60s
=> Fix slow worker startup

docs/README.rst, docs/openstack_backend.rst
Signed-off-by: lande1234 <lan.de3@zte.com.cn>
=> fix wrong words

scripts/suite.py, teuthology/orchestra/opsys.py, teuthology/orchestra/test/test_opsys.py, teuthology/packaging.py, teuthology/suite/placeholder.py, teuthology/suite/run.py, teuthology/suite/test/test_placeholder.py, teuthology/suite/test/test_run_.py, teuthology/suite/test/test_util.py, teuthology/suite/util.py
also added the ability to specify either version or codename and have the other inferred (version_codename).
=> teuthology-suite: add --D/--distroversion

teuthology/suite/run.py, teuthology/suite/test/test_run_.py, teuthology/suite/util.py
http://tracker.ceph.com/issues/16838
First I created a reproducer, then I discovered two ways to fix the bug.
They both seem like good ideas, and appear to not cause further regressions, so I think we may want both commits.
=> Fix regression when using teuthology-suite with --kernel

teuthology/worker.py
=> Fix an obvious bug in sentinel()

teuthology/task/ansible.py, teuthology/test/task/test_ansible.py, teuthology/test/task/test_ceph_ansible.py
=> CephLab: playbook failures result in status 'dead'

teuthology/task/packages.yaml
=> packages.yaml: reflect python-ceph package split

teuthology/misc.py, teuthology/test/test_misc.py
=> misc.sh(): Don't capture stderr by default

teuthology/task/install.py
...by replacing `python3-*` with `python34-*` on CentOS.
This is required so python3-based packages can be specified cleanly in `extra_packages` (like [here](https://github.com/ceph/ceph-qa-suite/compare/wip-ceph-python3#diff-9b1ef2f4528109b07046d9dec615dd08R3)), because packages for CentOS will have a `python34-` prefix and not `python3-`, to follow the existing convention.
Related to https://github.com/ceph/ceph/pull/10208
=> install: Allow installing python3 packages universally

teuthology/nuke/__init__.py
Specifically, ceph-qa-suite.git/tasks/cephfs/filesystem.py apparently
needs the clear_firewall action.
=> Fix imports of nuke actions from other modules

teuthology/nuke/__init__.py, teuthology/nuke/actions.py
http://tracker.ceph.com/issues/17084
Fixes: 17084
=> Kill valgrind.bin processes

teuthology/nuke/__init__.py, teuthology/openstack/__init__.py, teuthology/openstack/setup-openstack.sh, teuthology/openstack/test/openstack-integration.py, teuthology/openstack/test/test_openstack.py, teuthology/provision/openstack.py, teuthology/test/test_nuke.py
Loic wrote up #929, but the unit tests were failing.  As ovh is completely broken without it, I made a branch that extends that PR with unit test fixes.
=> openstack: Cache auth tokens, add unit test fixes

teuthology/orchestra/console.py, teuthology/task/console_log.py, teuthology/test/task/test_console_log.py
=> Console: rename has_credentials

teuthology/config.py, teuthology/packaging.py, teuthology/run.py, teuthology/suite/test/test_run_.py, teuthology/suite/test/test_util.py, teuthology/suite/util.py, teuthology/task/install.py, teuthology/task/internal.py, teuthology/test/task/test_install.py, teuthology/test/test_packaging.py
Note that this PR does not add shaman support to the kernel task, as we're not building kernels with chacra yet.
=> Support fetching packages from shaman instead of gitbuilder

teuthology/nuke/actions.py
=> teuthology: update nuke for ceph-mgr

teuthology/packaging.py, teuthology/repo_utils.py, teuthology/suite/util.py, teuthology/test/test_packaging.py
This is to help enable upgrade tests using Shaman
=> ShamanProject: query tags

teuthology/task/install.py
Previously, we were only applying the setting for upgrades
=> install: apply exclude_packages globally

teuthology/nuke/actions.py
=> teuthology/nuke: update for python-rgw

scripts/lock.py
=> lock: -m alias for --machine-type

teuthology/misc.py
This is moved to ceph-qa-suite.
Fixes: http://tracker.ceph.com/issues/17614
Signed-off-by: John Spray john.spray@redhat.com
=> misc: remove generate_caps

teuthology/ceph.conf.template
=> ceph.conf: osd debug  misdirected ops = true

teuthology/config.py
=> Default use_shaman to True

scripts/suite.py, teuthology/repo_utils.py, teuthology/run.py, teuthology/suite/__init__.py, teuthology/suite/placeholder.py, teuthology/suite/run.py, teuthology/suite/test/test_placeholder.py, teuthology/suite/test/test_run_.py, teuthology/suite/test/test_util.py, teuthology/suite/util.py, teuthology/test/test_repo_utils.py, teuthology/worker.py
... and also optionally look for tasks and suite definitions in a subdirectory of that repo
Related:
http://pad.ceph.com/p/qa-suite-merge
https://paste.fedoraproject.org/493541/04623891/
=> Allow using an alternate suite repo

scripts/suite.py, teuthology/run.py, teuthology/suite/placeholder.py, teuthology/suite/run.py, teuthology/suite/test/test_placeholder.py
This needs testing before it's merged.
* [``teuthology-suite -v -c wip-sage-testing -m smithi -s smoke -l 1 --filter-out ceph-deploy --ceph-repo git://git.ceph.com/ceph-ci.git -p 1 -e zack@redhat.com -t $(git_branch_current)``](http://pulpito.ceph.com/zack-2016-12-13_12:00:02-smoke-wip-sage-testing---basic-smithi/) :thumbsup:
=> suite: Add --ceph-repo option

teuthology/packaging.py
For upgrade tests that are otherwise using ceph-ci.git, we need to also
look in ceph.git to lookup released tags.
=> ShamanProject._tag_to_sha1(): retry w/ ceph.git

teuthology/task/ceph_ansible.py, teuthology/test/task/test_ansible.py, teuthology/test/task/test_ceph_ansible.py
CentOS: http://pulpito.ceph.com/vasu-2016-12-07_16:28:29-smoke:ceph-ansible-jewel---basic-vps/
Xenial: http://pulpito.ceph.com/vasu-2016-12-07_16:28:41-smoke:ceph-ansible-jewel---basic-vps/
Fixed ansible to 2.1 due to peding issue in 2.2, we can move to 2.2 when it works
=> ceph-ansible task changes for tests to work with latest ceph-ansible master branch

teuthology/task/swift.py
This needs testing but I wanted to get it out so I don't forget about it
Signed-off-by: Ali Maredia <amaredia@redhat.com>
=> swift: added "--cluster" to rgw-admin command for multisite support

scripts/prune_logs.py, teuthology/prune.py
=> prune: Compress teuthology.log

setup.py, teuthology/run.py, teuthology/worker.py
This will hopefully fix http://tracker.ceph.com/issues/18482
=> Avoid a race condition with job archive creation

teuthology/task/kernel.py
Some rpm scripts don't allow dashes in the Release field, so let's
accept both -g and _g.  Kill _vsplitter() as Calxeda is no more.
=> kernel: be more flexible about sha1 matching

teuthology/task/pcp.py
Fixes: http://tracker.ceph.com/issues/18594
=> pcp: use a timeout when downloading graphite graphs

setup.py, teuthology/__init__.py
https://pypi.python.org/pypi/manhole
=> Use manhole to provide a way to debug hung jobs

teuthology/__init__.py
=> Tell gevent not to patch os.waitpid()

scripts/suite.py, teuthology/suite/test/test_init.py
=> teuthology-suite: Drop default for --ceph

bootstrap
Signed-off-by: Jan Fajerski <jfajerski@suse.com>
=> bootstrap: add support for opensuse tumbleweed.

teuthology/nuke/actions.py
Fixes: http://tracker.ceph.com/issues/19061
=> nuke: Remove samba repos

teuthology/misc.py
It doesn't make any sense to wait more than a few minutes for OSDs to
come up. If they take more than five minutes, fail the job.
=> misc.wait_until_osds_up(): timeout after 5min

teuthology/nuke/actions.py
Fixes: http://tracker.ceph.com/issues/18974
=> nuke: Remove nfs-ganesha repos

docs/detailed_test_config.rst
so it is able to work with latest teuthology
=> docs/detailed_test_config.rst: fix the sample yaml

teuthology/task/clock.py
#1013 got merged with an old version of my local branch, because I never repushed after fixing it.
This PR includes the missing bits from that original set of code and testing.
=> Include missing pieces from ntpd clock task change

bootstrap
=> bootstrap: Update required package names for Fedora 25

teuthology/provision/downburst.py
Specifically, if the instance doesn't even exist, consider the destroy
op to have succeeded.
=> provision.downburst: Tweak destroy return code

teuthology/provision/__init__.py
=> provision: ctx does not always have 'config' attribute

docs/downburst_vms.rst
=> docs: Update libvirt conf to match current vps_hosts list

teuthology/ceph.conf.template
=> ceph.conf: mon osd allow pg remap = true

teuthology/orchestra/daemon.py
The former registers without starting; the latter does both (as before).
=> orchestra/daemon: separate register_daemon from add_daemon

teuthology/run.py, teuthology/task/internal/__init__.py, teuthology/task/internal/redhat.py, teuthology/task/kernel.py
setup repo based on config items, either use
cdn or compose sytle urls or plain repo's.
Still testing with other change,
=> Add redhat internal tasks that setup repo

teuthology/ceph.conf.template
=> ceph.conf: debug mgr by default

teuthology/task/ceph_ansible.py
=> Add missing run.Raw() to ceph_ansible.py

teuthology/orchestra/daemon.py
=> check_status(): No-op if there's no proc object

teuthology/ceph.conf.template
Fixes: http://tracker.ceph.com/issues/19631
=> ceph.conf: adjust "mon reweight min *" for mgr also

teuthology/misc.py
http://pulpito.ceph.com/vasu-2017-04-11_21:01:29-smoke-master---basic-vps/, Failed xenial test is a ceph issue
=> Add option to use sudo to check ceph health when required

teuthology/task/ceph_ansible.py
we are missing setting up the rgw role
=> ceph_ansible: Add the missing rgw role

teuthology/task/full_sequential_finally.py
=> task/full_sequential_finally: run commands on unwind/cleanup

teuthology/task/install/valgrind.supp
=> valgrind: suppression for python embedded in ceph-mgr

teuthology/orchestra/opsys.py, teuthology/test/test_get_distro_version.py, teuthology/test/test_packaging.py
http://tracker.ceph.com/issues/19859
=> Update default Ubuntu version to 16.04

teuthology/nuke/actions.py, teuthology/task/ceph_ansible.py
=> [tasks/ansible] Add support for mgr role

teuthology/task/install/__init__.py, teuthology/test/task/test_install.py
http://tracker.ceph.com/issues/16521
=> Pre-upgrade sanity check

teuthology/task/ceph_ansible.py
=> [task/ceph_ansible]: collect logs when the test fails

teuthology/provision/downburst.py
Related to:  https://github.com/ceph/ceph/pull/16799
=> [teuthology/provision]: Increase number of drives for vps to 4

teuthology/openstack/openstack.yaml
Fixes http://tracker.ceph.com/issues/21140
Replaced https://github.com/ceph/teuthology/pull/1105
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>
=> Removed default_idle_timeout

scripts/prune_logs.py, teuthology/prune.py
This works exactly like --pass, except it defaults to being disabled
=> prune: Optionally remove failed jobs entirely

teuthology/task/ansible.py
=> [ansible-doc-fix]: correct the doc to fix the overrides name

teuthology/ceph.conf.template
This is replacing the old one, but we need to keep the old one for
upgrades etc.
=> ceph.conf: set new pg max per osd limit

teuthology/task/install/__init__.py, teuthology/task/internal/__init__.py
=> More work to allow mounting /var/lib/ceph to a testnode device

teuthology/task/ceph_ansible.py
Fixes: http://tracker.ceph.com/issues/21574
=> update ansible package from ansible PPA

teuthology/orchestra/opsys.py, teuthology/test/test_packaging.py
=> Update default OS versions

teuthology/lock/cli.py, teuthology/lock/keys.py, teuthology/misc.py
=> Tolerate failure to scan VM host keys

teuthology/task/install/valgrind.supp
Signed-off-by: Jason Dillaman <dillaman@redhat.com>
=> valgrind: added suppression for cython constants

teuthology/task/ceph_ansible.py
This allows one to place the ceph ansible installer node on another machine.
It defaults back to the lowest monitor if there is no installer.0 role.
=> Implement installer.0 role.

teuthology/task/ceph_ansible.py
Insure that mon node is used for rbd_pools.
=> Fix installer.0 bug.

teuthology/suite/__init__.py
=> suite: do not rerun jobs w/o description

teuthology/task/ansible.py, teuthology/test/task/test_ansible.py
=> ansible: Add ability to skip tags during ansible task

docs/intro_testers.rst
Signed-off-by: Gregory Meno <gmeno@redhat.com>
=> Update getting started instructions to link to the new sepia wiki

teuthology/task/selinux.py
Fixes: http://tracker.ceph.com/issues/23798
=> task.selinux: Whitelist syslogd_t denials

teuthology/orchestra/opsys.py
=> Add Bionic to distro map

teuthology/suite/build_matrix.py, teuthology/suite/test/test_build_matrix.py
If either the diretory contains a magic $ file, or if the directory name
ends with $, then the random selection of a yaml file will occur.
=> Allow both $ and directory$ for random yamls.

teuthology/suite/test/test_run_.py
=> suite/test/test_run_.py: Don't hit the network!

requirements.txt
http://tracker.ceph.com/issues/24168
=> Unpin libvirt-python

scripts/suite.py, teuthology/suite/__init__.py, teuthology/suite/build_matrix.py, teuthology/suite/run.py
this change allows us to `--rerun` the full set of failed tests.
=> suite: allow `--rerun` to run full set of failed tests

teuthology/task/ceph_ansible.py
=> added nfs-ganesha to roles

teuthology/task/install/__init__.py
Reverts ceph/teuthology#1090
Shame on me for not noticing the DNM...
=> Revert "[DNM] upgrade check: upgrade to same version is a noop"

teuthology/report.py
=> report: strip space and quotes from parsed message

teuthology/task/install/__init__.py, teuthology/task/install/deb.py, teuthology/task/install/rpm.py, teuthology/test/task/test_install.py
Fixes: http://tracker.ceph.com/issues/25020
Fixes: http://tracker.ceph.com/issues/25026
=> install: make extra_packages distro-agnostic (in a limited way) and support extra_system_packages option

teuthology/task/install/valgrind.supp
=> teuthology/task/install/valgrind.supp: add suppression for DPDK

teuthology/task/print.py
The documentation is taken from the commit message that first
introduced this task.
=> teuthology/task: improve documentation of "print" internal task

teuthology/orchestra/run.py
The stdout/stderr greenlets will not necessarily exit when the command does if
child processes are stuck in an uninterruptible sleep. For example, the fsx.sh
workunit spawns fsx processes that may be left behind in the D state after
/bin/timeout kills fsx.sh. These are connected to the stdout/stderr pipes which
prevent the greenlets from exiting normally.
=> run: do not block on greenlets after command exits

teuthology/task/kernel.py
Fixes: https://tracker.ceph.com/issues/36499
=> kernel: Update kernel using `DEBIAN_FRONTEND noninteractive`

requirements.txt
Signed-off-by: Ricardo Dias <rdias@suse.com>
=> requirements.txt: add JWT dependency required by ceph-dashboard tests

teuthology/task/install/rpm.py
after cd1cef6, we install rpm packages like
2018-10-25T06:31:33.578 INFO:teuthology.orchestra.run.smithi076:Running:
"sudo yum -y '' install '' '' libcephfs_jni1"
...
2018-10-25T06:31:34.180
INFO:teuthology.orchestra.run.smithi076.stderr:No such command: . Please
use /bin/yum --help
2018-10-25T06:31:34.193 DEBUG:teuthology.orchestra.run:got remote
process result: 1
which fails the qa run on rpm based distros.
in this change, the command line args are passed in itertools.chain(),
because orchestra.run.quote() takes an iterable which contains string or
Raw.
=> task/install: run 'yum ... install' the right way

teuthology/task/selinux.py
Signed-off-by: Linggang Zeng <linggang.zeng@easystack.cn>
=> Fix setenforce failed while selinux is disabled

teuthology/orchestra/remote.py
Adds a remote.sh similar to misc.sh, in fact a shortcut for remote.run,
but return output instead of proc
Example:
```
my_name = Remote('127.0.0.1').sh('whoami')
```
Adds a remote.sh_file run a script as file on a remote with or without sudo
Example 1: Run python script with shebang
```
Remote('127.0.0.1').sh_file("#!/usr/bin/env python3\n"
"import sys\n"
"print(sys.version_info)")
```
Example 2: Run script as root
```
Remote('user@host.domain').sh_file("whoami", sudo=True,
label="who-am-i-for-the-real")
```
Example 3: Run script as other user
```
Remote('user@host.domain').sh_file("whoami", sudo='nobody', )
```
Example 4: Run local file script remotely with label
```
with open('/path/my/very/nice/script') as script_file:
Remote('user@host.domain').sh_file(script_file, …
```
=> orchestra: add remote.sh commands analogous to misc.sh

teuthology/orchestra/run.py, teuthology/task/install/rpm.py
=> task/install: run install commands in a concatenated string

teuthology/task/ceph_ansible.py
See https://github.com/ceph/ceph-ansible/pull/3199
=> ceph_ansible: Install netaddr

teuthology/misc.py
=> misc: optionally bind to v1+v2 addrs for mons

teuthology/kill.py
Signed-off-by: Shilpa Jagannath <smanjara@redhat.com>
=> Remove unused 'machine_type' parameter from kill_job()

teuthology/suite/run.py, teuthology/suite/test/test_build_matrix.py, teuthology/task/lockfile.py
Signed-off-by: Kyr <kyrylo.shatskyy@suse.com>
=> Fix flake8 pytest F632 errors

teuthology/test/test_repo_utils.py
Signed-off-by: Kyr <kyrylo.shatskyy@suse.com>
=> test_repo_utils: fix shared temporary directory

teuthology/nuke/__init__.py
Do not allow teuthology-nuke to delete all volumes on openstack.
There is a bug on some openstack clients that --name option
does not work correctly for 'openstack volume list' in contrast
to 'openstack server list' and lists all available volumes
ignoring '--name' option at all.
=> openstack: fix all volumes nuke

teuthology/coverage_report_standalone.py, teuthology/misc.py, teuthology/task/ceph_ansible.py
Start firewalld before starting ceph-ansible task
=> Fixes ceph-ansible timeouts

requirements.txt, setup.py
Use more recent version of mysql python module
=> python-cov: update python mysql dependency

teuthology/provision/cloud/openstack.py
=> cloud/openstack: log userdata for debug purpose

teuthology/nuke/actions.py, teuthology/task/clock.py
=> task/clock: add chrony support

teuthology/provision/cloud/openstack.py, teuthology/provision/cloud/test/test_openstack.py, teuthology/provision/cloud/test/test_openstack_userdata_conf.yaml
=> libcloud: read userdata from config

teuthology/orchestra/console.py
Fixes: http://tracker.ceph.com/issues/37681
=> teuthology/console: allow deferring login after reset

teuthology/run.py
=> initial_tasks: make it possible to disable ansible

teuthology/orchestra/remote.py
=> orchestra/remote: add a method to create temporary directory

docs/INSTALL.rst
Signed-off-by: Karol Mroz kmroz@suse.com
=> docs: add SUSE to list of bootstrapable operating systems

teuthology/exit.py, teuthology/run_tasks.py, teuthology/suite/matrix.py, teuthology/test/test_exit.py
=> suite/matrix: use isinstance for python3 compatibility

teuthology/lock/cli.py, teuthology/lock/ops.py
https://tracker.ceph.com/issues/42081
=> lock: update target os-type and os-version after provisioning

teuthology/lock/ops.py
Fixes: https://tracker.ceph.com/issues/42256
Signed-off-by: Ricardo Dias <rdias@suse.com>
=> lock/ops: remove import to break import loop

teuthology/ceph.conf.template
=> add note that ceph.conf.template should no longer be modified

teuthology/misc.py
=> misc: drop StringIO import to fix flake8

teuthology/lock/cli.py, teuthology/misc.py, teuthology/nuke/actions.py, teuthology/orchestra/cluster.py, teuthology/task/background_exec.py, teuthology/task/ceph_ansible.py, teuthology/task/clock.py, teuthology/task/exec.py, teuthology/task/install/__init__.py, teuthology/task/install/redhat.py, teuthology/task/install/util.py, teuthology/task/internal/__init__.py, teuthology/task/internal/check_lock.py, teuthology/task/internal/lock_machines.py, teuthology/task/internal/redhat.py, teuthology/task/internal/syslog.py, teuthology/task/internal/vm_setup.py, teuthology/task/kernel.py, teuthology/task/lockfile.py, teuthology/task/mpi.py, teuthology/task/parallel_example.py, teuthology/task/pexec.py, teuthology/task/selinux.py, teuthology/task/ssh_keys.py, teuthology/task/tests/test_locking.py
=> python3: get rid of iterkeys for compatibility

teuthology/misc.py, teuthology/repo_utils.py
This adds possibility to checkout github pr providing special purpose ref spec (like refs/pull/X/merge and refs/pull/X/head) as branch parameter to teuthology, for example, "teuthology-suite -t".
=> repo_utils: support github pull request branches

teuthology/task/internal/redhat.py
Signed-off-by: rakeshgm <rakeshgm014@gmail.com>
=> added rhel-8 appstream and baseos rpms for subscripion

teuthology/contextutil.py, teuthology/misc.py, teuthology/parallel.py
=> core: use six.reraise for py2/py3 compatibility

teuthology/run.py, teuthology/task/internal/__init__.py, teuthology/test/test_run.py
=> run: drop StringIO usage for py3 compatibility

teuthology/task/ansible.py, teuthology/task/ceph_ansible.py, teuthology/task/install/__init__.py, teuthology/task/internal/__init__.py, teuthology/task/kernel.py, teuthology/test/task/__init__.py, teuthology/test/task/test_ansible.py, teuthology/test/task/test_ceph_ansible.py, teuthology/test/task/test_install.py, teuthology/test/task/test_selinux.py
=> ceph_ansible: make code py3 compatible

requirements.txt, teuthology/provision/cloud/test/test_openstack.py
Use latest and greatest apache-libcloud
=> deps: bump apache-libcloud from 1.5.0 to 2.6.0

teuthology/task/internal/redhat.py
Signed-off-by: rakeshgm <rakeshgm014@gmail.com>
=> changed subscription username

teuthology/misc.py, teuthology/openstack/__init__.py, teuthology/orchestra/run.py, teuthology/packaging.py, teuthology/parallel.py, teuthology/provision/cloud/openstack.py, teuthology/provision/cloud/test/test_cloud_init.py, teuthology/provision/cloud/test/test_cloud_util.py, teuthology/provision/cloud/util.py, teuthology/report.py, teuthology/suite/matrix.py, teuthology/suite/test/test_build_matrix.py, teuthology/suite/util.py, teuthology/test/test_contextutil.py, teuthology/test/test_describe_tests.py, teuthology/test/test_run.py, teuthology/test/test_timer.py
Fixes: https://tracker.ceph.com/issues/42871
=> make cloud openstack py3 compatible

teuthology/lock/__init__.py, teuthology/lock/cli.py, teuthology/lock/keys.py, teuthology/lock/ops.py, teuthology/orchestra/console.py, teuthology/orchestra/remote.py, teuthology/task/internal/lock_machines.py
Fixes: https://tracker.ceph.com/issues/42871
=> remove circular imports

teuthology/suite/util.py
=> suite/util: add opensuse to distro defaults

teuthology/orchestra/opsys.py
=> orchestra/opsys: enable centos 8

docs/INSTALL.rst, requirements.txt, setup.py
Fixes: https://tracker.ceph.com/issues/43192
=> setup.py: add missing dependencies of tests

teuthology/orchestra/daemon/cephadmunit.py, teuthology/orchestra/daemon/group.py
=> orchestra: ceph-daemon -> cephadm

teuthology/misc.py, teuthology/task/install/rpm.py, teuthology/task/kernel.py
misc fixes for kernel and install tasks for centos8/rhel8
=> task/kernel,install: misc fixes for el8

teuthology/task/install/daemon-helper
=> task/install/daemon-helper: python3

teuthology/provision/cloud/openstack.py, teuthology/provision/fog.py
=> provision: fix the error message when a distro image is not found

setup.py
=> setup.py: move more modules back to "install_requires"

teuthology/orchestra/daemon/cephadmunit.py
These are both needed by thrashosds.
=> orchestra/daemon/cephadmunit: implement kill, wait

teuthology/task/selinux.py
Fixes: https://tracker.ceph.com/issues/43396
=> task/selinux: ignore recent rhel8 selinux denials

teuthology/orchestra/daemon/cephadmunit.py
Using 'podman logs' is racy because the command may start before the
container starts, or even after it start and exits.
=> orchestra/daemon/cephadmunit: use journalctl to monitor stdout/err

teuthology/task/ceph_ansible.py
Fixes: https://tracker.ceph.com/issues/43798
=> ceph_ansible: Make ceph_installer.run args consistent

teuthology/task/kernel.py
Part one - this does not get us all the way, but it's a start!
=> task/kernel.py: fix -k distro for opensuse/sle (part 1)

teuthology/task/ceph_ansible.py
=> task/ceph_ansible: Work with LVM scratch devices

teuthology/task/kernel.py
=> kernel.py: fix -k distro for opensuse/sle (part 2)

teuthology/packaging.py
Fixes: https://tracker.ceph.com/issues/43655
Works Around: https://tracker.ceph.com/issues/44183
=> packaging: add Shaman repo correctly on opensuse

teuthology/task/ceph_ansible.py, teuthology/task/internal/redhat.py
Modifications enables teuthology to enable relevant repos on RHEL7 for RHCS 3.x and 4.x and on RHEL8 for RHCS 4.x
Signed-off-by: Vasishta <vashastr@redhat.com>
=> Handles enabling of rhel 7 repos for RHCS 3.x and 4.x

teuthology/orchestra/cluster.py
For simplified outputs processing it might be usefull
to have a function will return all captured log from
all remote hosts in the given sequence.
=> orchestra/cluster: add sh() method

teuthology/misc.py
This lets us attach to the process later.
=> teuthology/misc: pass --vgdb=yes to valgrind

bootstrap, scripts/test/script.py, teuthology/__init__.py, teuthology/kill.py, teuthology/misc.py, teuthology/orchestra/daemon/systemd.py, teuthology/orchestra/remote.py, teuthology/orchestra/run.py, teuthology/orchestra/test/test_remote.py, teuthology/orchestra/test/test_run.py, teuthology/packaging.py, teuthology/provision/cloud/base.py, teuthology/provision/cloud/util.py, teuthology/repo_utils.py, teuthology/suite/placeholder.py, teuthology/suite/run.py, teuthology/suite/test/test_run_.py, teuthology/suite/util.py, teuthology/task/__init__.py, teuthology/task/install/deb.py, teuthology/task/kernel.py, teuthology/task/mpi.py, teuthology/task/pcp.py, teuthology/task/selinux.py, teuthology/test/task/test_ansible.py, tox.ini
This PR adds py3 compatibility support
It also enable py3 unit teuthology PR testing
=> py3 compatibility

teuthology/suite/placeholder.py
=> suite: debug mgr by default

teuthology/orchestra/connection.py
Add a keytype to use ssh.
Signed-off-by: Feng Hualong <hualong.feng@intel.com>
=> orchestra: add ed25519key keytype to connection

bootstrap
Tested on Linux Mint 19.3
Signed-off-by: ishanrai05 <ishanrai05@gmail.com>
=> Add bootstrap support for LinuxMint

teuthology/task/ceph_ansible.py
=> ceph_ansible: Remove unnecessary package install/removal

teuthology/repo_utils.py, teuthology/test/test_repo_utils.py
add some improvement about convert repo url to dirname
Signed-off-by: Vicente Cheng <freeze.bilsted@gmail.com>
=> repo_utils: improve the handling about another git ssh expression

teuthology/task/ceph_ansible.py, teuthology/task/internal/redhat.py
Tested with all below combinations:
```
- RHceph4_0 with rhel8_1
- RHceph4_0 with rhel7_7
- RHceph3_3 with rhel7_7
```
=> added rhbuild attribute

teuthology/orchestra/daemon/systemd.py
=> code changes to retrieve correct daemon pid

teuthology/task/install/__init__.py, teuthology/task/install/redhat.py
Removing `extra_packages` and `extra_system_packages` under `install` task and added to `redhat` install task 
Signed-off-by: rakeshgm <rgowdege@redhat.com>
=> extra_packages and extra_system_packages added to redhat install task

teuthology/task/internal/redhat.py
`Updated code changes for config error excpetion w.r.t rhbuild attribute`
=> updated config error exception w.r.t rhbuild

teuthology/orchestra/daemon/systemd.py, teuthology/task/ceph_ansible.py
=> code changes for multiple rgw daemons in single host

teuthology/suite/run.py
=> teuthology/suite: extract match() for filtering jobs

teuthology/task/ceph_ansible.py
=> code changes w.r.t ceph ansible cluster-name

teuthology/orchestra/opsys.py
=> opsys: Add Focal Fossa

teuthology/orchestra/daemon/systemd.py
=> updated pid method to retrieve correct daemon process id

teuthology/task/install/redhat.py, teuthology/task/internal/redhat.py, teuthology/test/task/test_install.py
=> various updates to redhat internal install task

teuthology/orchestra/connection.py
This reverts commit 1e30d6f624921ae98c27981d55e06c29d1b0fdd0.
=> Revert "teuthology/orchestra/connection: add retry exceptions"

teuthology/run.py, teuthology/run_tasks.py, teuthology/task/internal/__init__.py, teuthology/task/internal/git_ignore_ssl.py, teuthology/task/internal/redhat.py
added couple of the internal tasks for redhat that were missing and fixes for the same. 
=> fixes for redhat internal tasks

requirements2.txt, requirements3.txt, setup.py
=> setup.py: add toml for qa/tasks/cephadm.py

teuthology/run_tasks.py, teuthology/templates/email-sleep-before-teardown.jinja2, teuthology/test/test_email_sleep_before_teardown.py
=> run_tasks: add email notification for sleep-before-teardown

teuthology/provision/pelagos.py
=> provision/pelagos: improve logging

bootstrap, requirements.in, requirements2.txt, requirements3.txt, setup.py, teuthology/results.py
I think it's been years since anything in the project used the
mysqlclient package, so let's stop making everyone install it and everything it requires.
=> Drop MySQL dependency

teuthology/orchestra/run.py, teuthology/orchestra/test/test_run.py
needed by  https://github.com/ceph/ceph/pull/35260
=> orchestra/run: py2 fix for copy_and_close

bootstrap, requirements.in, requirements2.txt, requirements3.txt, scripts/suite.py, setup.py, teuthology/orchestra/console.py, teuthology/results.py, teuthology/suite/__init__.py, teuthology/suite/build_matrix.py, teuthology/suite/run.py, teuthology/suite/test/test_build_matrix.py, teuthology/suite/test/test_init.py, teuthology/suite/test/test_run_.py, tox.ini
This is only cherry-pick -x commits
=> py2 backports 05-06-2020

bootstrap
adding python3 packages for fedora and RedHat based systems. 
=> bootstrap: python3 packages for fedora and redhat based systems

teuthology/run.py
- code changes to avoid multiple kernel task entries in tasks list.
=> eliminating kernel task duplication

docs/INSTALL.rst
=> docs: create a python3 virtualenv instead a py2 one

teuthology/orchestra/daemon/systemd.py
=> Fixed empty string split issue

teuthology/worker.py
=> Fix worker crash on report.try_delete_jobs

teuthology/provision/downburst.py
=> provision/downburst: py3 fixes

teuthology/task/selinux.py
=> ignore selinux errors from ksmtuned

teuthology/task/internal/redhat.py
Read redhat repos list from downstream.yaml instead of hard coding here. 
=> read redhat repos list from downstream.yaml

teuthology/run.py
=> added user option to perform rh kernel update

requirements.txt, teuthology/provision/cloud/__init__.py, teuthology/provision/cloud/openstack.py, teuthology/task/clock.py
- Code changes on RHOS downstream OSP.
=> PSI downstream changes

roles/overrides.yaml, teuthology/suite/placeholder.py
Corresponding ceph change https://github.com/ceph/ceph/pull/36527
Signed-off-by: Neha Ojha <nojha@redhat.com>
=> roles/overrides, placeholder.py: add log-ignorelist

teuthology/suite/__init__.py
=> set max job time for system tests

docs/requirements.txt
so we can built this project using readthedocs.org
=> doc: add requirements.txt

teuthology/run_tasks.py, teuthology/templates/task-results.html, teuthology/test/test_email_sleep_before_teardown.py
- Added task level log files in archive directory.
- Creating job html report file and placing inside archive directory 
=> Added task level log files and job tasks html report file in archive directory 

teuthology/polarion/__init__.py, teuthology/run_tasks.py, teuthology/templates/task-results.html, teuthology/test/test_email_sleep_before_teardown.py
- Added task level log files.
- job tasks html report file in archive directory.
=> Added task level log files and job tasks html report file

bootstrap
=> bootstrap: correct the check for --use-feature=2020-resolver

teuthology/provision/pelagos.py
Pelgos should not wait end of parking process (booting to maintenance image) while node is nuked.
=> provision/pelagos: improve parking speed

teuthology/misc.py, teuthology/test/test_misc.py
Add to calls misc.canonicalize_hostname and misc.decanonicalize_hostname
support of empty domains, created tests for it.
=> Makes (de)canonicalize_hostname ready to empty domains

teuthology/task/install/redhat.py, teuthology/task/internal/redhat.py
fetch the dowstream yaml location from
downstream teuth_config and redhat install tasks
to accept lists too
=> redhat downstream yaml location changed and redhat install tasks to accept lists

scripts/suite.py, setup.py, teuthology/config.py, teuthology/run_tasks.py, teuthology/suite/run.py, teuthology/templates/rocketchat-sleep-before-teardown.jinja2
Add Rocket.Chat notification for sleep before teardown.
=> teuthology-suite: add Rocket.Chat notification

teuthology/task/install/__init__.py
=> install: pass the 'shaman' to Shaman class

teuthology/task/install/util.py
The 'ship_utilities_early: True' will make the 'install' tasks skip
shipping the utilities and will add a separate task to ship them
earlier than all the other tasks. This could make sure that the
utilities will be unwinded at the last time in case that some other
tasks will use the utilitied when unwinding.
=> teuthology: add a seprate task to ship the utilities

teuthology/run_tasks.py
=> run_tasks: correct typo tuethology -> teuthology

teuthology/__init__.py
=> version: increase version to 1.1.0 since we have dispatcher

README.rst
=> readme: fix teuthology docs link at docs.ceph.com

teuthology/task/ceph_ansible.py
Fixes: https://tracker.ceph.com/issues/49485
=> ceph_ansible: Satisfy 'six' dependency

teuthology/suite/placeholder.py
Signed-off-by: Neha Ojha <nojha@redhat.com>
=> suite/placeholder.py: lower osd specific debug levels

teuthology/orchestra/console.py
Fixes: https://tracker.ceph.com/issues/45570
=> orchestra/console: raise RuntimeError when fail to power on

teuthology/run.py
- Include install task to download all RPM packages.
**Test result:**
http://magna002.ceph.redhat.com/ceph-qe-logs/Sunil/test_cephadm-1905-12/tasks/install-1.log
=> Include install task to get all RPM pkgs

teuthology/task/install/rpm.py
Locally I had hit the same issue when installing packages it will fail
with repo metadata downloading and some other failures. Mostly this can
recovery later.
Fixes: https://tracker.ceph.com/issues/47852
=> rpm: retry installing packages if mirrors are temporarily unreachable

teuthology/task/exec.py
=> tasks/exec: add all-roles, all-hosts keys

teuthology/provision/cloud/openstack.py, teuthology/provision/cloud/test/test_openstack.py
=> openstack: add exclude_image regex parameter

teuthology/dispatcher/supervisor.py, teuthology/kill.py, teuthology/orchestra/remote.py
The bonus commit will help us identify which hosts fail to reconnect in the future.
=> supervisor: To preserve logs, delay nuking

docs/INSTALL.rst
This only applies to the "Ubuntu, Fedora, & Suse/Opensuse" section.
Signed-off-by: Laura Flores <lflores@redhat.com>
=> docs: improve instructions for installing teuthology

teuthology/packaging.py, teuthology/test/test_packaging.py
The workaround from https://github.com/ceph/teuthology/pull/1649 was
necessary because my original algorithm was faulty: when searching
through all the builds for a ref/sha1, one must match the arch
requested by the call to build_complete (in the Builder object);
that arch's presence in the shaman api/search result is not enough
of a match, as it can contain multiple arches in multiple states
of build success.  Only a failure *on the requested arch* should be
considered a "requested build not complete".
(note: this will still currently fail a request for a build whose
repo is complete but container build failed, as "build complete"
currently conflates those two statuses.  Teuthology does not
contain the information whether a build is being requested for
packages, containers, or both.) …
=> teuthology/packaging.py: fix build_complete: search for requested arch

teuthology/task/clock.py, teuthology/task/internal/syslog.py, teuthology/task/kernel.py
=> task/{kernel,clock}: parallelize per-role work

.gitignore
=> gitignore: ignore .vscode dir

teuthology/orchestra/remote.py, teuthology/orchestra/test/test_remote.py
=> Remote: Add is_container property

teuthology/kill.py
Also, use sudo's -n flag to avoid the password prompt and resulting
delay.
Fixes: https://tracker.ceph.com/issues/53853
=> kill: Check if sudo works before using it

teuthology/task/clock.py
=> task.clock: Fix call to filter_out_containers()

docs/requirements.txt
bump sphinx to latest stable
Signed-off-by: Kamoltat Sirivadhna <ksirivad@redhat.com>
=> docs/requirements.txt: bump sphinx to 4.4.0

bootstrap
=> bootstrap: Don't auto-install on Mac

teuthology/orchestra/opsys.py
=> opsys.py: RHEL8.5 is latest

update-requirements.sh
otherwise the requirements used by test would be missed
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
=> update-requirements.sh: pass --extra=test to pip-compile

teuthology/repo_utils.py
=> bootstrap_teuthology: Call decode() on stderr

teuthology/repo_utils.py
for better readability
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
=> teuthology/repo_util: pass universal_newlines=True

scripts/suite.py
Table copied from https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/tests-integration-testing-teuthology-intro/.
Signed-off-by: Laura Flores <lflores@redhat.com>
=> scripts: add priority table to teuthology-suite --help

teuthology/suite/run.py, teuthology/suite/util.py
We were accidentally mangling them.
=> suite: Allow 'git@' repo URLs

bootstrap
=> bootstrap: If pip is missing, rebuild virtualenv

teuthology/orchestra/opsys.py
=> opsys.py: Default to RHEL8.6

teuthology/orchestra/opsys.py
=> opsys.py: Add RHEL9

teuthology/misc.py
This reverts commit 40fff4b2911949847a302adfe2f4714cfaccb58e, reversing
changes made to 93d2b653facc0e5a7a532b39d9ff91a044f2c4a9.
=> Revert "Merge pull request #1624 from batrick/get-valgrind-args"

docs/commands/teuthology-describe.rst, docs/commands/teuthology-prune-logs.rst, docs/commands/teuthology-reimage.rst, docs/commands/teuthology-update-inventory.rst, docs/commands/teuthology-wait.rst
=> docs/commands: Add missing commands

docs/fragment_merging.rst, docs/index.rst, scripts/schedule.py, setup.cfg, teuthology/describe_tests.py, teuthology/misc.py, teuthology/suite/fragment-merge.lua, teuthology/suite/merge.py, teuthology/suite/run.py, teuthology/suite/test/test_merge.py, teuthology/suite/test/test_run_.py, teuthology/suite/util.py
Documentation: https://github.com/batrick/teuthology/blob/yaml-preprocessor/docs/fragment_merging.rst
Ceph PR using this: https://github.com/ceph/ceph/pull/46882
Todo:
[x] Write tests
[x] Documentation
=> teuthology: add pre/post fragment merge hooks

docs/docker-compose/start.sh, docs/docker-compose/testnode/Dockerfile, docs/docker-compose/teuthology/teuthology.sh, teuthology/beanstalk.py, teuthology/suite/run.py
I expect these initial two commits to fail CI; I believe #1776 regressed somehow, but haven't fully debugged it yet.
=> Fix scheduling regression

teuthology/task/ansible.py
=> ansible.py: Default to main

teuthology/orchestra/opsys.py
=> opsys.py: Add Ubuntu 22.04

teuthology/nuke/__init__.py
=> nuke: Tolerate null node description

teuthology/orchestra/opsys.py
=> orchestra/opsys: add newer sle and leap versions

teuthology/kill.py
This fixes a regression in `teuthology-kill`
=> kill.kill_job: Tweak job status reporting

teuthology/beanstalk.py, teuthology/dispatcher/__init__.py, teuthology/dispatcher/supervisor.py, teuthology/lock/ops.py, teuthology/nuke/__init__.py, teuthology/task/ansible.py, teuthology/task/cephmetrics.py, teuthology/test/task/test_ansible.py, teuthology/test/test_imports.py, teuthology/test/test_worker.py, teuthology/worker.py
This fixes:
`ImportError: cannot import name 'kill_job' from partially initialized module 'teuthology.kill'`
=> Import fixes

requirements.txt, setup.cfg
This should have been added a couple PRs back.
=> requirements.txt: Add prometheus_client

teuthology/worker.py
This is preferable to letting the dispatcher die.
=> worker.prep_job: Skip job if ls_remote fails

teuthology/dispatcher/__init__.py, teuthology/dispatcher/supervisor.py, teuthology/provision/fog.py
Fog itself doesn't have very helpful logging, but I'm hoping this will help us shed some light on the sporadic reimaging failures we've been seeing.
=> fog: Add more debug logging

teuthology/dispatcher/__init__.py
This is so that ceph-devstack can report job failures
=> dispatcher: Return the highest of the jobs' RCs

teuthology/contextutil.py, teuthology/orchestra/remote.py, teuthology/provision/fog.py
Looks like this was missed during PR submission/review in 8f8d058
=> FOG._wait_for_ready: Tolerate ConnectionResetError

teuthology/task/ansible.py
Fixes an error first seen here:
https://sentry.ceph.com/organizations/ceph/issues/42041/
=> Ansible._handle_failure: Catch all Exceptions

teuthology/task/ansible.py, teuthology/test/task/test_ansible.py
I still want to catch `Exception`s so that we don't fail jobs because of unexpected object structures.
=> ansible.FailureAnalyzer: Look for SSH errors; improve special case handling

teuthology/orchestra/console.py
This will make reading console debug logging easier.
=> orchestra.console: Scope loggers to shortname

teuthology/provision/fog.py
=> fog: Drop request debug logging

.github/workflows/dev_container.yml
=> .github: Add workflow to build dev container

teuthology/kill.py
The list comprehension was incorrect.
Fixes: https://tracker.ceph.com/issues/66440
=> kill: Fix killing by owner

teuthology/kill.py, teuthology/test/test_kill.py
Fixes: https://tracker.ceph.com/issues/66440#note-1
=> teuthology/kill.py: Fix "TypeError: 'NoneType' object is not iterable"

teuthology/lock/ops.py
We should try to call stop_node before unlock and don't even try to do this for vms.
=> lock/ops: try to stop_node before unlock

bootstrap
This is just a refactor for maintainability.
=> bootstrap: Simplify dependency checking/install

teuthology/run.py, teuthology/test/test_run.py
Fixes: https://tracker.ceph.com/issues/68285
=> run: Fix reference to ctx for interactive jobs

scripts/node_cleanup.py, teuthology/lock/query.py
=> node-cleanup: Grace period for inactive jobs

teuthology/lock/query.py
This is because we only want this grace period
when looking for stale jobs. Not when jobs are
being unlocked by the supervisor by unlock_one_safe().
Fixes: https://github.com/ceph/teuthology/pull/2033#issuecomment-2703733380
=> lock/query.py: add grace_time param to node_active_job()

.github/workflows/dev_container.yml
These are the most recent v3 releases for these actions.
=> workflows/dev_container: Pin docker actions

.github/workflows/ci.yml, .github/workflows/dependencies.yml
GitHub doesn't provide the image anymore.
=> ci: Drop Ubuntu 20.04

teuthology/misc.py, teuthology/suite/run.py, teuthology/suite/test/test_run_.py, teuthology/test/test_misc.py
Revert previous fix for https://tracker.ceph.com/issues/71612 as it created a new regression https://tracker.ceph.com/issues/71911. 
Second commit adds a new fix to the original issue (71612).
=> Fix wrong os-type issue

containers/teuthology-dev/Dockerfile
Solves - https://tracker.ceph.com/issues/72056
=> Add jq and curl to teuthology-dev Dockerfile

docs/requirements.txt
Solves - https://tracker.ceph.com/issues/72055
=> Add openstack dependencies in docs/requirements
